### ISSUE TITLE
你好 问下 我mvvm模式 viewmodel里面不适合传入context 请问怎么操作

### ISSUE THREAD

**Issue by CPC-Coder** [getActivity/EasyHttp#100]
## 建议收集
在android jetpack应用指南的书里 说道viewmodel里面不适合传入context 会造成内存泄漏
* issue 是否有人曾提过类似的问题？（必答项，一旦出现重复提问我将不会再次解答）
否
* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）

* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）

**Comment by getActivity** [comment]
小伙子，你这个问题和 EasyHttp 有什么关联？

**Comment by CPC-Coder** [comment]
牛逼  传入的是LifecycleOwner  LifecycleOwner  确实不会影响生命周期
原本以为是context
