### ISSUE TITLE
大佬，支持自定义UA么？

### ISSUE THREAD

**Issue by DodoSpringLove** [getActivity/EasyHttp#101]
## 建议收集

* issue 是否有人曾提过类似的问题？（必答项，一旦出现重复提问我将不会再次解答）

* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）

* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）

**Comment by getActivity** [comment]
https://baidux.tinoy.cn/?q=OkHttp%20%E6%80%8E%E4%B9%88%E8%AE%BE%E7%BD%AE%20UA
