### ISSUE TITLE
建议code在onFail里面也返回

### ISSUE THREAD

**Issue by ender115** [getActivity/EasyHttp#102]
## 建议收集

* issue 是否有人曾提过类似的问题？（必答项，一旦出现重复提问我将不会再次解答）
无
* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）
code只能在onSucceed里面才能拿到，有时候需要根据不同的code做不同的业务处理
* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）
建议code在onFail里面也返回，可以根据不同的code做不同的业务处理

**Comment by getActivity** [comment]
<img width="992" alt="image" src="https://user-images.githubusercontent.com/28616817/155087214-75d461ca-d0d0-451a-86fa-339659ef4b5d.png">

**Comment by ender115** [comment]
可以了  多谢轮子哥
