### ISSUE TITLE
HTTP Code based dynamic response types

### ISSUE THREAD

**Issue by omkar-tenkale** [getActivity/EasyHttp#104]
Does this library support multiple response based on response code

eg I want to get FormSubmitSuccessBean for HTTP 200 and FormErrorResponseBean for  HTTP 400

I tried to study com.hjq.http.listener.HttpCallback and IRequestHandler but unable to come to a good solution

Great library by the way, would love to use in my project
Retrofit doesn't support multiple response types

I'm imagining something like some handler where i can define specific Bean modal for specific http error code

**Comment by omkar-tenkale** [comment]
Some related links
https://mochadwi.medium.com/android-handle-dynamic-json-response-using-retrofit-5cc5a4ccd641

**Comment by omkar-tenkale** [comment]
I can see one way of doing is by using custom OnHttpListener 


    void onSucceed(JsonObject result) {
        switch(code){
             case 200: 
         }

    }

....

ahhhhhhhhhh cant find a solution 🤯🤯🤯

**Comment by fengzehao** [comment]
You can try to process it in RequestHandler. If 400 throws an exception in the requestSucceed() method, it will call back to the requestFail() method, and then process your FormErrorResponseBean separately in requestFail().

After processing like above, you can handle it in onFail.
I feel like this should work, you can try it.
`EasyHttp.post(this)
                 .api(new RefreshApi())
                 .request(new OnHttpListener<JSONObject>() {
                     @Override
                     public void onSucceed(JSONObject result) {
                     }

                     @Override
                     public void onFail(Exception e) {
                     }
                 });`

**Comment by fengzehao** [comment]
You can try to process it in RequestHandler. If 400 throws an exception in the requestSucceed() method, it will call back to the requestFail() method, and then process your FormErrorResponseBean separately in requestFail().

After processing like above, you can handle it in onFail.
I feel like this should work, you can try it.

`@Override
                     public void onSucceed(JSONObject result) {
                     }

                     @Override
                     public void onFail(Exception e) {
                     }`

**Comment by fengzehao** [comment]
You can try to process it in RequestHandler. If it is 400, process your FormErrorResponseBean in the requestSucceed() method and throw an exception, which will call back to the requestFail() method, and then return the error message in requestFail().

After the above processing, you can receive the specific error message in onFail.
I feel like this should work, you can try it.

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/155920044-3db9676a-75e5-4d49-85c9-30e0d47e2d50.png)

**Comment by getActivity** [comment]
See if that solves your problem?

**Comment by omkar-tenkale** [comment]
Seems like my problem is much more complex 

Api can return any code 200,400,404,500 or whatever WITH a body

/endpoint1   Can respond  200,400,404
/endpoint2 Can respond only 200,400

The client should declare for what codes it expects custom response and what the response models are

.request(new HttpCallBack<200Modal,400Modal,...)

But I feel like the my concept is not clear, I should work on it first
Thanks for the response guys!
