### ISSUE TITLE
setServer bug

### ISSUE THREAD

**Issue by AdminQQZ** [getActivity/EasyHttp#105]
## 问题描述
  EasyConfig.with(okHttpClient)
                // 设置服务器配置
                .setServer(server)

在初始化设置服务的时候，都没问题，但我项目有一个接口是需要用到别的服务器主机，然后我就这样写
![image](https://user-images.githubusercontent.com/12959954/156487056-9ad79e98-508a-487a-ac1c-e5f8fd6d70a5.png)
f发现 无法替换，并且出现又对又错的情况
![Uploading BAO9G30V`A_YJG3J93$A[40.png…]()

初始化配置的时候，不写服务还不行，这点有点太强制了。

* 框架版本：最新版本

* 问题描述：XXX

* 复现步骤：XXX

* 是否必现：填是/否

* 手机信息：例如某米 9 / Android 10

## 请回答

* 是部分机型还是所有机型都会出现：部分/全部（例如：某为，某 Android 版本会出现）

* 框架最新的版本是否存在这个问题：是/否（如果用的是旧版本的话，建议升级看问题是否还存在）

* 是否已经查阅框架文档还未能解决的：是/否（文档会提供最常见的问题解答，可以看看是否有自己想要的）

* issue 是否有人曾提过类似的问题：是/否（看看曾经有人提过类似的问题，先参考一下别人是怎么解决的）

* 是否可以通过 Demo 来复现该问题：是/否（排查一下是不是自己的项目代码写得有问题导致的）

* 使用原生的 OkHttp 来实现是否也会出现该问题：是/否（排查一下是不是 EasyHttp 的代码存在问题导致的）

## 其他

* 提供报错堆栈（如果有报错的话必填）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by AdminQQZ** [comment]
![image](https://user-images.githubusercontent.com/12959954/156487452-357c4f6e-1490-4e4c-bf5b-a3f2586c559e.png)

**Comment by AdminQQZ** [comment]
![image](https://user-images.githubusercontent.com/12959954/156488012-3d1f254b-eeb2-444c-9a83-e6691ece6d26.png)
需要外部实现更改host主机

**Comment by getActivity** [comment]
<img width="621" alt="image" src="https://user-images.githubusercontent.com/28616817/156493066-57a43b52-9d6c-49f6-87d7-6aa56a34dec5.png">
