### ISSUE TITLE
怎么获取到下载链接的文件名？

### ISSUE THREAD

**Issue by LEMON521** [getActivity/EasyHttp#106]
## 建议收集

* issue 是否有人曾提过类似的问题？（必答项，一旦出现重复提问我将不会再次解答）

* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）

* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）

比如这种的下载连接
http://XXX.XXX.XX1.1XX0/X/XX/admXX_down?time=1111222233&key=dad65a94465XXXXX&id=138441321212313210&certificateType=3

**Comment by getActivity** [comment]
https://baidux.tinoy.cn/?q=%E4%BB%8EURL%E4%B8%AD%E8%8E%B7%E5%8F%96%E6%96%87%E4%BB%B6%E5%90%8D%E7%A7%B0
