### ISSUE TITLE
Json格式转换出错 LinkedTreeMap cannot be cast to  XXX

### ISSUE THREAD

**Issue by hais1992** [getActivity/EasyHttp#107]
## 问题描述

* 框架版本：10.8

* 问题描述：不能正确识别监听器的泛型类型，导致json解析转换出错。
* 类似问题如 https://blog.csdn.net/qq_36652498/article/details/107457231

* 复现步骤：参考图片
* 
![image](https://user-images.githubusercontent.com/91512491/156722742-ed3447bd-5eaf-43a0-9cfc-27550013a955.png)
![image](https://user-images.githubusercontent.com/91512491/156722926-5137e62c-5426-4a90-8035-d13e32e32918.png)

* 是否必现：是

**Comment by hais1992** [comment]
发送网络请求时，的泛型填写  BaseMode<String> 
调试过程中截图如下
![image](https://user-images.githubusercontent.com/91512491/156724099-6880e2d6-19a6-4808-8ba9-0e3797f48bac.png)
![image](https://user-images.githubusercontent.com/91512491/156724210-5b6b6414-a58a-4207-8e52-d60efa1e534d.png)

**Comment by getActivity** [comment]
小伙子，我可以明确告诉你的是，这种代码封装是存在问题的，一旦你在调用的地方设置了未指明类型的泛型 `T`，那么用框架是没有办法解析出来的，无论是用 EasyHttp 解析，还是用 Gson 解析，结果都是一样的。

**Comment by getActivity** [comment]
还有这个问题不属于框架的 Bug，如果你一定要那么做，可以考虑 fork 一份源码到本地，然后自己进行适配。

**Comment by w1984908499** [comment]
请问你解决这个问题了吗

**Comment by getActivity** [comment]
<img width="804" alt="Image" src="https://github.com/user-attachments/assets/b70bd6df-357b-4628-8c45-2a49d6732036" />

**Comment by getActivity** [comment]
https://github.com/getActivity/EasyHttp/issues/271
