### ISSUE TITLE
上传文件 有文件名 为中文 且有要求的格式如何上传

### ISSUE THREAD

**Issue by CPC-Coder** [getActivity/EasyHttp#108]
## 建议收集

* issue 是否有人曾提过类似的问题？（必答项，一旦出现重复提问我将不会再次解答）

* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）
1  后端 上传文件有 根据文件作为参数 上传文件  但是框架不能上传    或者怎么样 传入 文件名
2 okhttp3请求头中含中文报错原因 请问是怎么处理 比较好奇   可能会会遇到这种问题  网上总觉得不大好

* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）

**Comment by getActivity** [comment]
文件名参数，框架会自动根据你传入的文件名称来获取文件名称，然后自动传给后台，你只需要直接传入 File 对象给框架即可，如果你不想用 File 的文件名作为参数，那么你只能自定义 RequestBody 来做了（可以使用 OkHttp 自带的 MultipartBody），具体使用方法，框架文档上面有写。

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/28616817/156745493-4248f590-6f54-4236-b516-aa7e9b36a3be.png">

**Comment by getActivity** [comment]
关于 OkHttp 请求头中参数包含中文会报错的问题，这个问题框架内部已经处理了，你只需要保证当前使用的框架版本是最新的即可。

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/28616817/156745894-ebcdacb9-40db-4597-b92e-774d57d418e1.png">

**Comment by CPC-Coder** [comment]
谢谢 轮子哥  牛逼
