### ISSUE TITLE
问下 假如有一种需求:   我finish掉activity  但是请求还需要继续

### ISSUE THREAD

**Issue by CPC-Coder** [getActivity/EasyHttp#109]
## 建议收集

* issue 是否有人曾提过类似的问题？（必答项，一旦出现重复提问我将不会再次解答）

* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）
* 我finish掉activity  但是请求还需要继续,例如:我为了可能后台还在上传文件,但是为了客户体验,finish掉某个activtity或某个lifecycle, 由于框架自动管理生命周期,请问怎么延长生命周期.   是传入app lifecyle   ,然后手动取消生命周期?  或者大佬 有什么更好的方式 学习下

* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）

**Comment by getActivity** [comment]
框架文档上面没有写？
