### ISSUE TITLE
一个接口就要新建一个文件，不觉得很麻烦吗

### ISSUE THREAD

**Issue by dary123** [getActivity/EasyHttp#11]
一个接口就要新建一个文件，不觉得很麻烦吗

**Comment by nszaaa3** [comment]
前后端约定好封装格式，写一个接口文件可以全局用。

**Comment by dary123** [comment]
> 前后端约定好封装格式，写一个接口文件可以全局用。

但是不同的接口肯定要写多个文件的，比如登录注册这块，之前用retrofit的时候只需要创建一个LogReg_Interface就行了，里面包含多个接口，但是这个库一个接口就需要创建一个接口文件，每个接口传的参数不可能一样的，所以没法全局用一个文件呀

**Comment by dary123** [comment]
![微信截图_20200628104329](https://user-images.githubusercontent.com/12826258/85936421-4c1f2d80-b92d-11ea-80d1-4264433340a0.png)
像这样，这个文件只能用于一个接口，不是太浪费了吗

**Comment by nszaaa3** [comment]
嘿嘿，我的意思是在前后端约定好封装的格式把数据封装在一个json里，不直接通过字段来请求，这样在调用接口的时候，只需要填parameter就可以。
![image](https://user-images.githubusercontent.com/15356343/85936577-cc925e00-b92e-11ea-9580-b56179010c00.png)

**Comment by getActivity** [comment]
把接口所有信息包装到一个类中，好处是维护起来方便，下次调用这个接口的时候不需要再去看后台文档，当后台接口有变动的时候，不需要一个个地方修改，只需要在这个类中修改就可以了

**Comment by getActivity** [comment]
前期开发的优势并不大，后期维护才能展现魅力

**Comment by nszaaa3** [comment]
我才理解你是不是想问怎么区分接口地址。。我的做法是服务端只暴露一个接口地址，移动端在接口文件里就只写这一个接口地址，那么服务端区分调用哪个接口的方法是根据移动端在header里边传的接口名或者新建一个字段用来传递调用哪个方法。
