### ISSUE TITLE
IRequestCache  增加自定义key

### ISSUE THREAD

**Issue by byc4426** [getActivity/EasyHttp#110]
## 建议收集
 一些api是公共api，和用户无关的，一些是跟用户有关api，都是没有参数或者参数都一样的api
 public Object readCache(HttpRequest<?> httpRequest, Type type, long cacheTime)
     跟用户有关的可以uid加上api为cacheKey 
     String cacheKey = "uid"+httpRequest.getRequestApi().getApi() + GsonFactory.getSingletonGson().toJson(httpRequest.getRequestApi());
    公共api就不能跟uid相关联，
    光是httpRequest 不好判断是公共api还是跟用户有关api，建议增加个自定义key判断
public Object readCache(HttpRequest<?> httpRequest, Type type, long cacheTime，String cacheKey)

**Comment by getActivity** [comment]
收到，多谢小伙子的建议，我会在下个版本更新 Demo 的用法。

**Comment by getActivity** [comment]
小伙子，框架已经更新，多留意一下。
