### ISSUE TITLE
使用放到外部存储目录下则需要适配分区存储下载崩溃，demo也是

### ISSUE THREAD

**Issue by zs18340282344** [getActivity/EasyHttp#111]
## 问题描述

* 框架版本：implementation 'com.github.getActivity:EasyHttp:10.0'
* 问题描述：下载崩溃但是应该不是下载框架问题，而是适配分区那崩溃了

* 复现步骤：fileName设置PPT模板使用手册.docx 下载链接 https://orangefuture.obs.cn-north-1.myhuaweicloud.com/e_files/a7db725a-d237-450b-b7df-80f98a398229.docx

* 是否必现：是 

* 手机信息：vivinex3s 安卓10系统
## 请回答

安卓11下载正常，安卓10崩溃

## 其他

报错信息
Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference

**Comment by getActivity** [comment]
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/28616817/160815299-09c46e78-292a-46b7-82e4-8ba86fe2e9e6.png">
