### ISSUE TITLE
Json方式提交时，框架会把Parcelable序列化后的javaBean在post时多一个CREATOR字段

### ISSUE THREAD

**Issue by lzy0016** [getActivity/EasyHttp#112]
## 问题描述

* 框架版本：10.8

* 问题描述：Json方式提交时，框架会把Parcelable序列化后的javaBean在post时多一个CREATOR字段

* 复现步骤：XXX

* 是否必现：是

* 手机信息：小米8

{
        "talling": {
            "containerpic1": "/upload//fjkcjs/202204/fjkcjs_1648807109456.jpeg",
            "jobid": "1509820220179779584",
            "ship_img": "/upload//fjkcjs/202204/fjkcjs_1648807109456.jpeg",
            "tallying_job_id": "1509822873798316032",
            "CREATOR": {},
            "is_submit": 0,
            "goods_full_img": "/upload//fjkcjs/202204/fjkcjs_1648807109456.jpeg",
            "port_img": "/upload//fjkcjs/202204/fjkcjs_1648807109456.jpeg",
            "type": 0,
            "goods_img": "/upload//fjkcjs/202204/fjkcjs_1648807109456.jpeg"
        },
        "token": "1000001870428136"
    这是打印的调用接口时提交的数据  可以看到有个 "CREATOR": {}, 后台的接口要求必须对应字段，所以我只能改成Serializable来序列化了

**Comment by getActivity** [comment]
<img width="840" alt="image" src="https://user-images.githubusercontent.com/28616817/161267849-3ef22c7d-9168-4b9d-a36a-56cf3969bc41.png">

**Comment by getActivity** [comment]
小伙子，问题修正了，用这个包再试一下
