### ISSUE TITLE
上传文件，文件名(中文)变乱码

### ISSUE THREAD

**Issue by JiangShuLiang** [getActivity/EasyHttp#113]
## 问题描述

* 框架版本：10.8

* 问题描述：文件上传，服务端接收到的文件名（中文）变成乱码。备注：有个特殊的点，就是此文件是来自外挂u盘里的而非手机存储里的。不清楚会不会是这个导致了乱码。

* 复现步骤：XXX

* 是否必现：是

* 出现问题的手机信息：红米k30s

* 出现问题的安卓版本：12（miui13.0.4）

## 请回答

* 是部分机型还是所有机型都会出现：全部

* 框架最新的版本是否存在这个问题：是

* 是否已经查阅框架文档还未能解决的：是

* issue 是否有人曾提过类似的问题：否

* 是否可以通过 Demo 来复现该问题：是

* 这个问题是不是后台自己的问题导致的：否（同一个上传接口也有web端在请求，但就不会乱码）

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，有几个事情需要你这边确认一下

**Comment by getActivity** [comment]
1. 这个是外部 U 盘存储的问题，还是手机存储的问题？
2. 文件名乱码，抓包看了吗？是不是传过去的文件名和后台接收到一样？
3. 文件名乱码，没有乱码的文件名叫什么？乱码后的文件名叫什么？

**Comment by JiangShuLiang** [comment]
> 



> 1. 这个是外部 U 盘存储的问题，还是手机存储的问题？
> 2. 文件名乱码，抓包看了吗？是不是传过去的文件名和后台接收到一样？
> 3. 文件名乱码，没有乱码的文件名叫什么？乱码后的文件名叫什么？

1.已确定不是存储问题，在手机上也试过，同样会乱码。
2.抓包已看，确定一致
3.没乱码的文件名叫“测试用txt”，乱码后：%E6%B5%8B%E8%AF%95%E7%94%A8txt.txt

以下是相关截图：
![22](https://user-images.githubusercontent.com/20485764/163908372-1d204d2f-c3ba-4057-bdd5-60ab4968382d.png)
![111](https://user-images.githubusercontent.com/20485764/163908376-1dff42dd-5aa9-4100-aa59-fc835ba23249.png)

**Comment by getActivity** [comment]
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/28616817/163910026-5bdd902e-56ee-4869-a850-f555bc541e94.png">

**Comment by getActivity** [comment]
小伙子，上传的文件名不能带中文，文件名带中文字符需要先进行编码，你如果不信可以用 OkHttp 的 API 试一下，文件名带中文 OkHttp 是会抛异常的。

**Comment by JiangShuLiang** [comment]
> 小伙子，上传的文件名不能带中文，文件名带中文字符需要先进行编码，你如果不信可以用 OkHttp 的 API 试一下，文件名带中文 OkHttp 是会抛异常的。

感谢解答了！弱弱问一下，有没有办法实现上传文件名是中文的文件呢？

**Comment by getActivity** [comment]
[EasyHttp-11.2.aar.zip](https://github.com/getActivity/EasyHttp/files/8536700/EasyHttp-11.2.aar.zip)

**Comment by getActivity** [comment]
小伙子，我刚刚试过了，上传的文件名可以带中文字符，不需要经过编码，这块代码我已经改了，你用这个包试试看。

**Comment by JiangShuLiang** [comment]
> 小伙子，我刚刚试过了，上传的文件名可以带中文字符，不需要经过编码，这块代码我已经改了，你用这个包试试看。

我刚试过，解决了！！！感谢作者！！！

**Comment by getActivity** [comment]
OKOK 的，小伙子，考虑到问题影响比较小，所以就不发布远程依赖了，你先用着这个包，等下个版本更新了你再改回来。
