### ISSUE TITLE
DELETE请求能增加 body 传递参数的功能吗？

### ISSUE THREAD

**Issue by liverloop** [getActivity/EasyHttp#114]
## 建议收集

* issue 是否有人曾提过类似的问题？（必答项，一旦出现重复提问我将不会再次解答）

* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）

* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）

**Comment by getActivity** [comment]
[EasyHttp-11.2.aar.zip](https://github.com/getActivity/EasyHttp/files/8536603/EasyHttp-11.2.aar.zip)

**Comment by getActivity** [comment]
<img width="882" alt="image" src="https://user-images.githubusercontent.com/28616817/164590449-db22c40b-1bf9-407a-9dbb-d5003c7513e8.png">

**Comment by getActivity** [comment]
小伙子，我加上了，你用这个包试试

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。

**Comment by bakonMa** [comment]
新版本里面没有加吗？求加上吧

**Comment by getActivity** [comment]
<img width="1099" alt="image" src="https://github.com/getActivity/EasyHttp/assets/28616817/2625d936-89d3-470e-a3f4-529acf8a0abf">

@bakonMa 有的，小伙子
