### ISSUE TITLE
下载文件没有判断404啊

### ISSUE THREAD

**Issue by harmydzh** [getActivity/EasyHttp#115]
* 框架版本：11.0

* 问题描述：下载文件时，文件不存在，依然下载成功。
![1650963312(1)](https://user-images.githubusercontent.com/96103266/165263098-f018b8f5-75c4-4926-8b00-3ea6eeeeed8f.png)

* 是否必现：是

**Comment by getActivity** [comment]
[EasyHttp-11.2.aar.zip](https://github.com/getActivity/EasyHttp/files/8568702/EasyHttp-11.2.aar.zip)

**Comment by getActivity** [comment]
小伙子，你用这个包试试看还会不会

**Comment by harmydzh** [comment]
11.2没有问题了

**Comment by getActivity** [comment]
OK 的，小伙子，这个包你先用着，后续我再发布一下远程依赖。
