### ISSUE TITLE
需要暂停上传或者下载任务的方法

### ISSUE THREAD

**Issue by Heart-Beats** [getActivity/EasyHttp#116]
## 建议收集    

* issue 是否有人曾提过类似的问题？
    未搜索到

* 你觉得框架有什么不足之处？
   我在做文件的上传或下载时使用此框架，有个需求需要暂停上传或者下载任务，发现没有此方法，希望大佬可以考虑添加暂停和重新唤醒任务的相关方法

**Comment by getActivity** [comment]
小伙子，断点下载后期会考虑加上的，多谢小伙子的提醒，但是现在我建议你先用别的框架来实现。

**Comment by getActivity** [comment]
小伙子，我后面再思考了一下，最终决定还是不加断点续传的功能，因为 EasyHttp 的定位是网络请求框架，不是下载框架，这两者有相似之处，但却属于两个不同类别的，如果你需要使用断点续传，建议使用其他第三方下载框架来实现。

**Comment by Heart-Beats** [comment]
大佬，EasyHttp 的定位是网络请求框架但是目前已经集成了上传和下载功能，这两个功能对于现在的 APP 都是不可或缺的，而且对于用户体验来说，断点续传相关的功能现在也很普遍，如果大佬觉得这两个真实属于不同的类别可以考虑将下载上传功能抽离出来，作为 EasyHttp  的扩展库，同时由于已有的功能存在，其实开发续断点续传也不是非常的复杂

**Comment by getActivity** [comment]
小伙子，这个不是复不复杂的问题，而是断点续传这种功能不应该出现在网络请求框架上面，严格点来说，EasyHttp 不应该做下载的功能，至于你说的抽离，我会考虑一下，如果市面上没有人做好，我才会考虑去做。
