### ISSUE TITLE
返回的为啥是LinkedTreeMap类型

### ISSUE THREAD

**Issue by csh159** [getActivity/EasyHttp#117]
![c4efbf4ef07e968970c4352cff0f9f8](https://user-images.githubusercontent.com/4157414/165894567-1c6db0a6-7244-45a9-b755-176cc91a0f37.png)
上面是返回的接口

下面提交代码
![1651213636(1)](https://user-images.githubusercontent.com/4157414/165894669-c9764444-6d02-4781-a252-b94c936a5dcb.png)

**Comment by getActivity** [comment]
<img width="915" alt="image" src="https://user-images.githubusercontent.com/28616817/165955185-dc4b6c1a-2b84-41f9-bb72-595d99f3ea10.png">

**Comment by getActivity** [comment]
小伙子，你写代码的时候没有察觉这里有异样么？你这样写泛型是解析不了的，Gson 对于一些解析不了的泛型，都是直接用 LinkedTreeMap 类型代替。

**Comment by getActivity** [comment]
超过五天没有响应，自动关闭此 issue。
