### ISSUE TITLE
java.lang.IllegalStateException: closed

### ISSUE THREAD

**Issue by Heart-Beats** [getActivity/EasyHttp#118]
## 问题描述

* 框架版本：11.0

* 问题描述：大佬，我在做文件上传时有个场景需要将返回的响应传给其他页面，因此设置 IRequestHandler 时直接返回了 Response， 但是当我在请求成功时调用 `response.body()?.string()` 即报错了，原因是该方法仅可被调用一次，具体代码可见截图。

* 复现步骤：XXX

* 是否必现：是

* 出现问题的手机信息：荣耀20Pro

* 出现问题的安卓版本：Android 10

## 请回答

* 是部分机型还是所有机型都会出现：未测试其他机型

* 框架最新的版本是否存在这个问题：是
* 
* 是否已经查阅框架文档还未能解决的：是

* issue 是否有人曾提过类似的问题：否

* 是否可以通过 Demo 来复现该问题：否

* 这个问题是不是后台自己的问题导致的：否

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

![image](https://user-images.githubusercontent.com/33248551/165941176-7d5d6a39-3174-4392-a958-dcca4bbc2ba0.png)

* 提供截图或视频（根据需要提供，此项不强制）

运行部分代码如下：
![image](https://user-images.githubusercontent.com/33248551/165941043-800dd681-a67a-4252-98bf-d73474997a97.png)

* 提供解决方案（如果已经解决了的话，此项不强制）
目前我看在 requestSucceed 成功中解析响应没有问题，因此可以在这里定义实体类进行接受转换，但是我目前的使用场景仅仅是上传文件时使用到，因此不想再去单独定义个基类去进行解析，请问大佬有好的解决方式吗？

**Comment by getActivity** [comment]
超过五天没有响应，自动关闭此 issue。

**Comment by Heart-Beats** [comment]
大佬 `response.body()?.string()` 这个调用是EasyHttp 主动调用的吗？我看我在 requestSucceed 中重新构建个新的 Response 还是会这样，所以感觉像是 EasyHttp 主动调用解析的。既然如此解析时基于原始响应构建个新的去解析，再将原始响应传递下去不是更好吗

**Comment by getActivity** [comment]
你可以用原生 OkHttp 试试看，就知道是不是 EasyHttp 的问题。

**Comment by getActivity** [comment]
https://github.com/getActivity/AndroidProject-Kotlin/issues/16

**Comment by getActivity** [comment]
@Heart-Beats 小伙子，这个问题应该和你是同一个问题，现在已经修复了。

**Comment by RXlung** [comment]
![image](https://github.com/getActivity/EasyHttp/assets/21995371/a9eac34e-2672-495c-ae35-f2899b5f6366)
