### ISSUE TITLE
为什么bean要写在IRequestApi,完全就不合理啊，如果多个API用同一个Bean怎么处理。

### ISSUE THREAD

**Issue by jackpanz** [getActivity/EasyHttp#119]
一个项目至少都有个十几网络取数据,多的有几十个网络取数据，写个URL、拼接一些参数还需要添加一个类来完成，就几句话的事情，这样也太麻烦了。
为什么bean要写在IRequestApi，多个API我可能需要用同一个bean，这样也不合理。

**Comment by getActivity** [comment]
小伙子，框架就是这么设计的，你如果不喜欢可以使用 OkGo，没有必要一定要用 EasyHttp，按照你自己的想法来就可以了。

**Comment by liangjingkanji** [comment]
那你用[Net](https://github.com/liangjingkanji/Net)吧

**Comment by chenxiaofei910714** [comment]
使用了你的很多框架，这个网络请求框架文档从头看到尾，我也是觉得请求个接口都要取写一个类有些不好
