### ISSUE TITLE
路径拼接

### ISSUE THREAD

**Issue by whl0718** [getActivity/EasyHttp#120]
String url = mRequestHost.getHost() + mRequestPath.getPath() + mRequestApi.getApi()

在使用过程中这三个路径中有一个不小心多加了个 / 号  ，导致路径不正确，感觉可以用正则或者其他方式拼接一下

**Comment by getActivity** [comment]
小伙子，`mRequestPath.getPath()` 这个概念在新版已经被移除掉了，只剩下 `String url = mRequestHost.getHost() + mRequestApi.getApi()`

**Comment by getActivity** [comment]
至于你说的一不小心多了一个 `/` 号，我试过可以正常请求的，所以我觉得问题不大，不需要太纠结。
