### ISSUE TITLE
OnHttpListener 的泛型需要外部传递进来怎么办

### ISSUE THREAD

**Issue by kanshenmekan** [getActivity/EasyHttp#121]
class XXX<泛型> implements OnHttpListener<泛型>
然后外部实例化的时候写入T泛型

**Comment by getActivity** [comment]
https://github.com/getActivity/EasyHttp/issues/107

**Comment by getActivity** [comment]
小伙子，你看看这个 issue 是不是跟你的问题差不多？

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
