### ISSUE TITLE
可以与Jetpack一起使用吗

### ISSUE THREAD

**Issue by zs18340282344** [getActivity/EasyHttp#124]
## 建议收集

* issue 是否有人曾提过类似的问题？（必答项，一旦出现重复提问我将不会再次解答）
* 没有

* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）
* 框架很好，在与Jetpack使用时，有些不会用，建议出个demo

* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）
* 出个与Jetpack使用的demo

**Comment by getActivity** [comment]
小伙子，这个问题属于个人使用的问题，我目前暂时只处理框架的 Bug 和建议。
