### ISSUE TITLE
LogStrategy43行，打印日志时报ANR

### ISSUE THREAD

**Issue by wyz-1992** [getActivity/EasyHttp#125]
## 问题描述  LogStrategy43行，打印日志时报ANR

* 框架版本：9.0

* 问题描述：打印日志，请求日志特别长时，报ANR

* 复现步骤：线上bug统计到的，请求参数居多的时候，比如我们上传用户的短信数据到服务端，短信数据剧多的时候

* 是否必现：否

* 出现问题的手机信息：vivo、oppo手机较多

* 出现问题的安卓版本：android11和12

## 请回答

* 是部分机型还是所有机型都会出现：全部

* 框架最新的版本是否存在这个问题：是/否（如果用的是旧版本的话，建议升级看问题是否还存在）

* 是否已经查阅框架文档还未能解决的：是

* issue 是否有人曾提过类似的问题：否

* 是否可以通过 Demo 来复现该问题：是/否（排查一下是不是自己的项目代码写得有问题导致的）

* 这个问题是不是后台自己的问题导致的：否
## 其他
![微信图片_20220622145806](https://user-images.githubusercontent.com/14249966/174965541-7566a6df-30bb-4170-9277-de549555e865.png)
![微信图片_20220622145812](https://user-images.githubusercontent.com/14249966/174965555-aac0664e-ad44-45b6-bc07-9c9c0d0747d6.png)
![微信图片_20220622145816](https://user-images.githubusercontent.com/14249966/174965559-dfc72b08-456e-44ed-8bb4-d9edc58f8a8c.png)

**Comment by getActivity** [comment]
<img width="636" alt="image" src="https://user-images.githubusercontent.com/28616817/175032421-569804be-8ef3-4d6d-8664-533cd5b74a66.png">

小伙子，EasyHttp 最新版本日志打印已经换成线程池来打印了，你直接升级到最新版本，后续有问题再反馈给我
