### ISSUE TITLE
crash：Expected URL scheme 'http' or 'https' but no colon was found okhttp3.HttpUrl$Builder.parse()

### ISSUE THREAD

**Issue by powermax-yangtao** [getActivity/EasyHttp#126]
## 问题描述

* 框架版本【必填】：10.2

* 问题描述【必填】：service中定时任务（http get请求）经常性无故crash。Lifecycle使用过LifecycleService 和 new ApplicationLifecycle()均无任务效果，请求几十次有一定概率出现CRASH。此问题在okhttp框架作者issue中有类似问题，但未提供有效解决方法。

* 复现步骤【必填】：偶发，暂未发现规律。

* 是否必现【必填】：否

* 出现问题的手机信息【必填】：公司自研平板

* 出现问题的安卓版本【必填】：5.1.1

## 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否
* 
* 是否可以通过 Demo 来复现该问题【必答】：否

* 这个问题是不是后台自己的问题导致的【必答】：否

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）
![image](https://user-images.githubusercontent.com/40649822/176390344-5780792f-e423-473e-80a2-ae975a5dcb40.png)

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，关于这个问题我无法给你解决，具体的原因如下：

1. 从你提供的报错截图来看，第一个没有报错的提示信息，第二个堆栈信息是被混淆过的，并且没有具体的报错行数，显得很没有诚意！

2. 你都认为这个问题是 OkHttp 的问题了，那么第一时间应该先找 OkHttp 的作者进行沟通，而不是找 EasyHttp 的作者。如果沟通无果后再找我也不迟。

3. 既然这个问题无法复现，我又怎么给你做修复？第一个怎么证明这个就是 OkHttp 的问题，而不是你的代码写法有问题？第二个怎么验证我的修改就是正确的，而不是越改越错？

**Comment by powermax-yangtao** [comment]
多谢轮子哥的指导，昨天写了套测试代码，知道了怎么排查问题了。
