### ISSUE TITLE
不管后端返回什么，都能当一个文件下载下来

### ISSUE THREAD

**Issue by Brislis** [getActivity/EasyHttp#127]
## 问题描述
  EasyHttp.download(ApplicationLifecycle.getInstance())
                    .method(HttpMethod.POST)
                    .file(new File(filePath,childName ))
                    .url(url)；
这里后端返回无应用权限的时候，也能把后端返回的json转化file

**Comment by getActivity** [comment]
<img width="726" alt="image" src="https://user-images.githubusercontent.com/28616817/177185098-c169b929-ad40-48b1-8558-7288b06b2804.png">

<img width="926" alt="image" src="https://user-images.githubusercontent.com/28616817/177185047-ceccb702-acd5-488b-83c0-b1091bca2276.png">
