### ISSUE TITLE
11.2版本中如何统一增加请求loading 

### ISSUE THREAD

**Issue by chinamingsss** [getActivity/EasyHttp#128]
## 建议收集

* 没有人提供 在 11.2的版本中没有了requestStart方法，无法增加请求loading

* 之前在10.2的版本中可以自定义一个requestHandler实现requestStart方法自定义显示请求loading，然后再需要显示loading的时候使用此requestHandler不需要显示loading的时候使用全局自定义的requestHandler但是更新完11.2版本后requestHandler里面去掉了requestStart方法无法添加loading了，这使我再之前用到的地方都失效了，我需要把所有的使用到的地方修改一遍，代价太大了

* 希望再最新版本11.2的版本乃至之后的所有新版本中可以保留此方法

**Comment by getActivity** [comment]
小伙子，我来解答你的疑问：

1. 最新版中 IRequestHandler 为什么删掉了 requestStart 和 requestEnd 的方法？

> 原因很简单，这种设计有瑕疵，无法根据场景灵活设定要不要显示对话框？对话框的样式是什么？我觉得应该放到外层的请求中才比较合理，你可以看到最新的 Demo 上面对于对话框的封装，是使用了 HttpCallback 类，里面有 onStart 和 onEnd 方法，运用了静态的代理设计模式，具体细节这里不再细讲。

2. 希望再最新版本11.2的版本乃至之后的所有新版本中可以保留此方法

> 我可以给明确答复，不会改，首先那种模式已经被验证过是有问题的，框架既然选择换了一种方式实现，那么就不会轻易换回去，除非你有足够的证据或者充分的理由来说服我，否则肯定是不会因为你个人的升级代价太大而改的，因为框架不止你一个人在用，你应该要考虑你的建议能真正带来什么改进，我才会考虑修改，否则一定是不会考虑的，你如果不认同我的说法，我只能建议你 fork 一份框架代码下来改。
