### ISSUE TITLE
下载文件时（post请求），接口出现校验出错的情况，依然返回一个file

### ISSUE THREAD

**Issue by Brislis** [getActivity/EasyHttp#129]
## 问题描述

* 框架版本【必填】：11.2

* 问题描述【必填】：当接口返回的数据并不是一个file（json）时，该框架依然当做file文件下载下来

* 复现步骤【必填】：
*  EasyHttp.download(ApplicationLifecycle.getInstance())
                        .method(HttpMethod.POST)
                        .file(new File(Environment.getExternalStorageDirectory().getAbsolutePath()+Constants.FILE_PATH_IMG,"childName" ))
                        .url("...")
                        .listener(new OnDownloadListener() {

                            @Override
                            public void onStart(File file) {
                                Log.d("Status","onStart");

                            }

                            @Override
                            public void onProgress(File file, int progress) {
                                Log.d("Status","onProgress");
                            }

                            @Override
                            public void onComplete(File file) {//下载完成
                                Log.d("Status","onComplete");
                                //不管接口出现什么问题，都会走到这里并且，比如接口返回{code:500,msg:"请求出错"}，依然会当做文件下载， 
                               //修改后缀为TXT后打开即这个json的内容
                           
                            }

                            @Override
                            public void onError(File file, Exception e) {
                                Log.d("Status","onError");
                            }

                            @Override
                            public void onEnd(File file) {
                                Log.d("Status","onEnd");
                            }

                        }).start();

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：任意手机

* 出现问题的安卓版本【必填】：任意版本

## 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* 框架最新的版本是否存在这个问题【必答】：是）

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是）

* 这个问题是不是后台自己的问题导致的【必答】：否，虽然是下载文件，但是出错情况并不是返回一个文件

**Comment by getActivity** [comment]
小伙子，我先问你一个问题，如何判断一个下载链接是成功还是失败？判断的标准有哪些？

**Comment by Brislis** [comment]
根据你的成功回调，判断file是否为null

**Comment by Brislis** [comment]
就是说当我用EasyHttp.download这个方法，不管URL传入什么，只要接口是通的，就能执行到onComplete回调并下载一个file下来，这部分是否可以优化？

**Comment by getActivity** [comment]
@Brislis  关键是我怎么知道这部分流是不是文件？判断的依据是什么？

**Comment by AdminQQZ** [comment]
现在问题是接口有 Content-Type  字段，先处理了来吧，在考虑没有的情况。

**Comment by getActivity** [comment]
@AdminQQZ @Brislis 那怎么知道 `Content-Type = application/octet-stream` 就是下载文件？而 `Content-Type = application/json` 就不是下载文件？判断的依据是什么？行业有这一块的判断标准么？

**Comment by Brislis** [comment]
@getActivity responseBody能不能判断出来？

**Comment by Brislis** [comment]
MIME 类型
媒体类型（通常称为 Multipurpose Internet Mail Extensions 或 MIME 类型 ）是一种标准，用来表示文档、文件或字节流的性质和格式。它在IETF RFC 6838中进行了定义和标准化。

**Comment by getActivity** [comment]
> @getActivity responseBody能不能判断出来？

怎么通过 ResponseBody 判断？

**Comment by getActivity** [comment]
> MIME 类型 媒体类型（通常称为 Multipurpose Internet Mail Extensions 或 MIME 类型 ）是一种标准，用来表示文档、文件或字节流的性质和格式。它在IETF RFC 6838中进行了定义和标准化。

这个只是告诉你文件是什么类型？也没有说明哪些类型就是下载的，哪些类型就是不能下载的。

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
