### ISSUE TITLE
关于post请求不能用gson模式问题？

### ISSUE THREAD

**Issue by lsqbeyond** [getActivity/EasyHttp#13]
您好，我发现这个框架post请求只能用表单形式么，如果使用json形式就返回错误，我看了您的demo，启用gson模式后 @Override public BodyType getType() { // 参数以 Json 格式提交（默认是表单） return BodyType.JSON; }，就会报错，但是我们公司现在api必须要用gson形式的，请指教

**Comment by getActivity** [comment]
框架本身是支持以 Json 格式提交参数的，如果你们的接口报错，那么要告诉我具体的原因，是因为什么原因导致的，我才能去排查这个问题。但是经过其他人的使用反馈，是没有任何问题的。
