### ISSUE TITLE
下载较大的TXT文件会OOM

### ISSUE THREAD

**Issue by SSSSunrise** [getActivity/EasyHttp#131]
* 框架版本【必填】：10.8-11.2

* 问题描述【必填】：150M的文本文件下载无响应，隔一会报错OOM

* 复现步骤【必填】：
`*EasyHttp.download(viewLifecycleOwner)
            .method(HttpMethod.GET)
            .url(url)
            .file(cloudPath + fileName)
            .listener(object : OnDownloadListener {
                override fun onStart(file: File?) {
                    Log.i("下载", "开始=${file?.absolutePath}")
                    mAdapter?.getItem(index)?.download = 1
                    mAdapter?.notifyItemChanged(index)
                }

                override fun onProgress(file: File?, progress: Int) {
                    mAdapter?.getItem(index)?.progress = progress
                    mAdapter?.notifyItemChanged(index)
                }

                override fun onComplete(file: File?) {
                    LogUtils.i("下载完毕=${file?.absolutePath}")
                    com.blankj.utilcode.util.FileUtils.rename(file?.absolutePath, newFileName)//重命名文件
                    To.show(String.format(StringUtils.getString(R.string.file_download_completed), newFileName))
                    com.blankj.utilcode.util.FileUtils.notifySystemToScan(cloudPath + newFileName)
                    mAdapter?.notifyItemChanged(index)
                }

                override fun onError(file: File?, e: Exception?) {
                    com.blankj.utilcode.util.FileUtils.delete(file) //下载失败删除文件
                    //下载失败
                    "下载失败".logd()
                    e?.message?.loge()
                    To.error(StringUtils.getString(R.string.download_failed__please_try_again))
                }

                override fun onEnd(file: File?) {
                    mAdapter?.getItem(index)?.download = 0
                    mAdapter?.notifyItemChanged(index)
                }

            }).start()`

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：任意手机

* 出现问题的安卓版本【必填】：任意版本

## 请回答

* 是部分机型还是所有机型都会出现【必答】：所有机型

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

* 这个问题是不是后台自己的问题导致的【必答】：否
## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）
![image](https://user-images.githubusercontent.com/31717774/179727739-ea286d38-46d0-4e8f-9a7c-34eecbc9a5dd.png)

**Comment by getActivity** [comment]
小伙子，从 OOM 的异常来看，没有看到关于框架代码的堆栈，你怎么确定这个 OOM 就是框架导致的？判断的依据是什么？

**Comment by SSSSunrise** [comment]
不好意思，我仔细排查了一下发现是我的那个log拦截器里做了打印日志，他好像把txt写到buffer里打印了，才会oom
