### ISSUE TITLE
easy HTTP 如何初始化报错

### ISSUE THREAD

**Issue by lyqlc** [getActivity/EasyHttp#135]
## 问题描述      java.lang.IllegalStateException: You haven't initialized the configuration yet

* 框架版本【必填】：EasyHttp:11.2

* 问题描述【必填】：使用Easy 请求报错没有初始化配置文件

* 复现步骤【必填】：点击请求  EasyHttp.download(getDialog())
                .method(HttpMethod.GET)
                .file(apkFile)
                .url(downloadUrl)
                .md5(fileMd5)
                .listener(object : OnDownloadListener {
                    override fun onStart(file: File?) {
                        // 标记为下载中
                        downloading = true
                        // 标记成未下载完成
                        downloadComplete = false
                        // 后台更新
                        closeView?.visibility = View.GONE
                        // 显示进度条
                        progressView?.visibility = View.VISIBLE
                        updateView?.setText(R.string.update_status_start)
                    }

                    override fun onProgress(file: File, progress: Int) {
                        updateView?.text = String.format(getString(R.string.update_status_running)!!, progress)
                        progressView?.progress = progress
                        // 更新下载通知
                        notificationManager.notify(
                            notificationId, notificationBuilder
                                // 设置通知的文本
                                .setContentText(String.format(getString(R.string.update_status_running)!!, progress))
                                // 设置下载的进度
                                .setProgress(100, progress, false)
                                // 设置点击通知后是否自动消失
                                .setAutoCancel(false)
                                // 是否正在交互中
                                .setOngoing(true)
                                // 重新创建新的通知对象
                                .build()
                        )
                    }

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：夜神

* 出现问题的安卓版本【必填】：6 ，7

**Comment by getActivity** [comment]
<img width="942" alt="image" src="https://user-images.githubusercontent.com/28616817/184633757-24722400-6da3-4796-88c6-bffb0661e85a.png">
