### ISSUE TITLE
HTTPS证书怎么配置呢

### ISSUE THREAD

**Issue by 979881765** [getActivity/EasyHttp#136]
## 建议收集

* issue 是否有人曾提过类似的问题？【必答】（一旦出现重复提问我将不会再次解答）

* 你觉得框架有什么不足之处？【必答】（你可以描述框架有什么令你不满意的地方）

* 你觉得该怎么去完善会比较好？【非必答】（你可以提供一下自己的想法或者做法供作者参考）

**Comment by getActivity** [comment]
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/28616817/186064321-2736a5c0-aecc-4135-97e6-bae6d1f0e8ea.png">
