### ISSUE TITLE
请问easyhttp网络请求会被阻塞导致代码延迟执行吗？

### ISSUE THREAD

**Issue by ymwm-lxl** [getActivity/EasyHttp#137]
#### 问题描述

* 请描述一下你的疑惑【必填】：XXX（注意：如果是框架 bug 请不要在这里提，否则一概不受理）

我这里查看现场安卓终端设备日志，发现 EasyHttp.post(this).api(xxx).request()代码没有立即执行，http的拦截器日志在稍后几分钟才进行打印。感觉像是被阻塞了？也怀疑是硬件出了问题。已经让现场更换硬件了。

当用户点击按钮没反应的时候拔掉了网线，日志反映出就立马发起了请求，不过请求失败了。

还有一次是发起了请求后，拦截器打印了发起的日志，在之后十三分钟之后打印了返回的日志，查看服务器端日志是在前端接到返回内容的稍早一二百毫秒接到的请求。所以应该前端打印发起日志的时候网络请求并没实际开始执行。

#### 请回答

* issue 是否有人曾提过类似的问题？【必答】（一旦出现重复提问我将不会再次解答）
没有

* 框架文档是否有提及到此问题？【必答】：是/否（请先看完框架的文档后再来提建议）
否，只有延迟加载的方法，但是我没有调用那个方法。

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，具体原因如下：

* 这个问题属于 Bug，不属于疑问解答，请使用提交 bug 的 issue 模板来填写

请重新提一个 issue 并纠正以上问题

**Comment by ymwm-lxl** [comment]
我觉得这个应该是我用法的问题，因为我大致看了框架源码，没什么毛病

**Comment by getActivity** [comment]
<img width="813" alt="image" src="https://user-images.githubusercontent.com/28616817/191165152-9a8a1888-ee4b-48a7-8a73-941ef753ea4c.png">

<img width="763" alt="image" src="https://user-images.githubusercontent.com/28616817/191165261-6a5aaea1-d7dd-4445-bfcf-da8e1fcfd19e.png">

**Comment by getActivity** [comment]
[Android笔记之解决OkHttp解析dns超时时间无法设置的问题](https://blog.csdn.net/quwei3930921/article/details/85336552)

**Comment by ymwm-lxl** [comment]
相关链接：
https://www.cnblogs.com/fnlingnzb-learner/p/16018378.html
https://stackoverflow.com/questions/40793786/strange-connection-blocking-hanging-with-okhttpclient
