### ISSUE TITLE
在系统网络DNS不可用的情况下，因为DNS导致的请求延迟，拦截器中的日志打印也相对延迟

### ISSUE THREAD

**Issue by ymwm-lxl** [getActivity/EasyHttp#138]
#### 问题描述

* 框架版本【必填】：9.6

* 问题描述【必填】：

在测试 https://github.com/getActivity/EasyHttp/issues/137 的过程中，发现因为dns不可用，所以也没有执行到拦截器，导致记录的日志不准确，**请问是否有其他方案进行请求的日志记录**（因为观测到框架本身BodyRequest里的日志是执行了的）？

原因：因为在解析DNS，导致延迟后续执行，使得无法准确定位现场网络请求具体问题。

* 复现步骤【必填】：dns设置“81.17.66.14”，发起请求即可。（注意：目前不受理没有复现步骤的 Bug 单）

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：第三方终端 - 商米L2s

* 出现问题的安卓版本【必填】：9

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

* 这个问题是不是后台自己的问题导致的【必答】：否

#### 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by ymwm-lxl** [comment]
同样，也会导致没有走 onStart ，导致loading 也没有显示，造成页面没有反应的假象。

**Comment by getActivity** [comment]
<img width="926" alt="image" src="https://user-images.githubusercontent.com/28616817/191499371-f5bd5e06-2a69-46eb-9340-7e57499478ca.png">

**Comment by getActivity** [comment]
小伙子，请提供一下可供复现此问题的 Demo 工程上来。

**Comment by getActivity** [comment]
超过三天没有响应，自动关闭此 issue。
