### ISSUE TITLE
RequestHandler 为什么不直接放进框架里面?让用户再次实现一次,很费劲

### ISSUE THREAD

**Issue by zxyaust** [getActivity/EasyHttp#140]
#### 建议收集

* issue 是否有人曾提过类似的问题？【必答】无

* 框架文档是否有提及到此问题？【必答】：是

* 你觉得框架有什么不足之处？【必答】RequestHandler 实现的部分应该封装进去,开发者用框架希望是开箱即用,这么一大推的配置,自己实现那么多东西,缓存也要自己写,那为什么不用别的框架呢?反正都是自己写,retrofit那么出名,对吧

* 你觉得该怎么去完善会比较好？希望能开箱即用.简单配置后就能使用,甚至是所有的东西应该有默认配置,开发者不需要做任何工作就能用,只有一些特殊需求,让用户根据文档自己配置即可

**Comment by getActivity** [comment]
小伙子，你可以尝试把 RequestHandler 的代码塞到框架中，你自己试一下就能知道我为什么不那么做了。

**Comment by zxyaust** [comment]
好的吧，我个人觉得应该给一套可以直接使用的方式，让需要自定义的人自己去实现一些特殊操作，感谢奉献



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月4日(周二) 中午11:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [getActivity/EasyHttp] RequestHandler 为什么不直接放进框架里面?让用户再次实现一次,很费劲 (Issue #140)




 
小伙子，你可以尝试把 RequestHandler 的代码塞到框架中，你自己试一下就能知道我为什么不那么做了。
