### ISSUE TITLE
Github访问的太费劲了，请问作者有没有邮箱，我可以不初始化那么多的属性吗，此库可以用在生产环境吗

### ISSUE THREAD

**Issue by HeVTion** [getActivity/EasyHttp#142]
#### 问题描述

* 请描述一下你的疑惑【必填】：Github访问的太费劲了，请问作者有没有邮箱，我可以不初始化那么多的属性吗，此库可以用在生产环境吗
#### 请回答

* issue 是否有人曾提过类似的问题？【必答】（否）

* 框架文档是否有提及到此问题？【必答】：是/否（否）

**Comment by getActivity** [comment]
1. Github访问的太费劲，你选择翻墙

**Comment by HeVTion** [comment]
轮子老师，我已经很科学上网了，建议轮子哥，把出一套英文注释的，因为上google市场你懂的，我要把这个库用在生产环境了，不懂的地方还请老师多多指教

**Comment by HeVTion** [comment]
请问老师，此库更新频繁吗？ 我想下载源码，固定一个版本使用

**Comment by getActivity** [comment]
小伙子，我个人不建议你使用本地依赖，因为你使用了本地依赖，那么你将会丧失以下权益：

1. 后续将无法即时更新，迎接你的是麻烦的替换和测试。
2. 后续出现框架任何 Bug 只能由你自己排查和处理，因为我不会基于你本地 fork 的版本进行单独维护，无论你有没有修改这里面的源码，你如果进行了本地依赖，我就认定这是你自己个人维护的版本，如果是一百个人这样做，我就得维护一百个版本， 我没有那么多时间和精力，作者只会维护 Github 这一个版本。

**Comment by getActivity** [comment]
超过三天没有响应，自动关闭此 issue。
