### ISSUE TITLE
希望作者优化一下

### ISSUE THREAD

**Issue by HeVTion** [getActivity/EasyHttp#143]
#### 问题描述

* 请描述一下你的疑惑【必填】：如题，希望作者把请求简化一下，比如EasyHttp.addhead.addParams.addtimeout.addretry.isLifeycle....
而不是在初始化的时候配置一大堆东西，这些东西应该有他的默认值

我已经找到处理方案，就是在拦截器里写，效果其实也一样，只不过要自己封装一层。
假设我使用activity+fragment的情况，我可以直接传入 activity作为LifecycleOwner对象吗？

#### 请回答

* issue 是否有人曾提过类似的问题？【必答】否（一旦出现重复提问我将不会再次解答）

* 框架文档是否有提及到此问题？【必答】：否（请先看完框架的文档后再来提建议）

**Comment by getActivity** [comment]
小伙子，我来回答你提的两个问题

* 希望作者把请求简化一下，而不是在初始化的时候配置一大堆东西，这些东西应该有他的默认值

> 关于这个问题我在之前 [EasyHttp/issues/142](https://github.com/getActivity/EasyHttp/issues/142) 已经回答过了你，不要重复提问，网络请求框架很多东西都需要定制化的，有些东西可以不设置也没有问题（setRetryCount、setRetryTime、addParam、addHeader、setInterceptor），有些东西必须设置（setServer、setHandler）才能使用，你要是觉得这样的代码设计不合理，也可以根据自己的需求来改。

* 假设我使用activity+fragment的情况，我可以直接传入 activity作为LifecycleOwner对象吗？

> 如果网络请求是在 Activity 请求的，那么请用 Activity 作为 LifecycleOwner 传入，如果网络请求是在 Fragment 请求的，那么请用 Fragment 作为 LifecycleOwner 传入，不要搞错了，Activity 和 Fragment 生命周期是不一样的。

**Comment by getActivity** [comment]
超过三天没有响应，自动关闭此 issue。
