### ISSUE TITLE
系统崩溃后EasyHttp不能发起网络提交

### ISSUE THREAD

**Issue by longcaiyinyuan** [getActivity/EasyHttp#147]
#### 问题描述

* 框架版本【必填】：v11.2   v10.2

* 问题描述【必填】：系统崩溃后EasyHttp不能发起网络提交

* 复现步骤【必填】：在CrashHandler全局异常类里uncaughtException方法中崩溃发生后用EasyHttp请求网络接口提交错误信息，EasyHttp没有请求成功。

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：Redmi k30  Android 12
*  还有一个第三方公司制作的平板  Android 7  没有具体的品牌
<img width="366" alt="weixin3" src="https://user-images.githubusercontent.com/44362109/206607962-4057a8d6-1850-4d5b-bd4e-739ac7255c9e.png">

![weixin2](https://user-images.githubusercontent.com/44362109/206607697-df7aaa00-7c0f-4f6e-8020-445c70c2fe85.jpeg)

* 出现问题的安卓版本【必填】：Android 12    Android 7

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

* 这个问题是不是后台自己的问题导致的【必答】：否。用okhttp原始的post写法请求可以提交上去。

#### 其他

* 提供报错堆栈 没有报错信息

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案

**Comment by getActivity** [comment]
小伙子，我这边验证了确实有这个问题，我使用的是抓包的方式进行验证，我用小米 12（Android 12）的机子测试，却看到 OkHttp 的请求有发送出去，而 EasyHttp 并没有发送出去，但是我换成 vivo iQOO 9 Pro（Android 12）的机子测试，在抓包的时候并没有抓到对应的请求，但是有一点和你有出入，无论是用 EasyHttp 还是用 OkHttp，都没有看到有请求发送出去，以下代码是崩溃时所作的操作：

<img width="907" alt="image" src="https://user-images.githubusercontent.com/28616817/206841664-acab4dd4-2a65-43e9-abbe-f7e768c84bf5.png">

* 问题点1：为什么用 EasyHttp 不行但是用 OkHttp 可以呢？

> 这是因为我在 OkHttp 的操作上面加了 `new Handler(Looper.getMainLooper()).post` 执行，通过抓包看也是发送不出去，所以造成 EasyHttp 发送不出去的原因是我在 request 方法中加了 post 操作，我现在优化了一下这个问题，你可以下载的版本试试看。

[EasyHttp-11.5.aar.zip](https://github.com/getActivity/EasyHttp/files/10199579/EasyHttp-11.5.aar.zip)

* 问题点2：我该如何解决这一问题？

> 关于崩溃信息是否能立即上报给后台，由于不同的厂商做了不同程度上的处理，vivo 的机子上面表现是，只要触发崩溃，进程就会立马被杀死，任何耗时操作都会立马失效，而在小米的机子上面，触发了崩溃也不会杀死进程（除非自己手动杀死进程），虽然进程没有被杀，但是我猜测进程已经处于名存实亡的状态，但是死亡的速度可能要比 vivo 的速度稍微慢一点，所以 OkHttp 的请求才能侥幸跑出去，但是有一点是确定的，如果在 `UncaughtExceptionHandler.uncaughtException` 方法最后面加上杀死进程的代码，将会导致任何请求发送不出去。

> 上面是对问题的分析，个人的建议是，不要在崩溃的时候请求网络，因为那个应用生命周期的最后一刻，你的操作不一定能生效，你如果有上报崩溃信息的需要，可以考虑先保存到本地，下次应用启动的时候再进行上报。

**Comment by longcaiyinyuan** [comment]
11.5新版已经没问题了。
确实在崩溃的时候记录日志保存本地，重启的时候再进行上报比较好。
感谢轮子哥~
