### ISSUE TITLE
无法再Worker中运行

### ISSUE THREAD

**Issue by sckalman123** [getActivity/EasyHttp#151]
#### 问题描述
无法在Worker中运行 ， 报错信息  failed because it threw an exception/error
                                                                                                    java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Method addObserver must be called on the main thread

源代码文件source 

public class DataWorker extends Worker implements OnHttpListener{

    private static final String PROGRESS = "PROGRESS";

    private Context mContext;

    public DataWorker(
            @NonNull Context context,
            @NonNull WorkerParameters parameters) {
        super(context, parameters);
        // Set initial progress to 0
        setProgressAsync(new Data.Builder().putInt(PROGRESS, 0).build());
        Log.i("xlog","DataWorker   构造函数" );
        mContext = context;
    }

    @NonNull
    @Override
    public Result doWork() {
        XLog.i("DataWorker do work start " );
        setProgressAsync(new Data.Builder().putInt(PROGRESS, 100).build());

        registerDev();

        return Result.success();
    }

    private void registerDev(){
        PostRequest postRequest = EasyHttp.post(new LifecycleAppFragment());
        postRequest.api(new RegisterDev().setDevSN(PhoneUtils.getDeviceSN(),"2Trash"));

        postRequest.request(new HttpCallback<HttpData<RegisterDev.VersionBean>>(this) {

            @Override
            public void onSucceed(HttpData<RegisterDev.VersionBean> result) {
                XLog.i("DataWorker onSucceed " + result);
            }
        });

    }

    @Override
    public void onSucceed(Object o) {
        XLog.i("DataWorker onSucceed ");
    }

    @Override
    public void onFail(Exception e) {
        XLog.i("DataWorker Exception "+e.toString() );
    }

请回答
issue 是否有人曾提过类似的问题？【必答】无
框架文档是否有提及到此问题？【必答】：无

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题

请重新提一个 issue 并纠正以上问题
