### ISSUE TITLE
请求头是汉字会闪退

### ISSUE THREAD

**Issue by WangkeqiangS** [getActivity/EasyHttp#154]
#### 问题描述

* 框架版本【必填】：10.2版本

* 问题描述【必填】：网络请求时，请求头设置为汉字会报错

* 复现步骤【必填】：调用接口，加个请求头，设置为汉字，即可复现

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：华为 mate 20

* 出现问题的安卓版本【必填】：10

* 问题信息的来源渠道【必填】：自己遇到的

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* 框架最新的版本是否存在这个问题【必答】：否

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

* 这个问题是不是后台自己的问题导致的【必答】：否

#### 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
<img width="367" alt="image" src="https://user-images.githubusercontent.com/28616817/211560808-eb15a9cb-3b2f-4516-8403-94f77c840717.png">

小伙子，你试过了框架最新版本不会，直接升级一下框架版本不就 OK 了？难不成要我给你的版本单独修复一次？

**Comment by WangkeqiangS** [comment]
好的 明白了 谢谢轮子哥
