### ISSUE TITLE
请问在下载文件的请求中，可不可以添加参数

### ISSUE THREAD

**Issue by ZhangOldTwo** [getActivity/EasyHttp#155]
## 【警告：请务必按照 issue 模板填写，不要抱有侥幸心理，一旦发现 issue 没有按照模板认真填写，一律直接关闭】

问题描述
我需要在下载文件时，传入筛选条件，但是目前在api中set相关参数以后发起请求，并没有对应的参数，想请问怎么在发起下载操作请求的同时，传入参数？

请回答
issue 是否有人曾提过类似的问题？【必答】否

框架文档是否有提及到此问题？【必答】否

**Comment by ZhangOldTwo** [comment]
![微信截图_20230202085227](https://user-images.githubusercontent.com/20178641/216204309-80c1094e-d75b-4f7a-804a-5b0b822bb6b0.png)
发现在下载时添加参数是个空方法

**Comment by getActivity** [comment]
此问题已经通过 QQ 私下处理完毕，更新到最新版本即可。

**Comment by RXlung** [comment]
有相关示例吗

**Comment by getActivity** [comment]
@RXlung 发起下载请求的时候不要传入 url，而是直接传入 api 对象，这样就可以携带请求参数。
