### ISSUE TITLE
延时请求无法取消

### ISSUE THREAD

**Issue by nwhhades** [getActivity/EasyHttp#159]
#### 问题描述

* 框架版本【必填】：11.6

* 问题描述【必填】：延时请求无法取消

* 复现步骤【必填】：

//延时请求
EasyHttp.get(this)
                .delay(5000)
                .tag("get")
                .request();

//取消
EasyHttp.cancel("get");

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：MuMu模拟器

* 出现问题的安卓版本【必填】：6
* 
* 问题信息的来源渠道【必填】：自己遇到的

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

* 这个问题是不是后台自己的问题导致的【必答】：是

#### 其他

bug原因 

取消请求的时候，没有考虑 EasyUtils.HANDLER.removeCallbacks 取消掉延时请求的runnable

解决需要思考

要怎么保存tag和Runnable的关系？ 

延时请求没有设置tag的情况呢？

**Comment by getActivity** [comment]
[EasyHttp-11.8.aar.zip](https://github.com/getActivity/EasyHttp/files/10832698/EasyHttp-11.8.aar.zip)

**Comment by getActivity** [comment]
小伙子，问题修复了，你下载上面的包试试看。

**Comment by nwhhades** [comment]
不设置TAG时，还是没有移除请求任务
bug原因参考下文
https://zhumulangma.blog.csdn.net/article/details/124964655

**Comment by nwhhades** [comment]
sdk 19 下  .setTag("get"+this)   可以直接复现

**Comment by getActivity** [comment]
[Uploading EasyHttp-11.8.aar.zip…]()

**Comment by nwhhades** [comment]
额 还是一样的 无法取消请求
看原因是MessageQueue.removeCallbacksAndMessages中使用了 == 来判断 token是否相等
而String用 == 判断会产生值相等却返回false的情况，导致没有移除任务

**Comment by nwhhades** [comment]
测试环境为Android 4.4

**Comment by getActivity** [comment]
[EasyHttp-11.8.aar.zip](https://github.com/getActivity/EasyHttp/files/10850715/EasyHttp-11.8.aar.zip)

**Comment by getActivity** [comment]
小伙子，问题修复了，再试一下。

**Comment by getActivity** [comment]
这次我换成了 what 来实现移除延迟消息

**Comment by nwhhades** [comment]
测试过了 问题解决   感谢！

**Comment by nwhhades** [comment]
关闭issues
