### ISSUE TITLE
建议：是否可以添加可以选择性不上传某个字段。即便是设置了@HttpRename

### ISSUE THREAD

**Issue by Xiao1209** [getActivity/EasyHttp#16]
项目中会有这样的一种需求。某些字段在某些情况下会参与请求，某些情况下会参与请求。
如：
```java
@HttpRename("param1")
String param1;

@HttpRename("param2)
String param2;
```

在场景A中需要仅请求 `param1` 参数
在场景B中需要仅请求 `param2` 参数
在场景C中需要两个参数同时请求。
如果按照现在的注解方案，需要写三份Java代码，针对于一个请求url。

请问有对于这种使用状况的一种改善方案吗？

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/98315554-67a0f000-2013-11eb-9196-14775ce50112.png)

**Comment by getActivity** [comment]
* 字段作为请求参数的衡量标准

	* 假设某个字段的属性值为空，那么这个字段将不会作为请求参数发送给后台
	
	* 假设果某个字段类型是 String，属性值是空字符串，那么这个字段就会作为请求参数，如果是空对象则不会
	
	* 假设某个字段类型是 int，因为基本数据类型没有空值，所以这个字段一定会作为请求参数，但是可以换成 Integer 对象来避免，因为 Integer 的默认值是 null

**Comment by getActivity** [comment]
你如果不想传 xxx 参数到后台，请把这个对象设置为 null，又或者不赋值
