### ISSUE TITLE
请求失败后 会将失败的msg弹出来 请问轮子哥怎么关闭呢 因为有的接口不需要弹出来 

### ISSUE THREAD

**Issue by 756230883** [getActivity/EasyHttp#160]
#### 问题描述

* 请描述一下你的疑惑【必填】：XXX（注意：如果是框架 bug 请不要在这里提，否则一概不受理）

#### 请回答

* issue 是否有人曾提过类似的问题？【必答】没有

* 框架文档是否有提及到此问题？【必答】：否

**Comment by 756230883** [comment]
![1679043424575](https://user-images.githubusercontent.com/9440937/225858707-b54a4010-2c1b-4857-8d21-111f98a20397.jpg)
因为不是我规定成功的code值  走到了这里 弹出了服务器返回的msg信息

**Comment by getActivity** [comment]
小伙子，框架内部实现不会主动弹提示给外层，至于弹提示的原因，很可能是你们在 BaseActivity onFail 方法里面弹的，但是也有可能不是，因为 Demo 这样写的，不清楚你们会怎么写

**Comment by 756230883** [comment]
谢谢轮子哥的提示 我用的您的快速开发框架 在AppActivity 基类中找到了提示的地方  谢谢轮子哥
