### ISSUE TITLE
post 提交的问题

### ISSUE THREAD

**Issue by liuhuicheng** [getActivity/EasyHttp#161]
#### 问题描述

post提交，当参数为list的时候 我看内部是把list转化为JsonArray对象，我这边是需要拦截提交的参数加密，list的时候没有问题，当JsonArray对象时候和list的加密结果不一样，想问下有什么解决的办法。

```java
@Override
public void interceptArguments(@NonNull HttpRequest<?> httpRequest, @NonNull HttpParams params, @NonNull HttpHeaders headers) {
    HashMap<String, Object> mParams = params.getParams();
    LogUtils.e(mParams.toString());
  
    String encrypt = AESUtil.encrypt(new Gson().toJson(mParams));
    params.clear();
    params.put("data", encrypt);
}
```
#### 请回答

* issue 是否有人曾提过类似的问题？【必答】（没有）

* 框架文档是否有提及到此问题？【必答】：是/否（否）

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题

请重新提一个 issue 并纠正以上问题

**Comment by getActivity** [comment]
小伙子，我看了好几遍你的描述，还是没有听懂你在说什么？

**Comment by liuhuicheng** [comment]
有没有办法做到 post提交 list参数 不去转化为JsonArray对象

**Comment by liuhuicheng** [comment]
好的 谢谢！

**Comment by SomnusWu** [comment]
就是这个问题，JSONArray转为Json会有values字段，感谢 [GsonFactory](https://github.com/getActivity/GsonFactory) 能解决这个问题。
