### ISSUE TITLE
POST 请求数组类型参数时转换错误

### ISSUE THREAD

**Issue by octopusYan** [getActivity/EasyHttp#164]
#### 问题描述

* 框架版本【必填】：11.6

* 问题描述【必填】：POST 请求数组类型参数时会转换为空对象
![image](https://user-images.githubusercontent.com/70868034/228303681-3c9eca94-0a13-4c0a-b4a2-1fc4378b7f1c.png)
![image](https://user-images.githubusercontent.com/70868034/228303585-99a050f4-6aee-4c78-a4d7-89cba6b2d237.png)

* 复现步骤【必填】：创建如下接口对象并请求
![image](https://user-images.githubusercontent.com/70868034/228302601-7c2228e8-87d5-461f-83e0-2412c81880b6.png)

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：win11 WSA / 小米8探索版

* 出现问题的安卓版本【必填】：10

* 问题信息的来源渠道【必填】：自己遇到的

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

* 这个问题是不是后台自己的问题导致的【必答】：否

**Comment by getActivity** [comment]
[EasyHttp-11.8.aar.zip](https://github.com/getActivity/EasyHttp/files/11095932/EasyHttp-11.8.aar.zip)

**Comment by getActivity** [comment]
小伙子，问题修复了，你用上面这个包试试看。

**Comment by octopusYan** [comment]
> 小伙子，问题修复了，你用上面这个包试试看。

好的。测试过了，可以。
![image](https://user-images.githubusercontent.com/70868034/228422877-01c9282d-8859-4cd1-bd3d-c38a9bd95d27.png)
