### ISSUE TITLE
在dialog或者popupwindow里面使用

### ISSUE THREAD

**Issue by fuchengxin** [getActivity/EasyHttp#165]
#### 问题描述

* 请描述一下你的疑惑【必填】：如果在dialog或者popupwindow里面使用网络请求，不想关联activity或者fragment的生命周期，只关联自身的dismiss()，是否需要手动add与cancel  tag

#### 请回答

* issue 是否有人曾提过类似的问题？【必答】否

* 框架文档是否有提及到此问题？【必答】：否

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
