### ISSUE TITLE
OnDownloadListener 接口中大部分方法可以都改为 default 吗？有些方法某些场景可能是不需要进行实现的

### ISSUE THREAD

**Issue by Heart-Beats** [getActivity/EasyHttp#166]
#### 建议收集

* issue 是否有人曾提过类似的问题？【必答】否

* 框架文档是否有提及到此问题？【必答】：否

* 你觉得框架有什么不足之处？【必答】如标题所述，使用时需要实现的方法太多了，OnHttpListener 也有此问题

* 你觉得该怎么去完善会比较好？【非必答】将大部分方法改为默认实现，比如下载中需要实现进度变化和下载完成，这两个比较常用，其他的使用者自己按需实现

**Comment by getActivity** [comment]
小伙子，你用的框架版本是多少，另外你具体是指哪些方法不需要实现？具体的理由是什么？

**Comment by Heart-Beats** [comment]
版本就是最新的 11.8 呀，就比如下面的这种类似场景：
![image](https://user-images.githubusercontent.com/33248551/230807569-214903ee-50b7-4930-8fdb-1c5551b47851.png)

其实我只关心下载完成，出错啥的没有重试机制，只是打印日志

**Comment by getActivity** [comment]
那我可以理解成你想要 onStart 和 onEnd 方法默认实现对吧？

**Comment by getActivity** [comment]
建议已经采纳，会在下个版本优化，多谢小伙子的建议。
