### ISSUE TITLE
当使用JSON提交数据的时候，全局参数不起作用

### ISSUE THREAD

**Issue by w1984908499** [getActivity/EasyHttp#167]
* 框架版本【必填】：11.8

* 问题描述【必填】：当使用JSON提交数据的时候，全局参数不起作用

* 复现步骤【必填】：必现

* 是否必现【必填】：是

* 项目 targetSdkVersion【必填】：31

* 出现问题的手机信息【必填】：所有

* 出现问题的安卓版本【必填】：所有

* 问题信息的来源渠道【必填】：自己遇到的

* 提供解决方案（如果已经解决了的话，此项不强制）
* 可以通过OKHttp的拦截器实现添加JSON全局参数

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 这个问题属于建议，不能提 bug issue 单，请提建议 issue 单

请重新提一个 issue 并纠正以上问题
