### ISSUE TITLE
服务器希望我在没有文件的时候依然使用multipart/form-data

### ISSUE THREAD

**Issue by q475762313** [getActivity/EasyHttp#168]
#### 建议收集

* issue 是否有人曾提过类似的问题？【必答】否

* 框架文档是否有提及到此问题？【必答】：否

* 你觉得框架有什么不足之处？【必答】OKGO中支持.isMultipart(true)一键直接转换成multipart/form-data，这里似乎没有更好的办法

* 你觉得该怎么去完善会比较好？【非必答】虽然我知道EasyHttp支持bodyRequest，但是还需要更多的操作，比如更改请求头，content_type Accept等，但是我觉得不够优雅

**Comment by q475762313** [comment]
我在BaseRequest中加了一个 
private boolean isMultipart = false;
并且判断params是否添加setMultipart值完美解决了我的问题
还是希望您能加一个，这耗费不了您5分钟时间！
![1681111565277](https://user-images.githubusercontent.com/35600294/230850296-3d89c86f-62aa-40e7-a6b5-525be23c45f5.jpg)

**Comment by q475762313** [comment]
针对所有post请求的接口，很不幸……

**Comment by q475762313** [comment]
> 小伙子，你这个是针对某一个接口还是所有接口？

轮子哥，我已付茶费请您喝茶，还是希望您的这个框架能支持这个需求，嘿嘿

**Comment by getActivity** [comment]
小伙子，你的打赏我收到了，感谢小伙子的支持！

**Comment by getActivity** [comment]
> 我在BaseRequest中加了一个 private boolean isMultipart = false; 并且判断params是否添加setMultipart值完美解决了我的问题 还是希望您能加一个，这耗费不了您5分钟时间！ ![1681111565277](https://user-images.githubusercontent.com/35600294/230850296-3d89c86f-62aa-40e7-a6b5-525be23c45f5.jpg)

小伙子，我不建议你这么做，你这样会强制使用 MultipartBody，但是你并不知道 MultipartBody 在没有参数的情况下会抛出异常，虽然框架做了处理，捕获了这个异常并换成 FormBody 来实现，这将意味着你这样改，并不能保证所有 post 请求的 `Content-Type` 都一定是 `multipart/form-data` 类型的。

**Comment by getActivity** [comment]
> 轮子哥，我已付茶费请您喝茶，还是希望您的这个框架能支持这个需求，嘿嘿

首先非常感谢你对我的喜欢和支持，但是我综合评估下来，可能在未来的框架版本仍然不会支持它，具体的原因如下：

1. MultipartBody 是请求体中包含多种流才需要使用，而一般情况下 post 默认请求应该是 FormBody，正常情况下不应该使用 MultipartBody。
2. 可能你给的理由没有太大的说服力，你只是认为自己需要这个接口，所以希望作者加上，但是对于其他人来讲这个接口就显得很怪异，其他人看到这个接口可能需要比较大的理解成本，或许这个需求本身比较特殊，不应该由框架层来实现，因为框架每做一次改变，都要考虑到大家的利益和感受，而不能只考虑某个人的需求或者利益。

**Comment by q475762313** [comment]
> > 轮子哥，我已付茶费请您喝茶，还是希望您的这个框架能支持这个需求，嘿嘿
> 
> 首先非常感谢你对我的喜欢和支持，但是我综合评估下来，可能在未来的框架版本仍然不会支持它，具体的原因如下：
> 
> 1. MultipartBody 是请求体中包含多种流才需要使用，而一般情况下 post 默认请求应该是 FormBody，正常情况下不应该使用 MultipartBody。
> 2. 可能你给的理由没有太大的说服力，你只是认为自己需要这个接口，所以希望作者加上，但是对于其他人来讲这个接口就显得很怪异，其他人看到这个接口可能需要比较大的理解成本，或许这个需求本身比较特殊，不应该由框架层来实现，因为框架每做一次改变，都要考虑到大家的利益和感受，而不能只考虑某个人的需求或者利益。

好的，明白，感谢轮子哥

**Comment by getActivity** [comment]
但是你的需求还是有其他办法可以实现的，但是要分两种情况，如果你是在某个接口上使用，可以考虑在 api 类中加入

```java
public final class SearchBlogsApi implements IRequestApi {

    @HttpHeader
    @HttpRename("Content-Type")
    private String contentType = "multipart/form-data";
}
```

* 需要额外注意的是，这个是框架 11.5 的版本加上的，如果你的框架不是这个版本及以上的，需要先进行升级

* 另外你如果要全局生效，可以考虑添加一个 OkHttp 拦截器，在拦截器判断 RequestBody 是不是 FormBody ，如果是的话，可以用 new 一个 CustomTypeBody（框架自带的类），在构造函数中传入刚刚获取到的 FormBody 对象，然后调用 CustomTypeBody 的 `setContentType("multipart/form-data")` 方法，表示强制修改它的 `Content-Type`，最后将 CustomTypeBody 作为新的 RequestBody 设置回去。
