### ISSUE TITLE
关于easyhttp使用后端event-stream的数据接收的问题

### ISSUE THREAD

**Issue by ALEXLEOHY** [getActivity/EasyHttp#169]
#### 最近gpt大火，公司开始介入相关项目，在做聊天的过程中，使用了event-stream完成了类似gpt可以单个字输出的功能，然后要求前端实现此功能

* 请描述一下你的疑惑【必填】：看了一下okhttp有sse的相关功能，请问使用easyhttp如何对请求的event-stream回复数据进行接收

#### 请回答

* issue 是否有人曾提过类似的问题？暂时没有

* 框架文档是否有提及到此问题？暂时没有

**Comment by getActivity** [comment]
https://blog.csdn.net/u011767319/article/details/124841088

**Comment by getActivity** [comment]
小伙子，关于你说的 sse 功能，我在网上查阅了相关资料，确实 OkHttp 有这个东西，但是我经过再三思考，决定不去该功能，具体原因如下：

1. 目前用这个功能的人比较少，你是第一个提这个功能的人
2. 封装这个功能的成本较高，可能需要对框架做比较大的改动

**Comment by ALEXLEOHY** [comment]
多谢轮子哥，目前确实用okhttp来实现，但是能力有限， 么办法接入到easyhttp中，所以向您来请教，多谢.
