### ISSUE TITLE
post提交Json(raw Content-Type:application/json)数据时,服务器解析失败

### ISSUE THREAD

**Issue by geekergeeker** [getActivity/EasyHttp#17]
实际请求中,header自动设置Transfer-Encoding chunked,而不是Content-Length,这种情况,后端不兼容
具体逻辑在okhttp的类BridgeInterceptor中

解决办法:JsonObjectBody中覆写contentLength()方法返回json长度

**Comment by getActivity** [comment]
我已通过 QQ 沟通并处理了该问题，这个问题会在下个版本修复完成。
