### ISSUE TITLE
轮子哥你好 使用中发现如果 接口返回 “”  啥也没返回的时候 也会认定为成功

### ISSUE THREAD

**Issue by 756230883** [getActivity/EasyHttp#171]
#### 建议收集

* issue 是否有人曾提过类似的问题？【必答】（没有

* 框架文档是否有提及到此问题？【必答】：否

* 你觉得框架有什么不足之处？【必答】  使用中发现如果 接口返回 “”  啥也没返回的时候 也会认定为成功

* 你觉得该怎么去完善会比较好？【非必答】建议可以在RequestHandler中拦截一下空的返回值

**Comment by 756230883** [comment]
因为如果不拦截  在onSucceed中直接操作 返回的data会报错 因为返回的data是空的

**Comment by getActivity** [comment]
<img width="875" alt="image" src="https://user-images.githubusercontent.com/28616817/233538952-d8cb89e1-f036-467b-ac9d-410154510901.png">

**Comment by getActivity** [comment]
小伙子，建议已经采纳，这块我已经补充到代码注释中了

**Comment by 756230883** [comment]
![1682057636233](https://user-images.githubusercontent.com/9440937/233555049-7a11ec90-5f49-4a6f-bb6d-acb0ab7d01d6.jpg)
轮子哥我这样处理下  您看可以吗  这样就走不到 onSucceed 了

**Comment by getActivity** [comment]
那要是后台返回的不是空字符串，而是有数据的，但是唯独没有那个结果码，你这种情况还适用么？

**Comment by 756230883** [comment]
也是哦  还是会有问题 不过我们后台约定的返回码  0就是成功  非0就是失败  除了异常情况会是  “”  正常情况就是 0 或者 非0  还是感谢轮子哥的回复
