### ISSUE TITLE
Android9和Android10  使用app专有目录下载文件，下载方法没有任何反应

### ISSUE THREAD

**Issue by MrBangBangBang** [getActivity/EasyHttp#176]
#### 问题描述

* 请描述一下你的疑惑【必填】：
   Android 9 和Android 10的设备，使用下载功能，按照demo上的写法，使用app的专有目录进行下载
` fun dowload(){
        val file = File(getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS), "sampleInfo_template.xlsx")
        LogUtils.i(file.absolutePath)
        EasyHttp.download(this)
            .method(HttpMethod.GET)
            .file(file)
            .url("http://192.168.2.6:8080/sample/upload/gcpExcelExample/sampleInfo_template.xlsx")
            .listener(object : OnDownloadListener {
                override fun onStart(file: File?) {
                    LogUtils.i("开始")
                }

                override fun onProgress(file: File?, progress: Int) {
                    LogUtils.i("进度 $progress")
                }

                override fun onComplete(file: File?) {
                    LogUtils.i("结束 ${file?.absoluteFile}")
                }

                override fun onError(file: File?, e: java.lang.Exception?) {
                    LogUtils.i("错误： ${e?.message}")
                }

                override fun onEnd(file: File?) {
                    LogUtils.i("onEnd ${file?.absoluteFile}")
                }
            })
    }`
 
上面的相关代码，方法执行了，但是没有任何日志信息，所有回调方法都没有走，也没有任何崩溃和错误信息，就是什么反应都没有，不知道应该怎么排查问题，还请解答，谢谢

#### 请回答

* issue 是否有人曾提过类似的问题？【必答】 没有

* 框架文档是否有提及到此问题？【必答】：有提到安卓10的分区储存问题，但是用app专有目录可以直接使用new File()，所以我是按照专有目录的形式去下载的。

**Comment by MrBangBangBang** [comment]
。。。 用的是`` 这个代码格式编写的，不知道为什么发布之后，格式成这样了。。。

**Comment by MrBangBangBang** [comment]
我从新上传下代码试试看

`val file = File(getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS), "sampleInfo_template.xlsx")
        LogUtils.i(file.absolutePath)
        EasyHttp.download(this)
            .method(HttpMethod.GET)
            .file(file)
            .url("http://192.168.2.6:8080/sample/upload/gcpExcelExample/sampleInfo_template.xlsx")
            .listener(object : OnDownloadListener {
                override fun onStart(file: File?) {
                    LogUtils.i("开始")
                }

                override fun onProgress(file: File?, progress: Int) {
                    LogUtils.i("进度 $progress")
                }

                override fun onComplete(file: File?) {
                    LogUtils.i("结束 ${file?.absoluteFile}")
                }

                override fun onError(file: File?, e: java.lang.Exception?) {
                    LogUtils.i("错误： ${e?.message}")
                }

                override fun onEnd(file: File?) {
                    LogUtils.i("onEnd ${file?.absoluteFile}")
                }
            })`

**Comment by MrBangBangBang** [comment]
`
val file = File(getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS), "sampleInfo_template.xlsx")
        LogUtils.i(file.absolutePath)
        EasyHttp.download(this)
            .method(HttpMethod.GET)
            .file(file)
            .url("http://192.168.2.6:8080/sample/upload/gcpExcelExample/sampleInfo_template.xlsx")
            .listener(object : OnDownloadListener {
                override fun onStart(file: File?) {
                    LogUtils.i("开始")
                }

                override fun onProgress(file: File?, progress: Int) {
                    LogUtils.i("进度 $progress")
                }

                override fun onComplete(file: File?) {
                    LogUtils.i("结束 ${file?.absoluteFile}")
                }

                override fun onError(file: File?, e: java.lang.Exception?) {
                    LogUtils.i("错误： ${e?.message}")
                }

                override fun onEnd(file: File?) {
                    LogUtils.i("onEnd ${file?.absoluteFile}")
                }
            })
`

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 这个问题属于 bug，不能提疑问 issue 单，请提 bug issue 单

请重新提一个 issue 并纠正以上问题

**Comment by MrBangBangBang** [comment]
大佬 问题解决了，我文档看的不够仔细，随后我通过认真对比demo中的每一行代码，发现我最后忘记写.start()了，尴尬了。。。  抱歉
