### ISSUE TITLE
框架返回内容不对 返回ok

### ISSUE THREAD

**Issue by javalove6688** [getActivity/EasyHttp#178]
#### 框架返回内容不对 返回ok

* 请描述一下你的疑惑【必填】：XXX（注意：如果是框架 bug 请不要在这里提，否则一概不受理）

#### 框架返回内容不对 返回ok了 而不是实际的json数据

* issue 是否有人曾提过类似的问题？【必答】（否）

* 框架文档是否有提及到此问题？【必答】：是/否（否）

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 这个问题属于 bug，请按照 bug issue 模板填写，而不能用疑问 issue 模板填写

请重新提一个 issue 并纠正以上问题
