### ISSUE TITLE
请求结果返回ok

### ISSUE THREAD

**Issue by javalove6688** [getActivity/EasyHttp#179]
#### 请求结果返回ok

* 框架版本【必填】：11.6

* 问题描述【必填】：返回ok

* 复现步骤【必填】：
 EasyHttp.get(this)
                .api(“xxx/api.json”)
                .request(new HttpCallback(new OnHttpListener<String>() {
                    @Override
                    public void onSucceed(String response) {

response返回的ok

* 是否必现【必填】：是

* 项目 targetSdkVersion【必填】：28

* 出现问题的手机信息【必填】：红米k60

* 出现问题的安卓版本【必填】：13

* 问题信息的来源渠道【必填】：自己遇到

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：全部
* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是
* 这个问题是不是后台自己的问题导致的【必答】：否（

#### 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，请上传一个可供复现此问题的 Demo 工程到这里来，我复现一下这个问题。

**Comment by javalove6688** [comment]
就你url直接访问一个目标文件比如a.json 这个里面是json文本，而这个框架返回ok

**Comment by getActivity** [comment]
@javalove6688 小伙子，你看框架的 Demo 工程，里面响应体就是 Json 数据，那它怎么是正常的？

**Comment by getActivity** [comment]
超过两个星期没有响应，自动关闭此 issue。
