### ISSUE TITLE
怎么打印详细日志，包含header和请求参数

### ISSUE THREAD

**Issue by liu-xinhui** [getActivity/EasyHttp#18]
目前只有地址和请求方式

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/99748615-d011c600-2b17-11eb-8d5e-70ed6c5b2bf6.png)

**Comment by getActivity** [comment]
经过验证，框架的日志打印是正常的

**Comment by liu-xinhui** [comment]
![image](https://user-images.githubusercontent.com/7698511/99748987-95f4f400-2b18-11eb-9762-09090a422d58.png)
我直接使用的AndroidProject开发的，里面打印的日志是这样的，需要配置什么吗

**Comment by liu-xinhui** [comment]
经试验，只有post时才打印header和param，get不打印

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/99797755-cebdb900-2b6a-11eb-8c77-df21dd8178bc.png)
