### ISSUE TITLE
[疑惑]：轮子哥你好 在特定情况下 EasyConfig.getInstance().addParam 添加的全局参数会消失

### ISSUE THREAD

**Issue by 756230883** [getActivity/EasyHttp#180]
### 问题描述【必填】

正常情况下 没有问题 添加的全局参数会携带在请求里 因为项目里有系统权限管理的功能 在设置里 拒绝了某项权限以后  再返回App 发现这时候的请求 都不会携带之前设置好的全局参数了 麻烦轮子哥看下是什么问题呢

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 这个问题属于 bug，不能提疑问 issue 单，请提 bug issue 单

请重新提一个 issue 并纠正以上问题
