### ISSUE TITLE
[Bug]：轮子哥你好 在特定情况下 EasyConfig.getInstance().addParam 添加的全局参数会消失

### ISSUE THREAD

**Issue by 756230883** [getActivity/EasyHttp#181]
### 框架版本【必填】

com.github.getActivity:EasyHttp:11.6

### 问题描述【必填】

正常情况下 没有问题 添加的全局参数会携带在请求里 因为项目里有系统权限管理的功能 在设置里 拒绝了某项权限以后 再返回App 发现这时候的请求 都不会携带之前设置好的全局参数了 麻烦轮子哥看下是什么问题呢

### 复现步骤【必填】

在设置里拒绝某项权限后  回到App  App会刷新 这时候 再去请求接口  公共参数全部消失了

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

30

### 出现问题的手机信息【必填】

华为P30Pro

### 出现问题的安卓版本【必填】

鸿蒙3.0.0

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

全部 oppo reno3

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by getActivity** [comment]
小伙子。有两个地方需要你提供一下：

1. 在设置里拒绝了某项权限以后：是拒绝了什么权限？请详细说明
2. 是否可以通过 Demo 来复现该问题【必答】是：请提供一个可供复现的 Demo 工程上来，我这边要对问题进行复现。

**Comment by 756230883** [comment]
[EasyHttp-master.zip](https://github.com/getActivity/EasyHttp/files/11661011/EasyHttp-master.zip)
附件为demo

**Comment by 756230883** [comment]
具体操作步骤
1  进入首页会申请存储权限   同意权限后  我在oncreate 里面添加了一个  tokenNew的全局参数 点击下一页 销毁首页
2  进去第二页 点击权限管理 禁用存储权限 返回回来 应用会刷新（其实禁用任意权限 回来都会刷新）
3 这时候再去任意请求  发现  tokenNew 已经没有了

--------------------------------------
如果把EasyConfig.getInstance().addParam放入第二页的oncreate 或者 onRestart里面 相当于再次添加一遍就没问题

**Comment by getActivity** [comment]
小伙子，我下载了你的 Demo 工程看了一下，首先断定这个问题不是框架的问题，而是你对于 Android 系统机制不熟悉导致的，当你禁用存储权限的时候，应用会直接被系统杀死，当你按返回键返回还能看到应用的时候，这是因为应用重启了，应用重启和正常应用启动的流程是不一样的，应用重启相比正常应用的流程有一定的差异性，具体表现为，重启的应用会经过 Application.onCreate 方法和最后一个停留 Activity.onCreate 方法，而中间有什么 Activity 启动了，这些 Activity 干了啥，系统是一概不会关心的。

**Comment by 756230883** [comment]
明白了 轮子哥 那我只能再 最后一个停留的Activity中 再去 EasyConfig.getInstance().addParam 添加一遍全局参数了
