### ISSUE TITLE
[疑惑]：如何动态host，我需求的host主机地址会变动。

### ISSUE THREAD

**Issue by AdminQQZ** [getActivity/EasyHttp#185]
### 问题描述【必填】

[疑惑]：如何动态host，我需求的host主机地址会变动。
![image](https://github.com/getActivity/EasyHttp/assets/12959954/09e6ba1b-3720-43f7-89ce-b5e4b88b2486)

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

### issue 列表中是否有人曾提过类似的问题【必答】

是

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

否

**Comment by AdminQQZ** [comment]
行了。
![image](https://github.com/getActivity/EasyHttp/assets/12959954/2b59f970-1027-42a2-87f5-290fd312d68b)

**Comment by getActivity** [comment]
<img width="381" alt="image" src="https://github.com/getActivity/EasyHttp/assets/28616817/2290ddd5-b49c-45a1-8ef2-bdcf9b004d50">

小伙子，这个问题我在文档上面已经有写了，但是你写了已经阅读了相关文档仍然没有解决，只能证明你没有认真看过文档，或者乱填 issue，像这种问题我一般是不会给予解答的，我会让提问的人自己去文档找答案。
