### ISSUE TITLE
[疑惑]：

### ISSUE THREAD

**Issue by yanwencheng** [getActivity/EasyHttp#186]
### 问题描述【必填】

Android app签名后，EasyHttp请求闪崩，不知道哪位大神遇到过

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 这个问题属于 bug，不能提疑问 issue 单，请提 bug issue 单

请重新提一个 issue 并纠正以上问题
