### ISSUE TITLE
[疑惑]：安全扫描提示HTTPS未校验服务器证书、主机名漏洞

### ISSUE THREAD

**Issue by yanwencheng** [getActivity/EasyHttp#187]
### 问题描述【必填】

在配置OkHttpClient时使用
![image](https://github.com/getActivity/EasyHttp/assets/11845393/213dcf3f-acbd-42c7-9d47-bbe478797b27)
但是上架安全扫描提示如下，不知道是不是误报
![image](https://github.com/getActivity/EasyHttp/assets/11845393/71932d6d-542f-4c93-9613-ef243a35cb7b)
![image](https://github.com/getActivity/EasyHttp/assets/11845393/42d527d6-8f04-4ba1-b76a-28e7169d5029)

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，我不是很懂你想表达什么意思？这个类只是我预设在框架中的，你可以用，也可以不用，默认情况下是不用的，这个类会给你带来什么影响吗？

**Comment by yanwencheng** [comment]
目前是安全扫描扫描出这两个方法，说是漏洞让删掉，我们从源码build了，已删掉了
&nbsp;


416970882
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月2日(星期天) 中午11:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [getActivity/EasyHttp] [疑惑]：安全扫描提示HTTPS未校验服务器证书、主机名漏洞 (Issue #187)





 
小伙子，我不是很懂你想表达什么意思？这个类只是我预设在框架中的，你可以用，也可以不用，默认情况下是不用的，这个类会给你带来什么影响吗？

**Comment by getActivity** [comment]
小伙子，我觉得吧，你大可不必专门去克隆框架的源码，然后删掉这个类，而是你直接引用这个框架，后面 app 在上线包打 release 包的时候开启 minifyEnabled 不就可以了？这样到时候没有用到的类在编译期间会被移除掉。

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
