### ISSUE TITLE
参数不传递父类字段

### ISSUE THREAD

**Issue by liu-xinhui** [getActivity/EasyHttp#19]
![image](https://user-images.githubusercontent.com/7698511/99643773-13245880-2a88-11eb-8238-d0670eccf0ef.png)
![image](https://user-images.githubusercontent.com/7698511/99643788-17e90c80-2a88-11eb-809d-f9eec26b0624.png)
http请求是发现只有elevatorName字段，父类中的pageNum和pageSize没有作为参数

**Comment by getActivity** [comment]
框架不支持解析父类里面的字段

**Comment by getActivity** [comment]
这个功能我之前有考虑加入，但是后面没有加入，因为这个需求比较少见，所以暂不考虑加入

**Comment by liu-xinhui** [comment]
因为需要写一个通用分页工具类，里面需要用到分页参数，没有父类的话会不好做。不过我已经用在子类中再写一遍pageNum和pageSize实现了，也影响不大

**Comment by Skqing** [comment]
希望能够支持读取父类参数，这个也不难。不行就提供一个开关参数吧，毕竟很多页面是列表页页码那些参数都一样，单独写在每个api类里面重复性很大

**Comment by getActivity** [comment]
[easyhttp-9.5.aar.zip](https://github.com/getActivity/EasyHttp/files/6329292/easyhttp-9.5.aar.zip)

**Comment by getActivity** [comment]
@Skqing 加上了，小伙子，你测试看一下，如果没有问题的话，我会在下个版本加上。
