### ISSUE TITLE
[疑惑]：如何获取当前请求的接口地址

### ISSUE THREAD

**Issue by zh3631** [getActivity/EasyHttp#193]
### 问题描述【必填】

你好轮子哥，框架 9.0 版本如何获取当前请求的接口地址，目前只可以获取 host 和 path，想要获取完整的请求 url?
需求是：捕捉后台返回的乱码，上报给后台。就是接口报错他会返回一些乱码，由于项目已经投入市场，一些以前的接口有的特定情况下会报错，然后抓到错误和当前的请求接口 一起给后台用来排查错误。图片上传不了，我给你复制关键代码。自己定义一个异常用来捕捉解析异常，就是返回的是乱码

```java
public Exception requestFail(LifecycleOwner lifecycle, Exception e) {
        // 判断这个异常是不是自己抛的
        if (e instanceof HttpException) {
            if (e instanceof TokenException) {
                // 登录信息失效，跳转到登录页
               
            }
            if (e instanceof ResultErrorException) {
                // 返回结果异常 乱码 PHP报错
                Application application = ActivityManager.getInstance().getApplication();
                
                BaseReq.sendError(errorText, application);//errorText是解析错误返回的乱码，现在缺少请求url
            }
            return e;
        }
       ...............................
}
```

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by zh3631** [comment]
你好轮子哥，如何获取当前请求的接口地址，目前只可以获取host和path，想要获取完整的请求url?
需求是：捕捉后台返回的乱码，上报给后台。就是接口报错他会返回一些乱码，由于项目已经投入市场，一些以前的接口有的特定情况下会报错，然后抓到错误和当前的请求接口 一起给后台用来排查错误。图片上传不了，我给你复制关键代码。自己定义一个异常用来捕捉解析异常，就是返回的是乱码

public Exception requestFail(LifecycleOwner lifecycle, Exception e) {
        // 判断这个异常是不是自己抛的
        if (e instanceof HttpException) {
            if (e instanceof TokenException) {
                // 登录信息失效，跳转到登录页
               
            }
            if (e instanceof ResultErrorException) {
                // 返回结果异常 乱码 PHP报错
                Application application = ActivityManager.getInstance().getApplication();
                
                BaseReq.sendError(errorText, application);//errorText是解析错误返回的乱码，现在缺少请求url
            }
            return e;
        }
       ...............................
}

**Comment by zh3631** [comment]
![微信图片_20230726124208](https://github.com/getActivity/EasyHttp/assets/50099790/c21c9d8b-f89d-4376-a4ce-a415b9379987)

**Comment by getActivity** [comment]
小伙子，你先升级一下框架，等你升级完就知道这个问题该怎么处理了。

**Comment by zh3631** [comment]
好的我试试，谢谢

**Comment by zh3631** [comment]
谢谢已经解决了，回调返回那里新增了请求接口对象。已经解决了我的疑问，还有个小小的疑问，升级完以后EasyLog也新增 了请求接口这个参数，问题是我项目大多数，为了方便，其他地方也用EasyLog来打印日志的。现在新增一个参数

**Comment by getActivity** [comment]
@zh3631 不要用 EasyLog 来打印项目的日志，这个框架内部使用的。

**Comment by zh3631** [comment]
好的，已经改了，一顿全局替换，我升级完也发现了，EasyLog 只用于EasyHttp。再次感谢轮子哥
