### ISSUE TITLE
[建议]：框架可以支持到 protobuf 吗

### ISSUE THREAD

**Issue by ITJoker** [getActivity/EasyHttp#194]
### 你觉得框架有什么不足之处？【必答】

框架可以支持到 protobuf 吗？ 

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

**Comment by getActivity** [comment]
收到，多谢小伙子的建议，目前框架支持的请求 Body 只有 Json 和表单两种，并且不支持扩展，这块确实是框架做得不够完善，我会在下个版本优化此问题，介于 protobuf 框架在行业还没有那么流行，所以框架会在下个版本对抽取和开放扩展接口出来。

**Comment by getActivity** [comment]
小伙子，这个问题已经在框架上面更新，更新一下到 12.5 版本即可。

**Comment by ITJoker** [comment]
谢谢大佬回复，有点小激动，总之很感谢很开心！
