### ISSUE TITLE
[疑惑]：

### ISSUE THREAD

**Issue by zhang3776813** [getActivity/EasyHttp#195]
### 问题描述【必填】

请问一下，如果提交json类型参数，本框架应该怎么写?看了示例项目，都是采用Form方式提交

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 乱填 issue 问题

请重新提一个 issue 并纠正以上问题
