### ISSUE TITLE
[疑惑]：可以优先使用IPV4来访问后台服务器吗

### ISSUE THREAD

**Issue by 740599886** [getActivity/EasyHttp#199]
### 问题描述【必填】

因为后台暂不支付IPV6访问，所以打算目前先改一版  如果用户使用IPV6来访问后台，应用这边手动给他 优先使用IPV4来访问，麻烦问下作者是否可以实现呢。

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，你说的这个事情如果要实现的话，是要修改 OkHttp 源码的对吧？

**Comment by 740599886** [comment]
这个不太清楚.....,   目前只了解如果该 运营商支持IPV6，会优先使用IPV6去访问，但是会报UnknownHostException错误，就是想如果这个运营商卡 同时支持IPV6和IPV4的话， 我们通过代码手动给他尝试使用IPV4去访问后台， 至于会修改到源码，确实不太清楚，有时间 大佬可以帮忙解释下   感谢

**Comment by getActivity** [comment]
小伙子，你这个就不是正常的需求，后台不支持 ipv6 的地址，属于后端的问题，应该是由后端来解决，而不是客户端来支持。

**Comment by 740599886** [comment]
好的 感谢大佬解答
