### ISSUE TITLE
怎么以body的方式请求啊？

### ISSUE THREAD

**Issue by qq171161636** [getActivity/EasyHttp#20]
![微信截图_20201120170524](https://user-images.githubusercontent.com/31119689/99782753-85626f00-2b54-11eb-82ac-4d92f84939e1.png)

**Comment by getActivity** [comment]
用 EasyHttp.post 不行？

**Comment by qq171161636** [comment]
http://**********/v1/sms?phone=15342590000   我问了下后台， 其实最终的是像get的拼接这种，但是却是post的请求，这个怎么处理？

**Comment by getActivity** [comment]
这个可以实现，你可以在 getApi 方法中手动拼接，不过我不推荐你这样做，因为 Post 请求就是将参数放置到 Body 中，而 Get 请求是将参数到 URL 中，这个是行业通用的标准。
