### ISSUE TITLE
[疑惑]：轮子哥，post接口，body里放数组对象，但是对象没有key 该怎么放啊，着急，在线等

### ISSUE THREAD

**Issue by xiaxinqing** [getActivity/EasyHttp#203]
### 问题描述【必填】

![image](https://github.com/getActivity/EasyHttp/assets/15827197/ce0280b0-5c2d-4a15-855a-63ce88cffbff)
轮子哥，post接口，body里放数组对象，但是对象没有key 该怎么放啊，着急，在线等。
如上图

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by xiaxinqing** [comment]
post 请求，参数正常是 k-v  键值对，碰到的问题是 是接口上传数据， 但是没有key

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 乱填 issue 回答

请重新提一个 issue 并纠正以上问题
