### ISSUE TITLE
[疑惑]：下载请求怎么设置超时时间

### ISSUE THREAD

**Issue by ylmyg** [getActivity/EasyHttp#204]
### 问题描述【必填】

我想问下，框架在下载的时候怎么单独设置超时的时间，目前我看到文档里面是设置整个框架超时的，比如我有两个地方用到下载，一个想设置超时10s，一个想设置超时20s，怎么进行单独的设置呢？

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by ylmyg** [comment]
下载里面没有.client()方法

**Comment by ylmyg** [comment]
我看到文档是有设置局部超时的方法，但是下载没有，请问我该怎么加上？

**Comment by getActivity** [comment]
<img width="671" alt="image" src="https://github.com/getActivity/EasyHttp/assets/28616817/24079cce-3220-4cf0-8d5e-7afda57368a7">

小伙子，你仿造这个写法，自定义一个 api 类，api 类实现 IRequestClient 接口即可。

**Comment by ylmyg** [comment]
![1696906210377](https://github.com/getActivity/EasyHttp/assets/7122217/5c988f2c-c277-4aea-8a12-009c0d10ba3a)
是这样么？ 但是 getOkHttpClient() 爆红了

**Comment by getActivity** [comment]
@ylmyg `EasyConfig.getInstance().getClient()` 是调的这个 API

**Comment by ylmyg** [comment]
可以了
