### ISSUE TITLE
[疑惑]：如何添加单个网络请求的header或者cookies

### ISSUE THREAD

**Issue by liwenlong15139561730** [getActivity/EasyHttp#205]
### 问题描述【必填】

我需要在下载文件请求的url里面 注入cookies

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，你说的注入 cookies 是指这个？

<img width="705" alt="image" src="https://github.com/getActivity/EasyHttp/assets/28616817/75dcad3c-2675-4b14-89ee-5bacaa99001c">

**Comment by liwenlong15139561730** [comment]
这个cookieJar应该是okhttp  response响应的时候得到新的Cookie回调。我应该是只需要在request的时候addheader("Cookie", "xxx")注入到单个请求中， 我看到EasyConfig好像是配置全局的。

**Comment by getActivity** [comment]
小伙子，你这个问题我在框架文档上面不是有写了？

**Comment by liwenlong15139561730** [comment]
不是，我现在 EasyConfig 是单例模式，然后通过EasyConfig.getInstance().addHeader(Keys.COOKIE, mCookies)添加了cookie，然后就是想问一下，是否对其他的网络请求有什么影响？？因为EasyConfig是单例模式 所以全局的网络请求都源自它，当我下次进行其他网络请求时，这个cookie需要移除吗？？因为我不是很清楚，所以在理念上想到的是 单对单的 配置+请求。

**Comment by liwenlong15139561730** [comment]
我搜了一下，发现可以通过CookieSyncManager向url里面直接注入cookie。
public static void synCookies(Context context, String url) {  
	    CookieSyncManager.createInstance(context);  
	    CookieManager cookieManager = CookieManager.getInstance();  
	    cookieManager.setCookie(url,  cookies); 	    		
	    CookieSyncManager.getInstance().sync();  
}

**Comment by getActivity** [comment]
<img width="1074" alt="image" src="https://github.com/getActivity/EasyHttp/assets/28616817/c64d19de-1ae4-48e8-9cde-4b027f30d04a">
