### ISSUE TITLE
[Bug]：多个接口header里面传同样key不同vaule，同时调用，会出现传错的问题

### ISSUE THREAD

**Issue by 1415605750** [getActivity/EasyHttp#207]
### 框架版本【必填】

EasyHttp:10.2

### 问题描述【必填】

公司项目内可以登录多个身份信息（以下称为token），不同身份信息调用不同接口，我的做法是，把token保存到本地，比如：
调用接口1的时候先调用EasyConfig.getInstance().removeHeader("X-Auth-Token");然后再调用 EasyConfig.getInstance().addHeader("X-Auth-Token", SPManager.getInsance().getValueBYkey("BrandToken"));
调用接口2的时候取同上，取token2放到header里传过去。
但是偶尔会出现一种情况：打印日志发现，接口2传的是token1.

我是在RequestHandler implements IRequestHandler  类用的response打印的接口和header对不上

### 复现步骤【必填】

多个接口传不同token，高并发同时调用

### 是否必现【必填】

否

### 项目 targetSdkVersion【必填】

29

### 出现问题的手机信息【必填】

小米11

### 出现问题的安卓版本【必填】

13

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

所有机型

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by getActivity** [comment]
小伙子，首先纠正你一点，这个问题属于你的 Bug，不是框架的 Bug，框架提供全局请求头或者全局参数设置，一旦设置了就是全局生效，你说的那种场景根本不能那样写，在多并发的情况下 100% 会有 Bug。

**Comment by getActivity** [comment]
如果要针对你说的这种场景做适配，可以先给 Api 类实现某个接口，然后再给 EasyHttp 设置全局的拦截器，在拦截器中做判断 Api 类是否实现某个接口了，再去添加不同的请求头或者请求参数。

```java
EasyConfig.getInstance().setInterceptor(new IRequestInterceptor() {
    @Override
    public void interceptArguments(@NonNull HttpRequest<?> httpRequest, @NonNull HttpParams params, @NonNull HttpHeaders headers) {
        if (httpRequest.getRequestApi() instanceof Xxx) {
            headers.put("X-Auth-Token", "xxxx");
        } else {
            headers.put("X-Auth-Token", "xxxx");
        }
    }
});
```

**Comment by 1415605750** [comment]
好的，感谢大佬，明白了
