### ISSUE TITLE
[疑惑]：请问GET请求支持传key同名value值不同的参数吗

### ISSUE THREAD

**Issue by qmdoit** [getActivity/EasyHttp#208]
### 问题描述【必填】

请问此GET请求支持传key同名的参数吗？类似OkGo的get请求传参时的params.put(key,value,false)这样？是需要自定义Api拼接参数吗？

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
<img width="1591" alt="image" src="https://github.com/getActivity/EasyHttp/assets/28616817/fe022a7c-d32c-4790-802e-9cd03e64325b">

**Comment by getActivity** [comment]
支持的，你在 Api 类中新建一个 List 字段，并且赋值即可。
