### ISSUE TITLE
[建议]：增加支持ProtoBuf格式数据解析

### ISSUE THREAD

**Issue by jintaox** [getActivity/EasyHttp#209]
### 你觉得框架有什么不足之处？【必答】

ProtoBuf是类似于Json和xml数据的数据格式

### issue 是否有人曾提过类似的建议？【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

**Comment by getActivity** [comment]
https://github.com/getActivity/EasyHttp/issues/194

**Comment by getActivity** [comment]
小伙子，我不是有回答过类似的问题了么？
