### ISSUE TITLE
[疑惑]：需求：发起一个http请求，有可能因为参数或者网络请求出错，不想在请求失败时弹出toast，显示出错信息给用户来看，怎样处理？

### ISSUE THREAD

**Issue by candebbs** [getActivity/EasyHttp#210]
### 问题描述【必填】

如题，发起一个http请求，有可能因为参数或者网络问题请求出错，不想在请求失败时弹出toast，显示出错信息给用户来看，怎样处理？

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by candebbs** [comment]
找到了

**Comment by RXlung** [comment]
> 找到了


同问，哪个设置？

**Comment by RXlung** [comment]
看明白了，写出答案：
抛出异常会走 requestFail  外部 就会走 onHttpFail  如果请求那有super.onHttpFail(e) 也会走覆写的override fun onHttpFail
方便后来者。
