### ISSUE TITLE
[建议]：请问以后会支持断点续传的功能么

### ISSUE THREAD

**Issue by ylmyg** [getActivity/EasyHttp#212]
### 你觉得框架有什么不足之处？【必答】

请问以后框架会支持断点续传的功能么，目前使用框架下载功能很好用，但是不懂怎么修改断点续传，我们服务器网络不太稳定，想增加断点，感觉无从下手。

### issue 是否有人曾提过类似的建议？【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### 你觉得该怎么去完善会比较好？【非必答】

希望增加。

**Comment by getActivity** [comment]
[EasyHttp-12.8.aar.zip](https://github.com/getActivity/EasyHttp/files/13463182/EasyHttp-12.8.aar.zip)

**Comment by getActivity** [comment]
@ylmyg 小伙子，我加上了，你用上面的包试试看。

**Comment by ylmyg** [comment]
@getActivity 感谢 我先体验一下 先别关闭issue

**Comment by ylmyg** [comment]
感觉不是很会用，请问有什么说明文档么？

**Comment by getActivity** [comment]
@ylmyg 小伙子，框架中默认是开启断点下载功能，你不需要额外设置其他 API，但是有一个前提条件，就是要你们服务器支持断点续传功能才可以。

**Comment by getActivity** [comment]
> @getActivity 感谢 请问下这个功能是单独分离出来的么 以后会合入正式的框架中么

是的，现在只是测试阶段，想让你帮我测试一下（理论上是没有问题的，因为这块我做了很多自测和处理），如果没有问题的话，过一段时间会发布到远程仓库上。

**Comment by ylmyg** [comment]
@getActivity 我也是直接使用框架的，刚才是我想多了，我们服务器是支持断点续传的功能的，我接下来会一直在测试。

**Comment by ylmyg** [comment]
请问下，我在下载的途中，手动断开了wifi连接，然后打开wifi，重新连接上以后，继续点击下载，为什么进度还是从0开始呢？难道是服务器不支持断点么，我们服务器是支持的。

**Comment by getActivity** [comment]
[EasyHttp.apk.zip](https://github.com/getActivity/EasyHttp/files/13472920/EasyHttp.apk.zip)

**Comment by getActivity** [comment]
@ylmyg 小伙子，你试一下上面 demo apk 包有没有这个问题？

**Comment by getActivity** [comment]
@ylmyg 另外你下载使用的文件类型，用的是 File 类还是 FileContentResolver 类？

**Comment by ylmyg** [comment]
com.hjq.http.EasyHttp.download(this)
            .method(HttpMethod.GET)
            .file(Config.BIN + File.separator + "all.bin")
            .url(d!!.fileUrl)
            .api(GjApi::class.java)
            .listener(object : OnDownloadListener {
                override fun onDownloadStart(file: File) {
 }
}
@getActivity 我是直接用file下载的 我想问下 是不是我操作得不对 我用apk也是下载一半以后 手动断开手机wifi 再重连wifi 再点击下载文件 还是一样从头开始下载

**Comment by getActivity** [comment]
@ylmyg  demo apk 包是否也有这个问题？

**Comment by getActivity** [comment]
[EasyHttp-12.8.aar.zip](https://github.com/getActivity/EasyHttp/files/13482831/EasyHttp-12.8.aar.zip)

**Comment by getActivity** [comment]
小伙子，之前是我把框架下载断点续传的功能默认设置成关闭了，你换成这个包试一下就好了。

**Comment by ylmyg** [comment]
@getActivity 太完美了 测试了10次 都可以断点续传

**Comment by ylmyg** [comment]
轮子，今天测一直有问题，下载过程中wifi断开，然后等待wifi连接上以后再开启下载，一直出现错误，我项目中有两处地方用到下载，一个地方下载文件大小是106k，另一个地方下载是30M。如果30M的下载触发断点，一直就会下载下来是106K，感觉和以前的下载有冲突了，而且下载进度显示了百分之169%

**Comment by ylmyg** [comment]
还发现如果第一个下载成功了。第二个点击下载直接触发下载成功，逻辑是第一个的下载文件

**Comment by ylmyg** [comment]
![1701329732976](https://github.com/getActivity/EasyHttp/assets/7122217/f74e629c-8917-477b-b9ab-c42b6ae9815f)
显示169 不懂啥意思

**Comment by ylmyg** [comment]
@getActivity 是的 下载路径都是一样的了 是否需要对应不一样的路径能解决此问题？

**Comment by getActivity** [comment]
@ylmyg  是的，小伙子

**Comment by ylmyg** [comment]
@getActivity 感谢

**Comment by ylmyg** [comment]
ABin里面的文件本来下载结束以后是30M的，然后再点击一次下载，再进入ABin文件夹里面看到大小变成Alot文件的大小了，感觉路径不一样还是有冲突呢

**Comment by ylmyg** [comment]
@getActivity 不行的 我把本地路径下的文件全部删除 重启手机 还是一样的 ABin目录下的文件 在触发断点的情况下 每次点击再次下载都不能再次下载了 不懂为什么

**Comment by getActivity** [comment]
> @getActivity 不行的 我把本地路径下的文件全部删除 重启手机 还是一样的 ABin目录下的文件 在触发断点的情况下 每次点击再次下载都不能再次下载了 不懂为什么

不是吧，只要路径不一样，理论上不会有这种情况出现的，我测试一下看看

**Comment by ylmyg** [comment]
轮子，用流量是可以的，怀疑是公司wifi做了手脚，导致不成功。我再测试一下，还有个问题，我怎么中断当前下载呢？比如说我当前界面在下载中，我退出界面了，我发现还在下载，以前旧版本我是调用.cancel方法，新版本已经没有了，我调用cancelAll没有能停止下载呢

**Comment by getActivity** [comment]
![](https://github.com/getActivity/EasyHttp/assets/28616817/eb7c4d54-fde2-44d5-85b5-65f44be39faf)

**Comment by ylmyg** [comment]
@getActivity 感谢
