### ISSUE TITLE
[疑惑]：请求参数都是key=value&key=value?能不能变成json的格式

### ISSUE THREAD

**Issue by wyp315360007** [getActivity/EasyHttp#213]
### 问题描述【必填】

请求参数都是key=value&key=value?能不能变成json的格式

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

否

**Comment by getActivity** [comment]
小伙子，你确定这个问题文档上面没有写？

**Comment by wyp315360007** [comment]
> 小伙子，你确定这个问题文档上面没有写？

我看到项目里有一个单独的HelpDoc.md文件，谢谢。不过我还是建议您能把这个帮助文件的链接加到README.md文件里，因为别的项目普遍都会把帮助文档写到README文件里醒目的地方。

**Comment by getActivity** [comment]
@wyp315360007 小伙子，你确定我没有把帮助文档链接写到  `README.md` 文件中？

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
