### ISSUE TITLE
[疑惑]：请求中加入headers，这个headers的token加密后的值比较长

### ISSUE THREAD

**Issue by xiongwenzhi** [getActivity/EasyHttp#215]
### 问题描述【必填】

请求中加入headers，这个headers的token加密后的值比较长，然后打印出来的值比较长，跟后台比较这个值，后台反馈说我打印的值换行了，所以就对不上后台的token，就报错了。

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by xiongwenzhi** [comment]
![微信图片_20231207164103](https://github.com/getActivity/EasyHttp/assets/12386795/1835e955-0169-4080-a71f-5094a4175d19)
看这个又好像没有换行

**Comment by xiongwenzhi** [comment]
![Uploading 微信图片_20231207165853.png…]()

**Comment by getActivity** [comment]
小伙子，你 debug 一下这行代码，然后往下排查，看一下是不是真的被转换了？目前我来看是没有的。

**Comment by getActivity** [comment]
![](https://github.com/getActivity/EasyHttp/assets/28616817/3702e141-2cfb-4a08-8fa1-4f4f2abc92b7)

我目前用 HttpCanary 抓包来看是正常的，字符串没有经过转换。

**Comment by getActivity** [comment]
<img width="883" alt="image" src="https://github.com/getActivity/EasyHttp/assets/28616817/db42ac94-cf3c-4702-ba57-402dcb956a7c">
