### ISSUE TITLE
[疑惑]：formRequest 如何统一转换为JsonRequest

### ISSUE THREAD

**Issue by renwfy** [getActivity/EasyHttp#216]
### 问题描述【必填】

formRequest 如何统一转换为JsonRequest ，把之前的请求参数加密传jsonBody

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

否

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有认真阅读文档之后才能提 issue

* 没有看过别人是否提过类似的 issue

请重新提一个 issue 并纠正以上问题
