### ISSUE TITLE
[Bug]：IRequestInterceptor中的方法interceptArguments发生在主线程

### ISSUE THREAD

**Issue by cnswan** [getActivity/EasyHttp#217]
### 框架版本【必填】

12.6

### 问题描述【必填】

封装请求时，需对收集到的参数做统一加密，当涉及到文件时会转换base64编码，这是一个耗时操作，我翻看了源码在HttpRequest.java类里，request方法中，createCall()是发生在当前线程的，从而导致interceptArguments发生在主线程。

### 复现步骤【必填】

APP界面选择图片，调用EasyHttp.post(t).api(api).tag(tag).request(callback)异步方法，HttpInterceptor拦截参数并对文件转换，AppActivity实现的onHttpStart()中showLoading()出现空窗期（点击按钮后几秒后才出现loading）

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

30

### 出现问题的手机信息【必填】

荣耀20;iqoo12Pro

### 出现问题的安卓版本【必填】

30

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

全部

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

否

### 提供解决方案

```
/**
 * 执行异步请求
 */
public void request(@Nullable OnHttpListener<?> listener) {
    if (mDelayMillis > 0) {
        // 打印请求延迟时间
        EasyLog.printKeyValue(this, "RequestDelay", String.valueOf(mDelayMillis));
    }

    StackTraceElement[] stackTrace = new Throwable().getStackTrace();
    Runnable runnable = () -> {
        if (!HttpLifecycleManager.isLifecycleActive(mLifecycleOwner)) {
            // 宿主已被销毁，请求无法进行
            EasyLog.printLog(HttpRequest.this,
                    "LifecycleOwner has been destroyed and the request cannot be made");
            return;
        }
        EasyLog.printStackTrace(HttpRequest.this, stackTrace);
        NormalCallback normalCallback =
                new NormalCallback(HttpRequest.this)
                        .setListener(listener);
        normalCallback.dispatchHttpBeforeCallback();
        mCallProxy = new CallProxy(createCall());
        normalCallback.setCall(mCallProxy).start();
    };
    if (mDelayMillis > 0) {
        // issue 地址：https://github.com/getActivity/EasyHttp/issues/159
        int what = mTag == null ? Integer.MAX_VALUE : mTag.hashCode();
        EasyUtils.postDelayedRunnable(() ->
                EasyUtils.runOnIOThread(runnable), what, mDelayMillis);
    } else {
        EasyUtils.runOnIOThread(runnable);
    }
}
```

**Comment by getActivity** [comment]
> 封装请求时，需对收集到的参数做统一加密，当涉及到文件时会转换base64编码

小伙子，你说参数加密要在 `interceptArguments` 做处理，这个我可以理解，但是要对文件做 base64 处理，这个就有点匪夷所思了，你为什么不直接传 base64 给框架？而是要先变成文件，然后再变成 base64，这样不是等于变相替换了参数的类型？

**Comment by cnswan** [comment]
帅哥，你说的对，就是替换成加密参数，加密文件
我为什么不直接传 base64 给框架？而是要先变成文件，然后再变成 base64
因为是从图库里选的，不能选一张转一次base64吧，我的思路是选完了提交的时候一起处理，框架提供拦截参数这个位置也比较合适，一个出口，如果文件本身是base64的话这里不涉及转换

如果单独线程先转换，再提交，dialog方法可能比较繁琐，要show两次

**Comment by getActivity** [comment]
小伙子，我理解文件转 base64 只能算编码，不能算加密吧？

**Comment by getActivity** [comment]
不过你说的一点启发了我，不能在主线程发起网络请求，因为过程可能包含了一些耗时操作，不仅是你要做加密操作，框架内部会做一些反射操作，所以我把它放到子线程中来。

**Comment by cnswan** [comment]
“小伙子，我理解文件转 base64 只能算编码，不能算加密吧？”
说错了，参数是AES，文件是base64
期待帅哥的下一个版本，感恩

**Comment by getActivity** [comment]
[EasyHttp-12.8.aar.zip](https://github.com/getActivity/EasyHttp/files/13738960/EasyHttp-12.8.aar.zip)

**Comment by getActivity** [comment]
@cnswan 小伙子，问题处理了，你可以用上面的版本试一下有没有这个问题，有问题及时反馈一下。

**Comment by cnswan** [comment]
![image](https://github.com/getActivity/EasyHttp/assets/14156066/a968e4b0-86a4-4202-9268-c17041622c5e)

**Comment by getActivity** [comment]
@cnswan 小伙子，你反馈的这两个问题，我经过核实，确实是真实存在的，目前我已经在框架内部做处理了，你可以下载上面的 aar 包做一下测试。
