### ISSUE TITLE
[疑惑]：如何动态设置请求头

### ISSUE THREAD

**Issue by GuoLiangjun123** [getActivity/EasyHttp#218]
### 问题描述【必填】

我们的请求头并不是固定的，而是根据不同的接口参数来设置不同的请求头，比如接口A的请求参数是a1,a2那么请求头就是a1,a2，如果接口B的请求参数是B1,B2那么这个时候请求头就变成了b1,b2。请问这种动态设置请求头的需求可以实现吗？

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by GuoLiangjun123** [comment]
我看了一下在EasyConfig中有一个addHeader的方法，但是我想在api类里面进行addHeader,现在的问题是我如何在api类里面获取到EasyConfig对象从而进行addHeader

**Comment by getActivity** [comment]
小伙子，你确定这个问题文档上面没有写？

**Comment by GuoLiangjun123** [comment]
> 小伙子，你确定这个问题文档上面没有写？

EasyConfig.getInstance().addHeader("key", "value"); 这个吗哥

**Comment by getActivity** [comment]
@GuoLiangjun123  不是这个，你再仔细找找

**Comment by GuoLiangjun123** [comment]
> @GuoLiangjun123 不是这个，你再仔细找找

给字段加上 @HttpHeader 注解即可，则表示这个字段是一个请求头，如果没有加上此注解，则框架默认将字段作为请求参数，就是这个了吧哥

**Comment by getActivity** [comment]
@GuoLiangjun123 小伙子，还是找错了，你现在还是认真把文档看一遍再说。

**Comment by GuoLiangjun123** [comment]
> @GuoLiangjun123 小伙子，还是找错了，你现在还是认真把文档看一遍再说。

IRequestInterceptor 接口来实现，是这个吗?如果是这个的话相当于返回一个全新的header，但是我们的需求是有两个全局的header和一个根据每个接口参数定义的动态header，我们现在要做的是这个动态heaer，所以看了整个文档下来还是觉得在文档的描述下 @HTTPHeader 注解最适合我们的需求

**Comment by FOnlyJack** [comment]
> 我看了一下在EasyConfig中有一个addHeader的方法，但是我想在api类里面进行addHeader,现在的问题是我如何在api类里面获取到EasyConfig对象从而进行addHeader

![image](https://github.com/getActivity/EasyHttp/assets/24829008/cb7a1816-8b79-4c4a-9cd6-94cf585eb9a0)
这样都能自定义的

**Comment by chen3441251** [comment]
也遇到了动态请求头的问题，搜索了一下issue都是已知请求头字段的情形，楼上的兄弟应该也是那种动态传入进来的header不知道如何设置成请求头，看了一下源码，原来轮子哥早就设计好了 
@HttpHeader
private HashMap<String,String> map

只要把传入进来的动态header键值对存入map字段，框架识别注解后会自动转换成header。之所以在这个close的issue回复不想重新开一个已有解决方案的问题，推测应该是轮子哥的文档里面举例都是单一字段，所以大家都不知道动态多字段怎么传了，轮子哥更新一下文档相信能更好
