### ISSUE TITLE
[疑惑]：post提交参数的问题 是否可以直接map提交 

### ISSUE THREAD

**Issue by liuhuicheng** [getActivity/EasyHttp#219]
### 问题描述【必填】

表单修改的时候有很多字段，只修改了某一个字段，提交的时候想直接实体类转化为map提交，是否可以直接map参数提交。如果按RequestApi中的字段提交 ，将会set很多字段。

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，对于这个问题，你可以直接在 api 类中定义一个方法，然后将你说的实体类对象传进来，在方法中对实体类的字段进行提取到 api 类中的字段上面。

**Comment by liuhuicheng** [comment]
好的 谢谢！
