### ISSUE TITLE
[疑惑]：为什么会出现多余的请求参数

### ISSUE THREAD

**Issue by GuoLiangjun123** [getActivity/EasyHttp#220]
### 问题描述【必填】

1.当我在请求用户信息接口之前 我会先重新设置一个拦截器，根据拦截器返回的接口参数进行加密，然后将该加密过后的值设置为header。但是当我在终端打印请求日志的时候发现，我多了一些请求参数，这是为什么呢？
![QQ图片20240102153031](https://github.com/getActivity/EasyHttp/assets/34742384/63d274f8-cba5-4756-b747-59fec0fc8426)
![QQ图片20240102153109](https://github.com/getActivity/EasyHttp/assets/34742384/3009c990-1d28-4fa3-a18c-c6af5f695715)
![微信图片_20240102152826](https://github.com/getActivity/EasyHttp/assets/34742384/2bdd51c8-9b23-4efa-8b72-34f79b2109a1)

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
<img width="649" alt="image" src="https://github.com/getActivity/EasyHttp/assets/28616817/f5e220f1-8ccf-40f4-be30-9b6fdafac059">

<img width="724" alt="image" src="https://github.com/getActivity/EasyHttp/assets/28616817/3771b2dc-4d34-4c62-b800-50f17c0a8e11">

小伙子，确定这个参数不是你自己加上的？

**Comment by getActivity** [comment]
<img width="736" alt="image" src="https://github.com/getActivity/EasyHttp/assets/28616817/cbfeb0a8-c01e-45ee-ae33-24978bb0b728">

**Comment by getActivity** [comment]
@GuoLiangjun123 小伙子，你的代码不是写得很明显了？你把 `params.params` 对象传给 headerEncode 方法了，对应的 headerEncode 方法里面 `dic` 参数，然后你判断 dic 是否为空，如果为空就用 `mutableMapOf` 扩展函数创建，但是很显然，结果不为空，所以直接就复用了 `dic` 参数，`signDic` 直接就等于 `dic`，然后你给 `dic` 赋值了两个键值对，这才导致的请求里面也有参数。
