### ISSUE TITLE
[疑惑]：是否有参数控制加载的时候 不出现加载动画？

### ISSUE THREAD

**Issue by Moonwing2020** [getActivity/EasyHttp#223]
### 问题描述【必填】

是否有参数控制加载的时候 不出现加载动画？

### 框架文档是否提及了该问题【必答】

是

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，框架内部不会做任何 UI 的更新，你说的加载动画，应该是基于框架封装的一些功能，这个加载动画 Demo 工程上面有演示，具体怎么控制，你可以看一下 Demo 的源码，其实就是一个 `ProgressDialog`，在这里我不再赘述。

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
