### ISSUE TITLE
[建议]：请求方式统一设置

### ISSUE THREAD

**Issue by whl0718** [getActivity/EasyHttp#224]
### 你觉得框架有什么不足之处？【必答】

请求方式都是通过`EasyHttp.post`或者`EasyHttp.get`来设置，分散各处，接口请求方式修改后需要全局搜索修改，能不能提供一个统一设置的地方，类似`IRequestType`  `IRequestPath`的接口来统一设置

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

**Comment by getActivity** [comment]
@whl0718 小伙子，你先回答我一个问题，你为什么要全局修改接口的请求方式？

**Comment by whl0718** [comment]
> @whl0718 小伙子，你先回答我一个问题，你为什么要全局修改接口的请求方式？

后端之前写的不规范，需要修改，导致要一个一个寻找修改

**Comment by whl0718** [comment]
还有一个问题我写好了接口类，其他人使用这个接口不知道请求方式，还需要查看接口文档

**Comment by getActivity** [comment]
> > @whl0718 小伙子，你先回答我一个问题，你为什么要全局修改接口的请求方式？
> 
> 后端之前写的不规范，需要修改，导致要一个一个寻找修改

小伙子，既然是后端的问题，为什么最终要让框架来改？

**Comment by getActivity** [comment]
> 还有一个问题我写好了接口类，其他人使用这个接口不知道请求方式，还需要查看接口文档

小伙子，一个接口的请求方式可以有多种形式，并不是一个接口只能用一种请求方式，同一个接口，即可以用 Get 请求一遍，也可以用 Post 再请求一遍。

**Comment by whl0718** [comment]
> > > @whl0718 小伙子，你先回答我一个问题，你为什么要全局修改接口的请求方式？
> > 
> > 
> > 后端之前写的不规范，需要修改，导致要一个一个寻找修改
> 
> 小伙子，既然是后端的问题，为什么最终要让框架来改？

只是提个建议，有的话只是后面方便一点

**Comment by getActivity** [comment]
> > > > @whl0718 小伙子，你先回答我一个问题，你为什么要全局修改接口的请求方式？
> > > 
> > > 
> > > 后端之前写的不规范，需要修改，导致要一个一个寻找修改
> > 
> > 
> > 小伙子，既然是后端的问题，为什么最终要让框架来改？
> 
> 只是提个建议，有的话只是后面方便一点

小伙子，如果是方便所有人，可以考虑一下，但是你这种场景太极端了，并且还是你自己的问题，我如果采纳这个建议，将没有任何理由说服其他提出质疑的人。

**Comment by whl0718** [comment]
好的谢谢
