### ISSUE TITLE
[Bug]：MMKV升级成1.3.2版本报错

### ISSUE THREAD

**Issue by ahnkk** [getActivity/EasyHttp#225]
### 框架版本【必填】

12.6

### 问题描述【必填】

12.6版本能够正常运行，但升级MMKV最新版1.3.2后会报错：Caused by: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
轮子哥你的另一个项目AndroidProject内使用的EasyHttp版本是10.2，此项目内MMKV升级成1.3.2版本可以正常运行。

### 复现步骤【必填】

MMKV版本升级当前最新版1.3.2
implementation 'com.tencent:mmkv:1.3.2'

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

30

### 出现问题的手机信息【必填】

红米k40

### 出现问题的安卓版本【必填】

12

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

全部

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by getActivity** [comment]
@ahnkk 小伙子，我理解这个问题不属于 EasyHttp 框架的问题吧？

**Comment by ahnkk** [comment]
> @ahnkk小伙子，我明白这个问题不属于EasyHttp框架的问题吧？

@getActivity  项目内EasyHttp 升级版本后，出现了这个问题，老的EasyHttp 没问题的，不知道什么原因，有点困惑，只能咨询咨询轮子哥您啦

**Comment by getActivity** [comment]
> > @ahnkk小伙子，我明白这个问题不属于EasyHttp框架的问题吧？
> 
> @getActivity 项目内EasyHttp 升级版本后，出现了这个问题，老的EasyHttp 没问题的，不知道什么原因，有点困惑，只能咨询咨询轮子哥您啦

@ahnkk 小伙子，你说错了吧，我看你上面的意思是，你是升级 mmkv 导致的问题吧？而不是升级 EasyHttp 导致的吧？

**Comment by getActivity** [comment]
> > @ahnkk小伙子，我明白这个问题不属于EasyHttp框架的问题吧？
> 
> @getActivity 项目内EasyHttp 升级版本后，出现了这个问题，老的EasyHttp 没问题的，不知道什么原因，有点困惑，只能咨询咨询轮子哥您啦

小伙子，如果确定是 EasyHttp 请告诉我，我尽全力协助解决，如果无法确定是 EasyHttp 框架的问题，则需要你自行处理。

**Comment by ahnkk** [comment]
> > > @ahnkk小伙子，我明白这个问题不属于EasyHttp框架的问题吧？
> > 
> > 
> > @getActivity 项目内EasyHttp 升级版本后，出现了这个问题，老的EasyHttp 没问题的，不知道什么原因，有点困惑，只能咨询咨询轮子哥您啦
> 
> 小伙子，如果确定是 EasyHttp 请告诉我，我尽全力协助解决，如果无法确定是 EasyHttp 框架的问题，则需要你自行处理。

我项目中使用到了EasyHttp 和MMKV，并且做了升级后出现上面的报错信息，但我不知道是因为什么报错，因为修改了很多。然后就去验证，最终发现是MMKV升级引起的。 EasyHttp 框架DEMO内也使用到了MMKV，这时不谈我的项目报错。在您这个DEMO内把MMKV版本改成最新后，一样会报错。 在您的另一个AndroidProject内一样做了MMKV升级尝试，因为那个里面是老版本的EasyHttp，最终得出老版本EasyHttp没问题，EasyHttp和MMKV如果都是最新版本的就会报错。 这就是全过程。 如果您觉得不是框架问题，那我继续使用老版本MMKV。 我觉得是您项目DEMO中使用到了MMKV，而不是MMKV使用了您的框架，所以我来这里提了问题。

**Comment by ahnkk** [comment]
> > > @ahnkk小伙子，我明白这个问题不属于EasyHttp框架的问题吧？
> > 
> > 
> > @getActivity 项目内EasyHttp 升级版本后，出现了这个问题，老的EasyHttp 没问题的，不知道什么原因，有点困惑，只能咨询咨询轮子哥您啦
> 
> @ahnkk 小伙子，你说错了吧，我看你上面的意思是，你是升级 mmkv 导致的问题吧？而不是升级 EasyHttp 导致的吧？

EasyHttp 10.2和MMKV1.3.2可以正常一起使用。EasyHttp 12.6和MMKV1.3.2在一起使用就报错。所以也可以说是升级EasyHttp 导致的吧

**Comment by getActivity** [comment]
小伙子，这个问题是 mmkv 里面依赖了某些较高版本 androidx 的依赖，导致和原有项目的 androidx 依赖的版本冲突了，改成以下依赖编译就能通过了

```groovy
dependencies {
    // 腾讯 MMKV：https://github.com/Tencent/MMKV
    implementation ('com.tencent:mmkv-static:1.3.2') {
        // 避免版本不一致导致的依赖冲突，从而导致编译报错
        exclude group: 'androidx.annotation', module: 'annotation'
    }
}
```
