### ISSUE TITLE
[Bug]：在AndroidProject Demo中搭配此库成功调用返回后，Object转型失败

### ISSUE THREAD

**Issue by bibubi** [getActivity/EasyHttp#226]
### 框架版本【必填】

10.2/12.6

### 问题描述【必填】

在[AndroidProject](https://github.com/getActivity/AndroidProject) Demo中使用 EasyHttp:10.2，在  EasyHttp.post(this).request(this);时候，Activity的onSucceed进行Object转换HttpData
![image](https://github.com/getActivity/AndroidProject/assets/18078927/e9f7de08-2803-4c88-b592-98e2af3642d1)
在[AndroidProject](https://github.com/getActivity/AndroidProject) Demo中使用 EasyHttp:12.6，在  EasyHttp.post(this).request(this);时候，Activity的onHttpSuccess进行Object转换HttpData
![image](https://github.com/getActivity/AndroidProject/assets/18078927/b506200d-753f-43cb-86fd-89337f97e87e)

### 复现步骤【必填】

Activity实现OnHttpListener

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

30

### 出现问题的手机信息【必填】

荣耀 20、红米K20

### 出现问题的安卓版本【必填】

Android 10、11

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

全部

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by getActivity** [comment]
<img width="408" alt="image" src="https://github.com/getActivity/EasyHttp/assets/28616817/e934db85-ee1b-44e0-870e-fea5f785bf66">

小伙子，你确定没有人提过类似的问题？
