### ISSUE TITLE
[疑惑]：为啥不用OKhttp自带的okhttp3.Interceptor

### ISSUE THREAD

**Issue by budaowengd** [getActivity/EasyHttp#228]
### 问题描述【必填】

原因：调试过程中发现 IRequestInterceptor 的调用都是在主线程执行的，因为我们接口会针对请求参数加密，响应参数解密，在主线程调用不太好，所以想基于okhttp3.Interceptor的实现，因为okhttp3.Interceptor是在子线程调用的。
疑问：我看源码中，没有到 okhttp3.Interceptor来实现拦截器的功能。是有什么考量吗？ 想听听轮子哥的观点，谢谢。

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，你确定这个问题没有人提过？

**Comment by budaowengd** [comment]
我在Issues 搜了"拦截器"，没看到相关的疑惑，加解密问题有人提过，所以我准备采用 "okhttp3.Interceptor" 来实现。我只是疑惑源码里为啥不用  "okhttp3.Interceptor" ，不是寻求解决加解密问题。

**Comment by getActivity** [comment]
@budaowengd 小伙子，你换个关键词再试一下

**Comment by getActivity** [comment]
`IRequestInterceptor`、加密、解密、主线程

**Comment by budaowengd** [comment]
好的，谢谢
