### ISSUE TITLE
[建议]：希望增加每个http请求可以自定义输入日志。

### ISSUE THREAD

**Issue by candebbs** [getActivity/EasyHttp#229]
### 你觉得框架有什么不足之处？【必答】

有这样开发场景，我一般关闭eashhttp的日志，一个界面有多个http请求，有可能是同时发出，有几个http请求的参数和返回来数据很重要，这几个http请求，能不能有一个属性可以打开日志，看请求头和返回数的参数？
EasyConfig.getInstance().setLogEnabled(false);这个是全局设置的，如果几个请求是同时发出的，做不了限制到每一个http请求的。

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

**Comment by getActivity** [comment]
@candebbs 小伙子，对于这种需求，框架表示无法支持，日志打印只能是统一开关，如果你有看某个请求日志的需求，可以考虑用抓包软件来看。

**Comment by getActivity** [comment]
之所以框架不支持的原因是：这种需求过于小众，但是对于框架来讲改动过大，对框架整体收益很小，并且你这个需求有其他方式实现。

**Comment by candebbs** [comment]
好的，谢谢。
