### ISSUE TITLE
[疑惑]：okhttp能够使用最新版本（4.x.x）吗？

### ISSUE THREAD

**Issue by moneeWong** [getActivity/EasyHttp#231]
### 问题描述【必填】

之前用的一直是4.10.0版本，很稳定，但retrofit弊端正如你所说，请问此库是否能够使用

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，这个问题你只能自己试验一下，理论上应该是没有问题的，不过只是理论而已，实际行不行你还要多测试一下。

**Comment by moneeWong** [comment]
> 小伙子，这个问题你只能自己试验一下，理论上应该是没有问题的，不过只是理论而已，实际行不行你还要多测试一下。

好的，感谢
