### ISSUE TITLE
[建议]：newWebSocket

### ISSUE THREAD

**Issue by actor20170211030627** [getActivity/EasyHttp#235]
### 你觉得框架有什么不足之处？【必答】

框架没有newWebSocket功能, 我以前使用的框架有这个功能, 但是换到EasyHttp后没有这个功能, 导致我不能完全替代, 需要自己再手动封装1个工具类.

### issue 是否有人曾提过类似的建议？【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### 你觉得该怎么去完善会比较好？【非必答】

别人提过, 但是你后来没有回答: [issues/40](https://github.com/getActivity/EasyHttp/issues/40)
我这儿遇到的情况是只有1个小功能需要Socket稍微连接一下, 以前使用的框架就是直接使用的Ok3的newWebSocket, 并不需要很稳定的Socket, 也没必要集成1个专业的Socket框架, 所以还是挺期望增加这个功能.

**Comment by getActivity** [comment]
小伙子，我经过再次慎重思考后，还是不会将 WebSocket 纳入到 EasyHttp，这是因为 EasyHttp 是基于 Http 封装的框架，Http 和 WebSocket 同属两种不同应用层的协议，并且两者的差异过大，之间的关联性也不大。
