### ISSUE TITLE
[疑惑]：请求数据接口加密和接口返回数据解密在哪进行拦截？

### ISSUE THREAD

**Issue by xuqinghao1991** [getActivity/EasyHttp#237]
### 问题描述【必填】

您好！EasyHttp框架版本使用的10.2版本，接口请求需要进行AES 加密 ，返回数据需要进行解密。请问在哪个类的方法里进行加密和解密操作？

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
<img width="462" alt="image" src="https://github.com/getActivity/EasyHttp/assets/28616817/8083ea3c-dd51-40ca-bd33-3eb70db3763c">

**Comment by getActivity** [comment]
小伙子，你确定上面这些问题都有严格执行？

**Comment by getActivity** [comment]
长时间没有响应，自动关闭此 issue。
