### ISSUE TITLE
[疑惑]：异步HTTP请求完成后如何渲染数据

### ISSUE THREAD

**Issue by liangjunsi** [getActivity/EasyHttp#238]
### 问题描述【必填】

轮子哥，不好意思我是一个新手，我想知道异步HTTP请求结束后怎么把数据渲染到页面，就好像下图中，因为HTTP是异步的，list第一次请求为空，我在文档和示例代码里找了很久还是没有找到想要的答案。
![Snipaste_2024-03-25_18-45-53](https://github.com/getActivity/EasyHttp/assets/47653527/86ef144e-435a-4f02-ae91-1adc65067f4a)

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by liangjunsi** [comment]
你的项目里的案例是模拟数据
![Snipaste_2024-03-25_18-45-53](https://github.com/getActivity/EasyHttp/assets/47653527/cbafd4d0-c04b-431e-97bb-4d1c9d095cf8)

**Comment by liangjunsi** [comment]
这是你项目里的代码，属于模拟数据
![Snipaste_2024-03-25_18-51-19](https://github.com/getActivity/EasyHttp/assets/47653527/cd83c7ae-a76b-42ce-8333-68128b8e61fb)

**Comment by getActivity** [comment]
小伙子，这个问题属于你个人的技术问题， 我目前不回答框架之外的问题，另外关于这块的说明在你提 issue 的时候已经写了，你可以看一下

<img width="956" alt="image" src="https://github.com/getActivity/EasyHttp/assets/28616817/5e7686dc-82aa-449f-a49a-c95998e80ea8">

<img width="836" alt="image" src="https://github.com/getActivity/EasyHttp/assets/28616817/3c3f44e7-cad3-40a0-95cf-75c765141fb9">
