### ISSUE TITLE
[疑惑]：我在APP里面集成了easyHttp，然后集成了一个第三方库，也集成了easyHttp  应该怎么分别调用

### ISSUE THREAD

**Issue by dzq0906** [getActivity/EasyHttp#240]
### 问题描述【必填】

[疑惑]：我在APP里面集成了easyHttp，然后集成了一个第三方库  也集成了easyHttp   这样初始化配置会被sdk的easyhttp的初始化配置替换掉然后走的回调都会是sdk里面的配置（因为sdk在后面初始化），我应该怎么使2个easyhttp分开

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
兼容的方案有以下几种：

1. 统一项目和三方库的 EasyHttp 的版本，具体以哪个为准，可以自行斟酌选择
2. 不建议三方库直接依赖三方库，如果三方库的网络请求不多，可以将 EasyHttp 的代码从中移除和替换成其他方式
3. 克隆 EasyHttp 的工程，并修改框架所在的包名，这样它们就属于两套不同的框架，互不干扰，但是你这样就算修改了我的框架，后续有什么问题只能靠你自己解决了，我目前只维护主分支的代码。

**Comment by dzq0906** [comment]
好的
