### ISSUE TITLE
[疑惑]：后端需要一个参数值为 null，但是设置为 null 后参数不会提交给后台

### ISSUE THREAD

**Issue by dearsteram** [getActivity/EasyHttp#241]
### 问题描述【必填】

后端需要一个参数值为 null，但是设置为 null 后参数不会提交给后台

### 框架文档是否提及了该问题【必答】

是

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
为什么要把 null 值的字段传给后台？这样做的意义在哪里？

**Comment by dearsteram** [comment]
> 为什么要把 null 值的字段传给后台？这样做的意义在哪里？

后端就是这么要求的，我只能根据后端要求传字段。

**Comment by getActivity** [comment]
@dearsteram 框架目前没有办法实现这个需求，预计未来也不会支持
