### ISSUE TITLE
[Bug]：请求头参数的字母被转成小写了

### ISSUE THREAD

**Issue by HeVTion** [getActivity/EasyHttp#243]
### 框架版本【必填】

4.11.0

### 问题描述【必填】

非常着急，header直接被转小写了！！！ ，服务端不兼容，求作者指教

### 复现步骤【必填】

添加一个header，任意大写

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

34

### 出现问题的手机信息【必填】

全部

### 出现问题的安卓版本【必填】

所有

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

全部

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供截图或视频

authorization:  Bear

**Comment by HeVTion** [comment]
老师很着急， 为什么全部转小写了，我不知道怎么处理哦

**Comment by getActivity** [comment]
<img width="1680" alt="image" src="https://github.com/getActivity/EasyHttp/assets/28616817/fd0cbb16-e23f-42bb-981a-b0a7829c748e">

<img width="1680" alt="image" src="https://github.com/getActivity/EasyHttp/assets/28616817/682a7728-cc23-40e5-b0c2-a81f772cc4f3">

小伙子，我经过测试验证，请求头无论是 key 还是 value，都是可以携带大写英文，并不存在你说的大写自动转小写。
