### ISSUE TITLE
[建议]：是否支持文件上传断点续传

### ISSUE THREAD

**Issue by chinamingsss** [getActivity/EasyHttp#244]
### 你觉得框架有什么不足之处？【必答】

文件上传如何实现断点续传功能

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### 你觉得该怎么去完善会比较好？【非必答】

文件上传如何实现断点续传功能

**Comment by getActivity** [comment]
小伙子，从目前的情况来看，Http 协议中并没有断点上传的标准，同时我也看了业内的实现方式，没有统一的标准，所以这个需求大概率不会在未来的版本中实现。

**Comment by chinamingsss** [comment]
我肤浅了，一直用你这个框架，上传的断点续传我基于你这个框架自己实现了一下
感谢大佬一直更新提供这么好的框架 哈哈哈哈
