### ISSUE TITLE
[疑惑]：Get请求能否实现 https://ebook/note/delete/{id} 将id传入进去？路径传参好像一时半会儿还没找到解决办法

### ISSUE THREAD

**Issue by jasonMouse** [getActivity/EasyHttp#246]
### 问题描述【必填】

用了这个框架之后，项目都做完了，这个时候突然加了一个需求，要调用一个这样的接口，我看了很久也没找到任何可以解决这个问题的办法，还请轮子哥帮忙看看

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
<img width="922" alt="image" src="https://github.com/getActivity/EasyHttp/assets/28616817/4cda1501-ad9a-42e7-9eee-d70407a8cd45">

小伙子，你确定核实过了框架文档和 issue 列表没有提过？
