### ISSUE TITLE
[疑惑]：get请求，如何把接收的参数回调成string

### ISSUE THREAD

**Issue by wuge2019** [getActivity/EasyHttp#247]
### 问题描述【必填】

请问大佬，像下图中的这种get请求，如何才能把接收的参数类型改成string
![image](https://github.com/getActivity/EasyHttp/assets/47548281/73f84b17-e66c-455e-b362-b24dcfe0ca28)

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

否

**Comment by getActivity** [comment]
小伙子，目前此 issue 打回，原因如下：

* 没有认真核实过文档是否提及过该问题

* 没有认真核实过 issue 列表是否提及过该问题

请重新提交 issue，并且严格按照 issue 模板填写
