### ISSUE TITLE
接口直接返回了一个音频文件，这个框架该怎么处理呢？

### ISSUE THREAD

**Issue by dxmwl** [getActivity/EasyHttp#249]
### 问题描述【必填】

后端提供的一个文字转语音的接口，直接返回了一个文件流，但是我看框架的文档中并没有相关说明，issue中也没有相关的问题，请问这边有相关的处理办法吗

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by dxmwl** [comment]
返回的是文件流，但是无法解析
![image](https://github.com/getActivity/EasyHttp/assets/173791785/0f68a1dd-d3e9-43aa-8c31-b6f1fcdbbb0e)

**Comment by dxmwl** [comment]
代码示例
` EasyHttp.post(this)
            .api(TextToSpeechApi().apply {
                message = "已成功记录"
            })
            .request(object :OnHttpListener<Any>{
                override fun onSucceed(result: Any?) {
                }

                override fun onFail(e: java.lang.Exception?) {
                    
                }

            })`

**Comment by dxmwl** [comment]
![image](https://github.com/getActivity/EasyHttp/assets/173791785/134c870d-2ac7-4f1a-8964-1a546dbdeff3)

**Comment by getActivity** [comment]
框架提供了文件下载功能，你为什么不用？

**Comment by dxmwl** [comment]
下载功能不是需要有下载地址才行吗？但是我们这边这个接口是传递文字等信息给后台的，没有对应的下载地址
![image](https://github.com/getActivity/EasyHttp/assets/173791785/e23f6106-9a80-4884-8ce2-f6718eb20760)

**Comment by CFSB** [comment]
可以协商一下让后台给你们一个下载地址

**Comment by dxmwl** [comment]
我尝试用download功能进行下载，但是下载的内容是这些，不确定这个内容是不是框架提示的
![image](https://github.com/getActivity/EasyHttp/assets/173791785/3028eb12-4ec4-4882-a5da-74b4859c860e)

**Comment by dxmwl** [comment]
查看这边提供的文档后，我不确定download是否能够这样传递参数
![image](https://github.com/getActivity/EasyHttp/assets/173791785/9b666d57-f2a8-43b1-b57f-e993cd132c61)

**Comment by getActivity** [comment]
@dxmwl 肯定是可以的，url 方法是 api 方法简写方式

**Comment by getActivity** [comment]
<img width="902" alt="image" src="https://github.com/getActivity/EasyHttp/assets/28616817/021468bf-4580-4b97-b387-da99e95d650d">

<img width="1028" alt="image" src="https://github.com/getActivity/EasyHttp/assets/28616817/b8cb603b-bff9-441a-855a-389ae416eae0">

<img width="1596" alt="image" src="https://github.com/getActivity/EasyHttp/assets/28616817/42f85cf5-e64c-4688-9c0f-27258c49a0fa">

**Comment by dxmwl** [comment]
我尝试打印相关信息，是存在的，但是放在接口请求时就没有了
![image](https://github.com/getActivity/EasyHttp/assets/173791785/e022554e-87d4-4b45-bd55-a14da8238863)

**Comment by getActivity** [comment]
@dxmwl 小伙子，我经过测试验证，并没有复现你所说的问题，我通过查看你的源码，判断你使用的框架版本是旧版本的，你直接升级到最新版本后再试，如果还是有这个问题，你直接编写一个 Demo 工程提供给到我进行复现。

**Comment by dxmwl** [comment]
确实是使用的旧版本的问题，我是使用的kotlin版的技术中台，里面很多框架是用的旧版本的

感谢轮子哥
