### ISSUE TITLE
[Bug]：java.lang.NoSuchMethodError: No direct method <init>(Ljava/util/Map;)V in class Lcom/google/gson/internal/ConstructorConstructor; or its super classes (declaration of 'com.google.gson.internal.ConstructorConstructor'

### ISSUE THREAD

**Issue by CFSB** [getActivity/EasyHttp#250]
### 框架版本【必填】

EasyHttp:10.2

### 问题描述【必填】

![bug](https://github.com/getActivity/EasyHttp/assets/40222362/fb09225a-5588-441c-bc8d-e252550a7931)

### 复现步骤【必填】

使用implementation 'com.google.code.gson:gson:2.10.1'时，报上述图片中的错误

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

31

### 出现问题的手机信息【必填】

小米10

### 出现问题的安卓版本【必填】

Android 12

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

所有

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 这个问题是 [GsonFactory](https://github.com/getActivity/GsonFactory) 框架问题，请前往该框架提 issue

请重新提一个 issue 并纠正以上问题
