### ISSUE TITLE
[疑惑]：发起get请求请求头的问题

### ISSUE THREAD

**Issue by wuge2019** [getActivity/EasyHttp#251]
### 问题描述【必填】

发起get请求的时候，访问的url自定义传入，但是我在框架的get请求自定义传入string类型url的相关方法没找到可以自定义请求头的地方，因为一个get方法涉及到了多个域名不确定和请求头不确定的操作，会在不同的地方调用到，我在文档内只找到了设置全局请求头的方法，请问大佬，这个应该怎么解决
![image](https://github.com/getActivity/EasyHttp/assets/47548281/dfc61075-77b3-4b93-88ba-c0e3069cea1a)
![image](https://github.com/getActivity/EasyHttp/assets/47548281/ed58440d-0510-4dc5-87f3-9f7fb0306227)

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by wuge2019** [comment]
已通过请求开始前添加全局请求头，请求结束删除请求头的方式解决

**Comment by getActivity** [comment]
如果你需要为某个请求添加请求头，那么则不能使用 url 的形式请求，而是应该用 api 的形式请求。
