### ISSUE TITLE
[疑惑]：轮子哥，请教下，要怎么在一个EasyHttp.download中配置新的OkHttpClient？

### ISSUE THREAD

**Issue by FanXH123** [getActivity/EasyHttp#258]
### 问题描述【必填】

我看了文档，里面有局部配置的方法，但是只在接口请求中生效，之前的版本也有.client(builder.build())局部配置的方法，但是现在没有这个方法了
![QQ截图20240809170851](https://github.com/user-attachments/assets/3e5db40c-b5f9-4a7a-9267-d325c80d0f41)

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by FanXH123** [comment]
![11111](https://github.com/user-attachments/assets/58c97402-1daa-4a5b-b1cd-a8479f846e04)
![2222](https://github.com/user-attachments/assets/8a6af403-e102-40d6-9c86-658dc7160cd6)

**Comment by getActivity** [comment]
<img width="762" alt="image" src="https://github.com/user-attachments/assets/61dba680-c385-485f-a601-7a6366697894">

**Comment by getActivity** [comment]
目前设置 OkHttpClient 只能在 api 类中实现 IRequestClient 接口，你照着这个写法配置一下。

**Comment by FanXH123** [comment]
> 目前设置 OkHttpClient 只能在 api 类中实现 IRequestClient 接口，你照着这个写法配置一下。

请教下，这个是只能下载源码修改吗，我看到DownloadRequest是在jar包中的类

**Comment by FanXH123** [comment]
是要创建一个api类实现 IRequestClient 接口吗，可能是我写的有问题，还是不会走配置的新的OkHttpClient 拦截器中，还是说要改源码的DownloadRequest类？
![1111](https://github.com/user-attachments/assets/cd14dd87-70c3-4eb0-b8bf-192f85c78cbe)
![2222](https://github.com/user-attachments/assets/a9e43e78-d5e7-4aef-a03d-edfc122c1bcd)

**Comment by getActivity** [comment]
你断点两个地方试一下，第一个是 DownloadApi 中的 getOkHttpClient 方法，第二个是 DownloadInterceptor 中的 intercept 方法看看走没有？

<img width="706" alt="image" src="https://github.com/user-attachments/assets/84d7e9ef-3b83-4695-8f64-7f4e008d54f8">

**Comment by getActivity** [comment]
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/09dcd45c-973e-4f94-950c-451467923523">

<img width="1680" alt="image" src="https://github.com/user-attachments/assets/fbcde512-1f3a-4b71-b5a3-1ab969fbc5c2">

**Comment by getActivity** [comment]
我自己测试是没有任何问题的，你看看是不是用了旧的框架版本导致的 Bug，如果用的是最新框架版本，这个问题大概率是你自己的问题，你先排查和定位一下。

**Comment by FanXH123** [comment]
可以了，感谢轮子哥
