### ISSUE TITLE
[建议]：EasyHttp.download(lifeCycle) .request(new OnHttpListener...)

### ISSUE THREAD

**Issue by actor20170211030627** [getActivity/EasyHttp#260]
### 你觉得框架有什么不足之处？【必答】

轮轮哥你好, 我又来给你提建议啦.

<b>建议1:</b> 当我们下载文件的时候, 还是能够调用到 .request 方法
<code>EasyHttp.download(lifeCycle)<s>.request(new OnHttpListener...)</s></code>, 我的建议是下载的时候屏蔽掉这个方法.
因为刚开始不熟练使用这个框架的时候, 如果不关心下载进度的话就会写.request , 然后就会崩溃...

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

**Comment by actor20170211030627** [comment]
嗯, 就像Retrofit的注解一样, 它的1个请求就有一个get/post 注解, 相当于1个请求就绑定死了请求方法.
<pre>
@GET("app/login/info")
suspend fun loginInfo(): BaseInfo&lt;Login?>
</pre>

**Comment by getActivity** [comment]
小伙子，我在代码抛异常是让你知道这样调用有问题，如果我不那么做，后续有问题排查成本会更高。
