### ISSUE TITLE
[疑惑]：用com.github.getActivity:EasyHttp:10.2这个库，来请求：这个https://test/delete这个url地址，请求方式是：DELETE请求，headers是"token":"961c",body是raw格式的json:[ "67ad" ],那么怎么写出这个请求的代码？

### ISSUE THREAD

**Issue by vance0901** [getActivity/EasyHttp#264]
### 问题描述【必填】

用com.github.getActivity:EasyHttp:10.2这个库，来请求：这个https://test/delete这个url地址，请求方式是：DELETE请求，headers是"token":"961c",body是raw格式的json:[ "67ad" ],那么怎么写出这个请求的代码？

### 框架文档是否提及了该问题【必答】

是

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
1. 升级框架到最新版本
2. 使用 EasyHttp.deleteByBody 进行请求
3. 自定义 ContentType 请求头

**Comment by vance0901** [comment]
弄好了，谢谢。
