### ISSUE TITLE
[疑惑]：请问我现在有个业务是多线程的下载视频，对下载的视频可以进行暂停和停止，但是我看demo里面没有暂停的业务

### ISSUE THREAD

**Issue by dd9000901** [getActivity/EasyHttp#265]
### 问题描述【必填】

[疑惑]：请问我现在有个业务是多线程的下载视频，对下载的视频可以进行暂停和停止，但是我看demo里面没有暂停的业务。请问怎么点击暂停后开始又进行断点续传。。谢谢，我只有取消下载~~没有看见暂停下载的方法

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
首先断点续传本质上需要服务器节点支持才可以，框架只是做了一些繁琐的处理，而不需要你自己手动处理，例如：1. 将文件断点的位置告诉服务器；2. 判断服务器是否支持断点续传；3. 续写之前下载过的文件。

从 Http 请求原理层面分析，断点续传本质不是真的能续传，Http 请求一旦断开，连接就不可能再继续，只能重新开始请求，所以框架内部并无提供暂停下载的 api，你如果要实现暂停然后继续下载的功能，在用户点击暂停下载的时候只能取消下载，在用户点击继续下载的时候需要重新发起下载请求，这个时候只要服务器本身就支持断点续传，重新下载的时候会跳过下载之前下载的文件部分内容，只下载之前没有下载文件的内容。

**Comment by dd9000901** [comment]
谢谢
