### ISSUE TITLE
post请求如何提交一个没有键的实体类

### ISSUE THREAD

**Issue by pigmakeup** [getActivity/EasyHttp#27]
EasyHttp 的post请求怎么给后台传一个实体类了，
![Uploading image.png…]()  
按照这种写法，
可以传，问题是是以键值对传的，现在不想要这个键，有什么办法吗

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/103598875-aaf9db00-4f3e-11eb-9d42-f543b03e9184.png)

**Comment by getActivity** [comment]
框架有扩展 API 出来的，但是我不推荐你那样写，那种写法本身就是不规范的，并且扩展性极差

**Comment by yangqb** [comment]
怎么操作啊，我们也有这个需求

**Comment by getActivity** [comment]
@yangqb 你用的是 json 还是表单提交？

**Comment by yangqb** [comment]
> @yangqb你用的是json还是表单提交？

我弄的json,框架自动转成表单了，自定义requestbody就解决了

**Comment by getActivity** [comment]
https://github.com/getActivity/EasyHttp/blob/master/HelpDoc.md

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/103611093-814fac80-4f5c-11eb-91f1-5a010b3c61e5.png)

**Comment by getActivity** [comment]
框架是可以自动帮你转换的，你只需要这样配置。

**Comment by getActivity** [comment]
@pigmakeup 不带 key 的参数你可以这样写
![](https://user-images.githubusercontent.com/28616817/103611464-51ed6f80-4f5d-11eb-9106-c056a23e1141.png)

**Comment by pigmakeup** [comment]
明白了，谢谢

**Comment by powermax-yangtao** [comment]
@HttpRenme("")这种方式请求，请求体中参数格式( "" = keyword )，还是无法满足不带键值的需求呀，还有其它简单方式吗？
