### ISSUE TITLE
@HttpIgnore这个注解功能缺失

### ISSUE THREAD

**Issue by zhehen1231** [getActivity/EasyHttp#30]
添加个参数指定字段名吧
如果参数叫access-token就没法用了

**Comment by getActivity** [comment]
小伙子，我没明白你的意思，你是遇到什么问题了？

**Comment by getActivity** [comment]
你可能有些理解错误，@HttpIgnore 这个注解是忽略参数的意思，而你的意思应该是，Java 的命名不能带横杆，但是你可以用 @HttpRename 注解。

**Comment by getActivity** [comment]
如果没有什么问题我就关闭 issue 了，如果还有疑问或者不懂欢迎再打开此 issue。
