### ISSUE TITLE
一些看法

### ISSUE THREAD

**Issue by daiwj** [getActivity/EasyHttp#35]
你说Retrofit的一些缺点，我是认同的。但是你说的维护性其实是不认同的。
一，Retrofit不支持动态参数修改是个败笔，但是一个接口一个类的时代已经过去了，真的不建议再弄回来。与其造轮子，不如写个类似Retrofit的库，开放出动态修改参数这样的功能即可。
二，下载的功能着实有些鸡肋，没有贬低的意思，网络请求就好好做网络请求就好了。

**Comment by getActivity** [comment]
小伙子，Retrofit 在维护性上我打中等分是有理有据的，例如所有参数都放在同一个方法里面，这样后面加参数需要改所有调用的地方，还有项目中常常会将很多接口放在同一个类里面，即使它们不属于同一模块，有的甚至将整个项目所有的接口放在一个类里面，导致接口类膨胀和臃肿。

**Comment by getActivity** [comment]
小伙子，下载功能哪里做得不够好你可以提，光吐槽解决不了问题，你说不行那我怎么知道哪里不行？

**Comment by daiwj** [comment]
> 小伙子，Retrofit 在维护性上我打中等分是有理有据的，例如所有参数都放在同一个方法里面，这样后面加参数需要改所有调用的地方，还有项目中常常会将很多接口放在同一个类里面，即使它们不属于同一模块，有的甚至将整个项目所有的接口放在一个类里面，导致接口类膨胀和臃肿。

 Retroft的维护性 是可以认可的，并不需要你打中等分，Retrofit最大的缺点是它太局限于注解的使用而已，像你说的却是动态化的配置，比如 url，param等，但这个需求场景其实并不多。其次你的库真的没有任何优势（其实是没什么亮点），下载功能为什么说鸡肋，因为做下载的比你下载做的强，做请求的比你的思想要前卫。你所说的 很多接口放到同一个类，那是使用者的问题，不是库的问题。

**Comment by daiwj** [comment]
> 小伙子，下载功能哪里做得不够好你可以提，光吐槽解决不了问题，你说不行那我怎么知道哪里不行？

其实现在很少有上传自己服务器的操作，都是云服务器，下载涉及的面很广，再高级一点的下载，前后台的下载体验，同步等等，这些操作 并不是一个网络库可以或者应该提供的，所以说你的亮点，上传下载功能呢，不说代码写的怎么样（我也没仔细看），却是很鸡肋。

**Comment by getActivity** [comment]
小伙子，你要是不认可框架的设计思想，可以不用，这个我没有强制，但我从你的吐槽中没有得到什么有用的东西，例如哪个功能的哪个细节做得不到位，我并没有听到这些东西。

**Comment by daiwj** [comment]
没有针对你的库，而是针对你你贬低Retrofit的维护性而夸大其谈你的库有多么好的观点，我觉得不止我一个人觉得一个接口一个类才是更差的维护性吧，如果造轮子，请结合点有用的东西，不要为了造轮子而造轮子。

**Comment by daiwj** [comment]
最后说一句吧，如果不是很喜欢我这么直接的看法，烦请close掉吧。抱歉～

**Comment by getActivity** [comment]
你如果讨厌一个接口写一个类，你可以这样写：
```java
EasyHttp.post(this)
        .api("article/query/0/json")
        .request(new HttpCallback<HttpData<SearchBean>>(this) {

            @Override
            public void onSucceed(HttpData<SearchBean> result) {
               
            }
        });
```
框架本身就是很人性化的

**Comment by getActivity** [comment]
一个接口设计成一个类是有目的的，你可以在类中通过实现 IRequestHost 接口来重新指定服务器地址，实现 IRequestType 接口可以重写指定接口的提交方式（表单还是 json）

**Comment by daiwj** [comment]
还有比 一个注解 就解决的 方式 更简单的吗？

**Comment by daiwj** [comment]
> 你如果讨厌一个接口写一个类，你可以这样写：
> 
> ```java
> EasyHttp.post(this)
>         .api("article/query/0/json")
>         .request(new HttpCallback<HttpData<SearchBean>>(this) {
> 
>             @Override
>             public void onSucceed(HttpData<SearchBean> result) {
>                
>             }
>         });
> ```
> 
> 框架本身就是很人性化的

业务的内聚性 你抛弃了，Retrofit的最大优点 直接给你弄没了，人才！

**Comment by palorotolo** [comment]
太难用了，写参数要写一堆模板代码。
