### ISSUE TITLE
返回数据拦截判断?

### ISSUE THREAD

**Issue by heyingjie** [getActivity/EasyHttp#37]
请问可以对返回的数据进行拦截判断吗，比如返回的JSON数据中Code字段判断到指定的值，就当错误处理，产生onFail回调。

**Comment by getActivity** [comment]
可以的，小伙子，具体实现可以参考一下：https://github.com/getActivity/EasyHttp/blob/master/app/src/main/java/com/hjq/easy/demo/http/model/RequestHandler.java

**Comment by getActivity** [comment]
你只需要在 requestSucceed 方法中抛出异常，那么就会走到 requestFail 方法，到时候就会回调 onFail 方法。

**Comment by heyingjie** [comment]
好的，谢谢
