### ISSUE TITLE
一个功能问题，一个设计问题

### ISSUE THREAD

**Issue by Skqing** [getActivity/EasyHttp#39]
1. 请求加密问题
比如我们的APP请求都是对内容加密的，目前的方案是在intercept做加密，在RequestHandler的success和fail里面做解密，但总感觉不太合适，能否提供一个方法，这个方法是在success和fail的前面调用的，我们可以在这里做统一的解密

2. 拦截器设计问题
登录问题，目前只看到在返回的时候判断返回的code里面的值判断是否是未登录状态。但实际上更好的办法是在客户端请求的时候就应该先判断本地token是否存在或者是否过期，如果不存在或者过期直接回调不用请求服务端。这个token判断是否过期用户可以放到intercept里面自己判断，另外IRequestApi应该提供或者用户自己定义一个注解，标识此接口是否需要登录才能调用，这些都可以在拦截器里实现。但目前拦截器的实现只是添加参数，拦截器的本质没有体现出来，就是不符合的请求要能在客户端拦截掉不需要请求服务端了。所以建议拦截器的方法里支持返回boolean，用户根据业务判断后如果需要继续请求就返回true，如果不需要继续请求而是直接回调结束那就返回false。

以上就是个人的使用体会，作者可以考虑一下。

**Comment by Skqing** [comment]
对于token失效的回调，支持写入回调内容，方便在回调里判断用户是否登录

**Comment by getActivity** [comment]
小伙子，第一个建议我表示理解，因为我在框架设计上可能没有考虑接口加密解密这块的细节，所以在下个版本我会在加上这块的功能，在 IRequestHandler 接口中添加 requestStart 方法，返回 Request 对象，以便进行请求前加密。

**Comment by getActivity** [comment]
但是第二个建议我表示有一些疑问，Token 过没过期不应该由后台控制的？这种操作我认为应该放在后台会更好，不应该放在客户端。当然你有这种需求我也表示理解，但是截止目前只有你一个人提出了这种建议，又或者你可以提出更有说服力的理由，否则我可能没办法采纳这个建议。

**Comment by Skqing** [comment]
第二个是这样的，我们生成的token在服务端是有失效时间的，在客户端也有保存并且也有失效时间，并且客户端的失效时间会比服务端的短一点，所以才会有我说的需求，不过可能大部分不会这样做吧，另外这个问题影响不大。关于第一个需求还行考虑一下，另外多谢回复！

**Comment by getActivity** [comment]
小伙子，第一个建议已采纳，框架已经更新了，你可以更新一下。

**Comment by getActivity** [comment]
小伙子，还有其他的问题或者建议不，没有的话我就关闭 issue 了
