### ISSUE TITLE
Socket 快速连接

### ISSUE THREAD

**Issue by dahui888** [getActivity/EasyHttp#40]
可以增加一个实现 WebSocket 请求连接的封装工具类吗，用于快速实现 WebSocket 请求连接。选择性导入包的。Socket太麻烦了

**Comment by getActivity** [comment]
小伙子，这个框架是针对 Http 请求的，如果你想用 WebSocket 的话，建议你用另外一套框架比较好。因为 Http 是短连接，而 WebSocket 是长连接，两者很难融合在一套框架上。

**Comment by chenjim** [comment]
okhttp 支持 websocket，EasyHttp 基于 okhttp 封装，可以直接用okhttp api 连接 websocket，可参考如下
  
```kotlin
val url: String = "ws://192.168.31.234:8214/mySocket"
val request = Request.Builder().url(url).build()
val client = EasyConfig.getInstance().client
client.newWebSocket(request, WebSocketListenerImp())
```

如果需要复用header 、cookie，需要在 EasyConfig 初始化时将 OkHttpClient 单独加拦截器
