### ISSUE TITLE
有接口请求的缓存功能吗？

### ISSUE THREAD

**Issue by chenhao1041661180** [getActivity/EasyHttp#43]

**Comment by AdminQQZ** [comment]
我也需要

**Comment by dahui888** [comment]
> _No description provided._

我暂时用的本地数据库实现的缓存,你可以先替换用着

**Comment by 704480904** [comment]
想请教下两个问题
1.这个放在后台服务中会 譬如定时每隔一个小时请求一次  会出现cookie 不上传的问题
2.想问下这个cookie的header 为啥没有打印出来，我应该改哪个地方 ，现在不确定是服务器没收到我传上去的cookie还是我没有传上去 只有一个后台服务器的接口偶偶会出现这种问题

**Comment by getActivity** [comment]
@704480904 小伙子，我来逐一回答你的问题

1. 只要你在 OkHttpClient 初始化的时候有设置 Cookie，那么请求是一定会携带的
2. Cookie 为什么没有打印的问题，目前框架只打印当前 Api 类的字段，如果你要打印请求的所有参数，请添加 OkHttp 拦截器进行打印

**Comment by 704480904** [comment]
实现了，在RequestHandler 的onSuccess 中添加了



但是有几次后台service请求，没有发送cookie上去就很奇怪了，而且都是手机处于不活跃的状态，就是大半夜的时候出现的，因为我们的app 需要每小时用后台service上传一次数据，有几次都调用失败了，如果cookie没设置进去的话，应该是所有调用这个接口都会失败的，不知道是不是生命周期管理的问题导致的，但是也不应该啊，神隐模式要么就直接断网了，不会再返回token 失效的状态码了，直接都到不了服务器，我先添加日志，到时候明天再看看这个问题，今天问了后台，说我那个session是没有过期的，过期时间是七天，如果今天再没出现就不管了，如果出现了，就下载你的代码下来自己改吧，






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "getActivity/EasyHttp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月21日(星期三) 下午4:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [getActivity/EasyHttp] 有接口请求的缓存功能吗？ (#43)



 @704480904 小伙子，我来逐一回答你的问题
  只要你在 OkHttpClient 初始化的时候有设置 Cookie，那么请求是一定会携带的
 Cookie 为什么没有打印的问题，目前框架只打印当前 Api 类的字段，如果你要打印请求的所有参数，请添加 OkHttp 拦截器进行打印

**Comment by 704480904** [comment]
RequestHandler 的onSuccess 添加可以打印出来了 
 Headers headersRequest = response.request().headers();
        if (headersRequest!=null) {
            for (String name : headersRequest.names()) {
                if (TextUtils.equals(name,"Cookie") ||TextUtils.equals(name,"cookie")){
                    XLog.d("请求Cookie:" + name + "=" + headersRequest.values(name).toString());
                    EasyLog.print("请求Cookie:" + name, headersRequest.values(name).toString());
                }
            }
            if (headersRequest.names().contains("Cookie")||headersRequest.names().contains("cookie")) {
                XLog.e("出现了请求不带cookie"+response.request().url().toString());
            }
        }

**Comment by getActivity** [comment]
@chenhao1041661180 @AdminQQZ @dahui888 小伙子，接口缓存功能已经做好了，欢迎你们来做第一批内测用户。

**Comment by getActivity** [comment]
[EasyHttp-10.0.zip](https://github.com/getActivity/EasyHttp/files/6972650/EasyHttp-10.0.zip)

**Comment by getActivity** [comment]
#### 请求缓存

* 需要先实现读取和写入缓存的接口，如果已配置则可以跳过，这里以 MMKV 为例

```java
public final class RequestHandler implements IRequestHandler {

    private final Application mApplication;
    private final MMKV mMmkv;

    public RequestHandler(Application application) {
        mApplication = application;
        mMmkv = MMKV.mmkvWithID("http_cache_id");
    }
    
    ..................

    @Override
    public Object readCache(LifecycleOwner lifecycle, IRequestApi api, Type type) {
        String cacheKey = GsonFactory.getSingletonGson().toJson(api);
        String cacheValue = mMmkv.getString(cacheKey, null);
        if (cacheValue == null || "".equals(cacheValue) || "{}".equals(cacheValue)) {
            return null;
        }
        EasyLog.print("---------- cacheKey ----------");
        EasyLog.json(cacheKey);
        EasyLog.print("---------- cacheValue ----------");
        EasyLog.json(cacheValue);
        return GsonFactory.getSingletonGson().fromJson(cacheValue, type);
    }

    @Override
    public boolean writeCache(LifecycleOwner lifecycle, IRequestApi api, Response response, Object result) {
        String cacheKey = GsonFactory.getSingletonGson().toJson(api);
        String cacheValue = GsonFactory.getSingletonGson().toJson(result);
        if (cacheValue == null || "".equals(cacheValue) || "{}".equals(cacheValue)) {
            return false;
        }
        EasyLog.print("---------- cacheKey ----------");
        EasyLog.json(cacheKey);
        EasyLog.print("---------- cacheValue ----------");
        EasyLog.json(cacheValue);
        return mMmkv.putString(cacheKey, cacheValue).commit();
    }
}
```

* 首先请求缓存模式有四种方式，都在 `CacheMode` 这个枚举类中

```java
public enum CacheMode {

    /**
     * 默认（按照 Http 协议来缓存）
     */
    DEFAULT,

    /**
     * 不使用缓存（禁用 Http 协议缓存）
     */
    NO_CACHE,

    /**
     * 只使用缓存
     *
     * 有缓存的情况下：读取缓存 -> 回调成功
     * 无缓存的情况下：请求网络 -> 写入缓存 -> 回调成功
     */
    USE_CACHE_ONLY,

    /**
     * 优先使用缓存
     *
     * 有缓存的情况下：先读缓存 —> 回调成功 —> 请求网络 —> 刷新缓存
     * 无缓存的情况下：请求网络 -> 写入缓存 -> 回调成功
     */
    USE_CACHE_FIRST,

    /**
     * 只在请求失败才去读缓存
     */
    USE_CACHE_AFTER_FAILURE
}
```

* 为某个接口设置缓存模式

```java
public final class XxxApi implements IRequestApi, IRequestCache {

    @Override
    public String getApi() {
        return "xxx/";
    }

    @Override
    public CacheMode getMode() {
        // 设置优先使用缓存
        return CacheMode.USE_CACHE_FIRST;
    }
}
```

* 全局设置缓存模式

```java
public class XxxServer implements IRequestServer {

    @Override
    public String getHost() {
        return "https://www.xxxxxxx.com/";
    }

    @Override
    public CacheMode getMode() {
        // 只在请求失败才去读缓存
        return CacheMode.USE_CACHE_AFTER_FAILURE;
    }
}
```

**Comment by 704480904** [comment]
那天我又遇到那个用多线程上传上百个zip 的时候，总是会出现

**Comment by 704480904** [comment]
https://blog.csdn.net/u012587005/article/details/78504925  java.lang.IllegalStateException: closed 这个错误，有说是Android studio ASM插装字节码导致 有说是因为  https://blog.csdn.net/zhangteng22/article/details/52233126 好像需要自定义上传的UploadRequestBody

**Comment by getActivity** [comment]
@704480904 小伙子，你先确定一下这个问题是不是只在 debug 包下才会出现？看看 release 包有没有这个问题？

**Comment by 704480904** [comment]
release包也出现了，不然我就不会去改这个bug 了，

上传的数据出现少了几份，譬如上传100份zip  ，服务器看了下只有99份,我看了日志，就是那个IllegalStateException: closed   什么的错误

**Comment by getActivity** [comment]
@704480904 小伙子，我自己的话没有遇到这个问题，别人也没有反馈过类似的问题，所以只能靠你自己排查了，如果是框架导致的问题再反馈给我，我再给你做处理。

**Comment by getActivity** [comment]
小伙子，远程依赖已经更新，你可以更新到最新版本体验接口缓存功能。
