### ISSUE TITLE
isBeanType对Null的判断问题

### ISSUE THREAD

**Issue by Skqing** [getActivity/EasyHttp#44]
```
    /**
     * 判断对象是否为 Bean 类
     */
    public static boolean isBeanType(Object object) {
        // Number：Long、Integer、Short、Double、Float、Byte
        // CharSequence：String、StringBuilder、StringBuilder
        return !(object instanceof Number || object instanceof CharSequence ||
                object instanceof Boolean || object instanceof File ||
                object instanceof InputStream || object instanceof RequestBody ||
                object instanceof Character || object instanceof JSONObject ||
                object instanceof JSONArray);
    }
```
这里如果传过来的参数是空也认为是对象，但实际上有时候是封装类型，只不过值为空而已。
所以当参数结构如下时：
```
public class XXApi implements IRequestApi, Serializable {
    private String name;
    private Map<String, Object> params;
```
如果往params里面添加一个值为null的属性时提交请求会报错。
异常代码：
```
case JSON:
                        if (value instanceof List) {
                            // 如果这是一个 List 参数
                            params.put(key, EasyUtils.listToJsonArray(((List<?>) value)));
                        } else if (value instanceof Map) {
                            // 如果这是一个 Map 参数
                            params.put(key, EasyUtils.mapToJsonObject(((Map<?, ?>) value)));
                        } else if (EasyUtils.isBeanType(value)) {
                            // 如果这是一个 Bean 参数
                            params.put(key, EasyUtils.mapToJsonObject(EasyUtils.beanToHashMap(value)));
                        } else {
                            // 如果这是一个普通的参数
                            params.put(key, value);
                        }
                        break;
                    default:
```
由于isBeanType的判断错误导致调用了beanToHashMap，而此时的value是null，所以就异常了。

**Comment by getActivity** [comment]
```java
// 前提是这个字段值不能为空（基本数据类型有默认的值，而对象默认的值为 null）
if (EasyUtils.isEmpty(value)) {
    // 遍历下一个字段
    continue;
}
```

**Comment by getActivity** [comment]
小伙子，你的假设不成立，value 值永远不可能为空

**Comment by getActivity** [comment]
如果你这边在实际开发中有遇到报错的话，麻烦发一下报错的堆栈给我。

**Comment by Skqing** [comment]
是不是我没说清楚呢，我的意思不是private Map<String, Object> params = null;
而是
private Map<String, Object> params = new HashMap();
params.put("name", null);
这种情况下，会报空指针异常
params.put("name", "张三");
这种情况不会

**Comment by Skqing** [comment]
AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxx.sss, PID: 4633
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at com.hjq.http.EasyUtils.beanToHashMap(EasyUtils.java:259)
        at com.hjq.http.EasyUtils.mapToJsonObject(EasyUtils.java:241)
        at com.hjq.http.request.BaseRequest.createCall(BaseRequest.java:273)
        at com.hjq.http.request.BaseRequest.lambda$request$0$BaseRequest(BaseRequest.java:314)
        at com.hjq.http.request.-$$Lambda$BaseRequest$FJCESaX9RFKrH0DJLNTxr4jKczA.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:7876)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by getActivity** [comment]
[easyhttp-9.5.aar.zip](https://github.com/getActivity/EasyHttp/files/6348416/easyhttp-9.5.aar.zip)

**Comment by getActivity** [comment]
@Skqing 经过核实，确实存在这个问题，问题已经纠正，多谢小伙子的提醒。

**Comment by getActivity** [comment]
由于问题影响范围比较小，会在下个版本更新上去，小伙子你如果着急用的话，可以用这个包作为本地依赖。

**Comment by Skqing** [comment]
好的，多谢！
