### ISSUE TITLE
混淆问题

### ISSUE THREAD

**Issue by vistar1986** [getActivity/EasyHttp#45]
能否详细说说怎么进行混淆，按照DEMO上的混淆规则打包后无法正常使用框架，但是程序没有闪退

**Comment by vistar1986** [comment]
![image](https://user-images.githubusercontent.com/11677770/115989056-f23fd080-a5ee-11eb-9c2e-abf025f18f8c.png)

**Comment by getActivity** [comment]
小伙子，无法使用框架是什么表现？

**Comment by getActivity** [comment]
小伙子，我在 Demo 中使用了代码混淆，并没有发现任何异常情况，都是可以正常请求的，你用 Demo 开启混淆模式试试看有没有这个问题。

**Comment by vistar1986** [comment]
你好，刚刚我用DEMO开启混淆模式看了，混淆后网络请求没有带参数，但是不开启混淆是带参数的

**Comment by vistar1986** [comment]
![1619399128(1)](https://user-images.githubusercontent.com/11677770/116016257-acc2e800-a66e-11eb-9031-88a0e2f70513.png)

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/116023633-177c1f80-a67f-11eb-8153-8d155b79c569.png)

**Comment by getActivity** [comment]
小伙子，我咋没有这个问题呢？你的 RequestApi 类是怎么写的？

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/116023811-80fc2e00-a67f-11eb-88cb-f94affd0e9bd.png)

**Comment by getActivity** [comment]
我把请求参数类型改成了 Json 提交，也是没有这个问题的呢

**Comment by vistar1986** [comment]
你好，我这边把混淆规则改了一下就可以了，DEMO中使用-keepclassmembernames，项目中改成-keep

**Comment by vistar1986** [comment]
![Uploading image.png…]()

**Comment by vistar1986** [comment]
![image](https://user-images.githubusercontent.com/11677770/116038434-0392e680-a69c-11eb-91d3-2d35d93b2efc.png)

**Comment by vistar1986** [comment]
![image](https://user-images.githubusercontent.com/11677770/116038552-2c1ae080-a69c-11eb-9979-25d67f2bfe49.png)
这是我的RequestApi

**Comment by getActivity** [comment]
解决了就 OK
