### ISSUE TITLE
在服务里面不调用接口

### ISSUE THREAD

**Issue by kunjingzhu** [getActivity/EasyHttp#47]
服务继承LifecycleService，不调用接口，也不报错
![image](https://user-images.githubusercontent.com/10395233/118078809-7d8bd500-b3e9-11eb-8d78-6af863a802a7.png)

**Comment by getActivity** [comment]
小伙子，你把 HttpCallback 换成 OnHttpListener 试试看

**Comment by kunjingzhu** [comment]
搞定了，谢谢。

**Comment by getActivity** [comment]
ok，解决了就好。
