### ISSUE TITLE
ViewModel里面怎么使用 框架请求

### ISSUE THREAD

**Issue by zj4074305** [getActivity/EasyHttp#53]
我看没有结合ViewModel使用的例子，ViewModel传入 LifecycleOwner 会引起内存泄漏怎么解决呢

**Comment by getActivity** [comment]
你可以考虑封装一个 BaseViewModel，并且实现 LifecycleOwner 接口，在 ViewModel.clear 方法中手动派发 destroy 事件。

**Comment by getActivity** [comment]
小伙子，你这边还有其他问题不？没有的话我就关闭 issue 了。
