### ISSUE TITLE
阿里云日志上传接口及返回数据

### ISSUE THREAD

**Issue by xuqinghao1991** [getActivity/EasyHttp#55]
你好,大佬,请问下我这有个需求是 阿里云要上传日志
日志内容包含:1.接口;2.请求头3:所有参数;4:接口返回数据(接口请求错误,接口请求失败错误码,接口请求正常数据)
请问现在有开放这个吗
![QQ截图20210721110033](https://user-images.githubusercontent.com/32887962/126423940-862e9a78-7146-45e2-a3f4-f7ddf8253475.png)

**Comment by getActivity** [comment]
小伙子，你看看 IRequestHandler 这个类是否能满足你的需求？

**Comment by xuqinghao1991** [comment]
> 小伙子，你看看 IRequestHandler 这个类是否能满足你的需求？
Object requestSucceed 在这个方法里基本可以满足
 Exception requestFail 这个方法里就无法获取了

**Comment by getActivity** [comment]
小伙子，在 requestSucceed 方法中抛异常会回调到 requestFail 方法中，你懂我的意思吧？

**Comment by xuqinghao1991** [comment]
> 小伙子，在 requestSucceed 方法中抛异常会回调到 requestFail 方法中，你懂我的意思吧？
好的,明白了,感谢

**Comment by getActivity** [comment]
OK 的，小伙子，你看看还有别的问题不，没有的话我就关闭 issue 了。

**Comment by xuqinghao1991** [comment]
> OK 的，小伙子，你看看还有别的问题不，没有的话我就关闭 issue 了。

没了,谢谢
