### ISSUE TITLE
javax.net.ssl.SSLException cannot be cast to com.hjq.http.exception.CancelException

### ISSUE THREAD

**Issue by 704480904** [getActivity/EasyHttp#56]
javax.net.ssl.SSLException cannot be cast to com.hjq.http.exception.CancelException

调用接口上传zip 的时候偶偶会出现这个异常导致异常上传失败，其他接口正常，这个上传zip 压缩包的接口 有时候会抛这个错误

**Comment by getActivity** [comment]
小伙子，麻烦提供一下堆栈信息

**Comment by 704480904** [comment]
# main(2)

java.lang.ClassCastException
javax.net.ssl.SSLException cannot be cast to com.hjq.http.exception.CancelException
com.ibiliang.deepeye.server.AlarmService$7.onFail(AlarmService.java:808)
com.hjq.http.callback.NormalCallback.lambda$onFailure$2(NormalCallback.java:67)
com.hjq.http.callback.-$$Lambda$NormalCallback$h1TlVh6XaCMpx-pe_FC7Nnd3OAM.run(Unknown Source:4)
android.os.Handler.handleCallback(Handler.java:914)
android.os.Handler.dispatchMessage(Handler.java:100)
android.os.Looper.loop(Looper.java:225)
android.app.ActivityThread.main(ActivityThread.java:7563)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)

这个是bugly 收到的日志

想问下有个单独的接口，服务器地址跟全局配置的servier 地址不一样，想问下怎么请求比较优雅？

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/126609348-f2ede6fa-3fec-45a8-a327-8f5420659775.png)

**Comment by getActivity** [comment]
小伙子，这是你的代码写得有问题吧？

**Comment by 704480904** [comment]
![image](https://user-images.githubusercontent.com/6984303/126611057-c5c32372-4e71-41ce-98de-e40a35bfec96.png)
我在失败的地方判断了类型啊

还有个问题想请教下 怎么 一个临时的http 请求地址 ，我应该怎么配置，我发现配置之后
![image](https://user-images.githubusercontent.com/6984303/126611255-6778acf3-895f-47ea-bf93-207d078c00cc.png)
所有的请求都变成了UIAutomator

**Comment by getActivity** [comment]
小伙子，这两个问题我逐一回答
1. 如果你要是判断了类型再强转的，还会出现崩溃，这个我就不知道是什么原因导致的，但是至少有一点可以肯定，这个不是框架导致的，因为堆栈指向是你的项目代码，这个需要你自行处理。
2. 第二个问题，关于如何修改接口的服务器配置的问题，我文档上面有写的，你可以点击[此处查看框架文档](https://github.com/getActivity/EasyHttp/blob/master/HelpDoc.md)。

**Comment by getActivity** [comment]
小伙子，你还有别的问题不，没有的话我就关闭 issue 了。

**Comment by 704480904** [comment]
![image](https://user-images.githubusercontent.com/6984303/126754650-4dc014f1-a5e2-49cf-840d-dd1e7b844c03.png)
我在这地方拦截打印cookie， 好像拦截不到cookie 其他的都拦截到了，这个拦截器我看了下，好像只能设置一个是么?

**Comment by getActivity** [comment]
@704480904 小伙子，这个拦截器肯定是拦截不到 Cookie 的，因为 Cookie 是在 OkHttp 的桥接拦截器中添加的，这个拦截器只是用来做添加全局动态的，你如果要打印 Cookie 参数只能用 OkHttp 自带的那个拦截器。

**Comment by getActivity** [comment]
@704480904 你看看你这边还有别的疑问不？

**Comment by 704480904** [comment]
只能用抓包工具来看了Charles 或者WireShark 了

![image](https://user-images.githubusercontent.com/6984303/126763991-ebbb8a99-4aa7-415f-b893-d05710ff8c82.png)

我写在这个地方，然后配置进OkHttp的client 里面去，好像也还是拦截不到

我用的PersistentCookieStore  在内存卡上面也有这个cookie了，但是就是有部分接口没有调用传上去cookie 导致服务器返回失效了，算了， 你把issue 关掉算了，他又不是全不行，只有其中1-2个接口 ，偶偶出现没有上传上去cookie

**Comment by getActivity** [comment]
@704480904 好的，小伙子，后续有问题欢迎你再联系我
