### ISSUE TITLE
如何在 ViewModel 中发起请求，不传递上下文 Context？

### ISSUE THREAD

**Issue by thisfeng** [getActivity/EasyHttp#57]
是这样的，ViewModel 本身不建议传递 Context ，但如果有些场景下需要在ViewModel 中发起一个请求。
使用 该苦 EasyHttp.post(this) 参数能否不使用 上下文 this。就直接可以 发起一个请求 并处理呢？
好像和该库设计理念有点相违背？

**Comment by getActivity** [comment]
小伙子，最新版 EasyHttp 传入的参数已经不是 Context 类型了，而是传入 LifecycleOwner 参数类型。

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by thisfeng** [comment]
哈哈 谢谢，我再研究研究。
