### ISSUE TITLE
是否支持直接传递实体类作为参数

### ISSUE THREAD

**Issue by ymwm-lxl** [getActivity/EasyHttp#58]
场景：拉取到详情数据之后取消订单接口需要把详情数据的所有内容修改单个字段之后作为参数上传。
需求：希望能够把接收到的实体类能够直接放进api里面提交，现在使用的方式是一个一个字段重新复制之后提交

**Comment by getActivity** [comment]
小伙子，你直接把 API 类作为 Bean 类接收不就可以了？就是你把请求响应的 Bean 类型改成 API 类型，这样你直接拿 Bean 对象当 API 对象用就可以了。

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。
