### ISSUE TITLE
Token 失效之后获取新token 之后是否能够有办法重新调用一下原来的接口

### ISSUE THREAD

**Issue by ymwm-lxl** [getActivity/EasyHttp#59]
我们在 Token 获取的时候，同时会获取一个过期时间较晚的 ReToken，当Token 过期后会使用 ReToken 重新获取Token，希望能够重新获取Token之后继续网络请求，就不知道该怎么做了。

**Comment by getActivity** [comment]
小伙子，框架暂不支持这种方式，你可能需要用 OkHttp 的拦截器来实现这一需求。

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by 704480904** [comment]
你这个鞋一个    HttpTokenInterceptor implements Interceptor  就可以实现了 在返回值里面判断http Code  服务器假设返回10086 为token失效，然后你从本地缓存里面拿到那个LongToken(你就是你的reToken)  同步请求一下获取token的接口  ，然后再继续请求你的http 接口请求就行了

 //根据和服务端的约定判断token过期
        if (isTokenExpired(response)) {
            XLog.d("session 过期 自动刷新session,然后重新请求数据");
            //同步请求方式，获取最新的Token
            String newToken = getNewToken();
            XLog.d("newToken:" + newToken);
            //使用新的Token，创建新的请求
            Request newRequest = chain.request()
                    .newBuilder()
                    .header("Cookie", newToken)
                    .build();
            //重新请求
            return chain.proceed(newRequest);
        }

大致上是这样
