### ISSUE TITLE
okhttp 频繁请求IOException

### ISSUE THREAD

**Issue by 704480904** [getActivity/EasyHttp#60]
想请教下okhttp 频繁请求的时候 出现IOException   Android OkHttp IOException unexpected end of stream异常处理方式  

https://www.jianshu.com/p/e18c0a13b194

跟这个报错的日志差不多 ，说是需要添加head Connection close ，我在implements IRequestApi  的类上面添加 @HttpHeader
    private String Connection  ，因为好像http 会默认添加connection 为keep alive 的头，想问下能否覆盖原keep-alive 的头，传输到服务器是close 还是keep-alive 因为这个头是保留值

**Comment by getActivity** [comment]
小伙子，你设置 OkHttp 的拦截器不就可以实现了么？

**Comment by 704480904** [comment]
但是部分接口需要keep-alive  除了轮询那个接口是设置close的 ，我在HttpHeaderInterceptor implements IRequestInterceptor  的interceptArguments 方法中判断算了，增加api.getApi()  判断请求的path 来添加算了，刚刚试了下，看了日志是可行的的，希望这个IOException 的问题能解决，脑仁疼，这种底层的问题

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by 704480904** [comment]
暂时没有了，多谢解答
