### ISSUE TITLE
请求结果实体类为什么时间类型的属性不能用date只能用string

### ISSUE THREAD

**Issue by sdjwj1118** [getActivity/EasyHttp#64]
如题

**Comment by getActivity** [comment]
小伙子，我想你应该是搞错了，EasyHttp 不负责数据的解析工作，你这个问题应该到 [Gson](https://github.com/google/gson) 上面去提问。

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by sdjwj1118** [comment]
没了 我自行处理下
