### ISSUE TITLE
使用同步请求方法报错

### ISSUE THREAD

**Issue by sdjwj1118** [getActivity/EasyHttp#65]
![1633333336(1)](https://user-images.githubusercontent.com/33438073/135812673-78c74003-b52e-4d11-877c-1ff33f0c066f.jpg)
![1633333344(1)](https://user-images.githubusercontent.com/33438073/135812687-7ce37188-c013-4994-baf7-3585f1f3221a.jpg)

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/135875258-bce810f6-901f-4125-9098-a69f94ace947.png)

**Comment by getActivity** [comment]
小伙子，mRequestHandler 对象是不可能为空的，请自行排查一下 mRequestHandler 对象为什么会为空的原因。

**Comment by sdjwj1118** [comment]
不是mRequestHandler为空 是执行这句代码的时候Response response = mCallProxy.execute();抛出了android.os.NetworkOnMainThreadException异常

**Comment by getActivity** [comment]
小伙子，同步请求是耗时操作，耗时操作不能在主线程中直接执行，这个异常怎么解决应该不用我多说了吧？

**Comment by CodeK1988** [comment]
协程同步code不为200后 不返回httpdata

**Comment by getActivity** [comment]
<img width="1092" alt="image" src="https://github.com/getActivity/EasyHttp/assets/28616817/20be73ab-a616-4af7-923f-c50f951a6dd4">

@CodeK1988 请求网络后返回什么，取决于你在 IRequestHandler 的实现类中返回了什么，如果你对 RequestHandler 实现的逻辑不满意，可以改造成你想要的样子。

**Comment by Spikoss** [comment]
同步请求的时候的确是有混淆的问题，一样的代码编译运行时没问题，混淆打包后有问题，但是异步混淆打包也没问，同步请求和异步请求的代码如下：`//同步请求
        PostRequest postRequest = EasyHttp.post(ApplicationLifecycle.getInstance())
                .schedulers(ThreadSchedulers.IO);
        try {
            HttpData<UploadZipFilesBean> baseBean = postRequest
                    .api(new UploadImgFileApi()
                            .setParamsWithFile(stepId, state, "", imgFile))
                    .execute(new ResponseClass<HttpData<UploadZipFilesBean>>() {
                    });
            LogUtil.i(TAG, "uploadImgSyn--服务器返回结果：" + baseBean, false, true);
            if (baseBean != null && baseBean.getStatus() != null
                    && baseBean.getStatus().equals("success") && baseBean.getResult() != null) { 
                return "";
            } else {
                return "baseBean = null" + baseBean;
            }

        } catch (Throwable e) {
            LogUtil.e(TAG, "上传图片失败 Exception：" + e.getMessage(), false, true);
            return "Exception:" + e.getMessage();
        }`

异步请求：`EasyHttp.post(ApplicationLifecycle.getInstance())
                .schedulers(ThreadSchedulers.IO)
                .api(new UploadImgFileApi()
                        .setParamsWithFile(stepId, state, "", imgFile))
                .request(new OnHttpListener<HttpData<UploadZipFilesBean>>() {
                    @Override
                    public void onHttpSuccess(HttpData<UploadZipFilesBean> baseBean) {
                        LogUtil.i(TAG, "upload--onHttpSuccess：" + baseBean.toString(), false, true);
                    }

                    @Override
                    public void onHttpFail(Throwable e) {
                        LogUtil.e(TAG, "upload--onHttpFail：" + e.getMessage(), false, true);
                    }

                });`

**Comment by Spikoss** [comment]
应该是ResponseClass<HttpData<UploadZipFilesBean>>被混淆了，并且即使异步，如果泛型里是List集合，也会被混淆，如：HttpData<List<MyBean>>
