### ISSUE TITLE
参数是url的时候被转义了  是否可以不转义

### ISSUE THREAD

**Issue by sdjwj1118** [getActivity/EasyHttp#67]
参数是url的时候被转义了  是否可以不转义  后端不识别这种转义的 不给改

**Comment by getActivity** [comment]
小伙子，首先框架的做法是没有问题的，url 上面的参数是一定要经过转义的，抛开中文不说，一些特殊字符串肯定也是要经过转义的，我不会开放这个方法，因为这样极度不规范，但是我可以提供几个建议给你：

1. 让后台支持参数转义

2. 让后台换成 post 请求

**Comment by sdjwj1118** [comment]
本身就是post请求

**Comment by getActivity** [comment]
*  小伙子，如果你想表达的是链接中的 `https://www.so.com/?src=so.com` 被转义成 `"https:\/\/www.so.com\/?src=so.com"`，那么还是有办法解决的，你可以用此方法来解决：

``groovy
// https://mvnrepository.com/artifact/org.apache.commons/commons-text
implementation ('org.apache.commons:commons-text:1.9') {
    exclude group: 'org.apache.commons', module: 'commons-lang3'
}
``

```java
OkHttpClient okHttpClient = new OkHttpClient.Builder()
        .addInterceptor(new Interceptor() {

            @Override
            public Response intercept(Chain chain) throws IOException {
                Request request = chain.request();
                RequestBody body = request.body();
                if (body instanceof JsonBody) {
                    String json = ((JsonBody) body).getJson();
                    JsonBody newJsonBody = new JsonBody(StringEscapeUtils.unescapeJava(json));
                    request = request.newBuilder()
                            .method(request.method(), newJsonBody)
                            .build();
                }
                return chain.proceed(request);
            }
        })
        .build();
```

**Comment by sdjwj1118** [comment]
是的 这就是我想表达的  我试一下

**Comment by sdjwj1118** [comment]
![image](https://user-images.githubusercontent.com/33438073/136817175-e16ecfdd-4717-4cb4-84ef-7e2a3fb52093.png)
![image](https://user-images.githubusercontent.com/33438073/136817334-e829a9b0-f518-4b9f-bc83-b87c38ff690e.png)
经过您说的方法 通过StringEscapeUtils转义已经把\/转成了/ 但奇怪的时候最后请求的时候还是原来的\/

**Comment by sdjwj1118** [comment]
是的  我通过日志发现请求参数还是带有双斜杠的

**Comment by sdjwj1118** [comment]
实际到达服务器的参数还是双斜杠 而不是通过这个拦截器转义好的单斜杠

**Comment by sdjwj1118** [comment]
可以了 感谢

**Comment by getActivity** [comment]
小伙子，框架的版本已经更新了，更新一下远程依赖即可。

**Comment by CodeK1988** [comment]
你好 url 被endecode了，添加了okhttp的拦截器也是乱码，调试很不方便，请问怎么设置？

**Comment by getActivity** [comment]
@CodeK1988 Get 请求上面的 url 参数是一定要经过编码的，这个是 Http 的请求规范，框架无法单独为某个人进行特殊设置，建议你遵守 Http 的请求规范。
