### ISSUE TITLE
token能否不在全局设置，因为有的接口可能需要传token，有的不需要传

### ISSUE THREAD

**Issue by zs18340282344** [getActivity/EasyHttp#73]

**Comment by getActivity** [comment]
https://github.com/getActivity/EasyHttp/blob/master/HelpDoc.md#%E5%A6%82%E4%BD%95%E5%9C%A8%E8%AF%B7%E6%B1%82%E4%B8%AD%E5%BF%BD%E7%95%A5%E6%9F%90%E4%B8%AA%E5%85%A8%E5%B1%80%E5%8F%82%E6%95%B0

**Comment by getActivity** [comment]
小伙子，我文档上面不是有写了？

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。
