### ISSUE TITLE
请问怎么传递空数组  data:[]  给后台时消失了

### ISSUE THREAD

**Issue by naojiangzhalie666** [getActivity/EasyHttp#75]

**Comment by getActivity** [comment]
[EasyHttp-10.5.aar.zip](https://github.com/getActivity/EasyHttp/files/7481343/EasyHttp-10.5.aar.zip)

**Comment by getActivity** [comment]
小伙子，问题修正了，你再试试

**Comment by getActivity** [comment]
小伙子，框架的版本已经更新了，更新一下远程依赖即可。
