### ISSUE TITLE
提一个小小的建议

### ISSUE THREAD

**Issue by candebbs** [getActivity/EasyHttp#76]
有时开发时，只想看请求头的参数，但服务器返回来的json太长了，在logcat翻很长才看到请求头，能不能做一个设置，只打印请求头参数，或者只打印服务器返回来的数据，或者请求头和服务器返回来的数据，日志输出的LogTag不同，方便查看不同的输出。

**Comment by getActivity** [comment]
小伙子，这个建议无法采纳，首先这个建议太过个性化，就算开发出来也没有多少人用，如果你有这个需要，请直接关闭 EasyHttp 的日志打印，然后写 OkHttp 拦截器来做日志打印，到时候你可以自定义日志的打印规则。

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。
