### ISSUE TITLE
 data:[] 空数组丢失问题   改后好像 对象变成字符串了

### ISSUE THREAD

**Issue by naojiangzhalie666** [getActivity/EasyHttp#77]
"itemsList": [
            "{contentId=[379], itemId=321, content=}",
            "{contentId=[], itemId=328, content=}",

**Comment by getActivity** [comment]
小伙子，你用的是什么请求方式？Get 还是 Post 请求？如果是 Post 请求，用的是表单还是Json 提交参数？

**Comment by naojiangzhalie666** [comment]
Post Json



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Android轮子哥 ***@***.***&gt;
发送时间: 2021年11月8日 13:42
收件人: getActivity/EasyHttp ***@***.***&gt;
抄送: naojiangzhalie666 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[getActivity/EasyHttp]  data:[] 空数组丢失问题   改后好像 对象变成字符串了 (Issue #77)

**Comment by naojiangzhalie666** [comment]
未更新前 "itemList":[
{
"itemId":2,
"content":"填写的表单内容",  
"contentId":[],  
          }, 只是 "contentId":[],  
,没数据时 丢失 ，  更新后 "itemsList": [
"{contentId=[379], itemId=321, content=}",
"{contentId=[], itemId=328, content=}",

**Comment by getActivity** [comment]
把你的 API 类及调用的代码发来我看一下

**Comment by naojiangzhalie666** [comment]
public class SaveApplyApi  implements IRequestApi , IRequestType {

    /**
     * bankId : 12
     * enterpriseId : 6
     * submitType : 0
     * formId : 2
     * itemList : [{"itemId":2,"content":"填写的表单内容","contentId":[]},{"itemId":2,"content":"","contentId":[1,2,3]}]
     */

    private Long bankId;
    private Long enterpriseId;
    private String submitType;
    private Long formId;
    private List<ItemListBean> itemsList;

    public SaveApplyApi setBankId(Long bankId) {
        this.bankId = bankId;
        return this;
    }

    public SaveApplyApi setEnterpriseId(Long enterpriseId) {
        this.enterpriseId = enterpriseId;
        return this;
    }

    public SaveApplyApi setSubmitType(String submitType) {
        this.submitType = submitType;
        return this;
    }

    public SaveApplyApi setFormId(Long formId) {
        this.formId = formId;
        return this;
    }

    public SaveApplyApi setItemsList(List<ItemListBean> itemList) {
        this.itemsList = itemList;
        return this;
    }



    @Override
    public String getApi() {
        return "app/loan/saveApply";
    }

    @Override
    public BodyType getType() {
        return BodyType.JSON;
    }

    public static class ItemListBean {
        /**
         * itemId : 2
         * content : 填写的表单内容
         * contentId : []
         */

        private int itemId;
        private String content;
        private List<?> contentId;
        private List imageList ;
        public void setImageList(List imageList) {
            this.imageList = imageList;
        }

        public void setItemId(int itemId) {
            this.itemId = itemId;
        }

        public void setContent(String content) {
            this.content = content;
        }

        public void setContentId(List<?> contentId) {
            this.contentId = contentId;
        }
    }
}



 EasyHttp.post(this)
                .api(new SaveApplyApi().setSubmitType(type)
                        .setBankId(Long.valueOf(bankId))
                        .setEnterpriseId(Long.valueOf(applyLoanBean.getId()))
                        .setFormId(Long.valueOf(formId))
                        .setItemsList(itemListBeanList))
                .request(new HttpCallback<HttpData<Object>>(this) {
                    @Override
                    public void onSucceed(HttpData<Object> data) {
                    }
                    @Override
                    public void onFail(Exception e) {
                        super.onFail(e);

                    }
                });

**Comment by getActivity** [comment]
小伙子，你用的框架是什么版本的？

**Comment by naojiangzhalie666** [comment]
这个是9.0 我换成最新的 发现不好使又退回了  我看使用时只是 
@Override
    public BodyType getType() {
        return BodyType.JSON;
    }改了

**Comment by getActivity** [comment]
[EasyHttp-10.6.aar.zip](https://github.com/getActivity/EasyHttp/files/7494744/EasyHttp-10.6.aar.zip)

**Comment by getActivity** [comment]
小伙子，问题修复了，你试一下这个包看看有没有什么问题

**Comment by naojiangzhalie666** [comment]
好的 我看一下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Android轮子哥 ***@***.***&gt;
发送时间: 2021年11月8日 14:34
收件人: getActivity/EasyHttp ***@***.***&gt;
抄送: naojiangzhalie666 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[getActivity/EasyHttp]  data:[] 空数组丢失问题   改后好像 对象变成字符串了 (Issue #77)





 
小伙子，问题修复了，你试一下这个包看看有没有什么问题
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by getActivity** [comment]
小伙子，可以了没？

**Comment by naojiangzhalie666** [comment]
可以了 能更新一下吧



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Android轮子哥 ***@***.***&gt;
发送时间: 2021年11月8日 14:50
收件人: getActivity/EasyHttp ***@***.***&gt;
抄送: naojiangzhalie666 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[getActivity/EasyHttp]  data:[] 空数组丢失问题   改后好像 对象变成字符串了 (Issue #77)





 
小伙子，可以了没？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by getActivity** [comment]
可以的，稍等一下，我更新一下远程依赖

**Comment by getActivity** [comment]
小伙子，远程依赖已经更新了
