### ISSUE TITLE
关于定时请求问题

### ISSUE THREAD

**Issue by victorKaiDong** [getActivity/EasyHttp#78]
轮子哥，我想请问一下，我想在每隔5秒发起一次请求的场景下，使用EasyHttp，除了WebSocket，有什么别的好方法么？

**Comment by getActivity** [comment]
Http 是短连接协议，不适合发起轮询请求，相比之下使用长链接协议就比较合适，但是你说不用 WebSocket，那么我也没有更好的方法了。

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by victorKaiDong** [comment]
好的，那我再考虑下别的方案吧，多谢
