### ISSUE TITLE
全局参数加密

### ISSUE THREAD

**Issue by 979881765** [getActivity/EasyHttp#79]
对所有接口（也有可能个别接口参数不做加密）的参数进行自定义加密，这种怎么统一实现呢？

**Comment by getActivity** [comment]
小伙子，框架文档上面没有写？

**Comment by getActivity** [comment]
小伙子，结果咋样了？还有你如果长时间不回复的话，我会认为你的问题已经解决了，我就会主动关闭这个 issue 了。

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。
