### ISSUE TITLE
EasyHttp 请求为什么都是在UI线程，并发请求的时候容易ANR

### ISSUE THREAD

**Issue by DodoSpringLove** [getActivity/EasyHttp#82]
EasyHttp 请求为什么都是在UI线程，并发请求的时候容易ANR

**Comment by getActivity** [comment]
小伙子，你用的是同步请求还是异步请求？

**Comment by getActivity** [comment]
还有你是怎么知道请求在 UI 线程中执行的？

**Comment by DodoSpringLove** [comment]
> 


> 还有你是怎么知道请求在 UI 线程中执行的？

都ANR了呀...

**Comment by DodoSpringLove** [comment]
> 小伙子，你用的是同步请求还是异步请求？

异步请求，在Services里调的

**Comment by getActivity** [comment]
小伙子，你去看看 Demo 上面的同步请求是怎么写的

**Comment by DodoSpringLove** [comment]
> 小伙子，你去看看 Demo 上面的同步请求是怎么写的

你说的是这个吗？
![image](https://user-images.githubusercontent.com/26377272/142991966-762565b3-b078-41ca-b570-02daf01d50ea.png)

**Comment by getActivity** [comment]
除了这个还能有哪个？

**Comment by DodoSpringLove** [comment]
感谢，找到问题了，小伙学艺不精，含请海涵～

**Comment by getActivity** [comment]
小伙子，遇到问题第一时间不是来问我，而是应该自己先排查和研究。
