### ISSUE TITLE
请问如何获取下载或者上传任务的进行状态？

### ISSUE THREAD

**Issue by Heart-Beats** [getActivity/EasyHttp#83]
请问如何获取下载或者上传任务的进行状态，我看目前的Tag仅仅是用来取消任务的。目前有这种场景，有一个下载列表正在下载中，然后我取消其中一个请求，移除了RecyclerView 的一个Item 导致了ViewHolder 重建， ViewHolder 又在创建时绑定了发起请求，这时就会导致请求多次发送，但是我没有办法在框架中判断是否已存在任务

**Comment by getActivity** [comment]
小伙子，你下载的时候用一个集合记录一下这个下载任务的 id 或者标记，ViewHolder 绑定数据的时候再从集合中判断不就可以了么？

**Comment by Heart-Beats** [comment]
> 小伙子，你下载的时候用一个集合记录一下这个下载任务的 id 或者标记，ViewHolder 绑定数据的时候再从集合中判断不就可以了么？

我昨晚使用此方式尝试了一下，发现在创建ViewHolder 时发起请求不满足，移除 item 时对应的状态 view 由于被移除了，重新创建时根据集合判断任务已存在就没有办法给它在回调里更新了，写法上确实有问题，目前没找到好的方式规避就没做移除 item 了

**Comment by getActivity** [comment]
小伙子，因为 EasyHttp 下载模块做得还是比较简单的，对一些比较复杂的场景会有比较有大的障碍，不过这个已经在我迭代计划范围之内了，你要是觉得 EasyHttp 没有办法满足你的需求，建议你先通过其他方式来实现。

**Comment by Heart-Beats** [comment]
> 小伙子，因为EasyHttp 下载模块还是比较简单的，对一些比较复杂的场景会有大的障碍，不过已经在我计划范围之内了，你觉得EasyHttp 没有满足你的需求，建议你先通过其他方式来实现。

好的大佬，其实昨天最先看的是 OkGo， 他的下载上传管理应该是可以满足需求的，但是看这个库很久没更新了怕有坑，目前我这业务场景也是比较简单的，暂时就先这样我看看能不能优化下

**Comment by getActivity** [comment]
可以的，小伙子，issue 我先关闭了，后续有问题再反馈。

**Comment by Heart-Beats** [comment]
> 可以的，小伙子，发出我先关闭了，孩子有问题再反馈。

好的，没问题
