### ISSUE TITLE
CacheMode的USE_CACHE_AFTER_FAILURE不起作用

### ISSUE THREAD

**Issue by hlla** [getActivity/EasyHttp#84]
1. 网络请求失败去读缓存，但`USE_CACHE_AFTER_FAILURE`都没写过缓存。
[writeCache](https://github.com/getActivity/EasyHttp/blob/ba1231ee0c2b00f0a52d58f79d7593e6bdb04b0b/library/src/main/java/com/hjq/http/config/IRequestHandler.java?_pjax=%23js-repo-pjax-container%3Afirst-of-type%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%3Afirst-of-type%2C%20%5Bdata-pjax-container%5D%3Afirst-of-type#L56)在调用的两个地方，判断条件都没有`CacheMode.USE_CACHE_AFTER_FAILURE`
![writeCache_判断条件](https://user-images.githubusercontent.com/7305059/145339961-874b1cde-10fb-4b92-ae84-3c39b08995bb.png)
2. `NormalCallback`的[start()](https://github.com/getActivity/EasyHttp/blob/ba1231ee0c2b00f0a52d58f79d7593e6bdb04b0b/library/src/main/java/com/hjq/http/callback/NormalCallback.java?_pjax=%23js-repo-pjax-container%3Afirst-of-type%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%3Afirst-of-type%2C%20%5Bdata-pjax-container%5D%3Afirst-of-type#L47)方法中`if (cacheMode != CacheMode.USE_CACHE_ONLY && cacheMode != CacheMode.USE_CACHE_FIRST)`
这里的判断条件是不是有问题

**Comment by getActivity** [comment]
[EasyHttp-10.8.aar.zip](https://github.com/getActivity/EasyHttp/files/7682688/EasyHttp-10.8.aar.zip)

**Comment by getActivity** [comment]
经过核实，确实存在这个问题，已经纠正了，多谢小伙子的提醒，你可以下载这个包测试看看。
