### ISSUE TITLE
请求接口如果是真的动态的则不太方便

### ISSUE THREAD

**Issue by fismas** [getActivity/EasyHttp#87]
## 建议收集

1.如果请求接口地址是从服务器获取的话，这种继承方式则不太友好也不方便；感觉还是直接传入url地址方式更加灵活些，当时继承方式也可以保留，另外也可扩展个方法可以直接传入url地址来请求，这样就更完美了

2.同步请求支持kotlin协程方式吗？

**Comment by getActivity** [comment]
1. 第一个问题我在文档中已经有写了：https://github.com/getActivity/EasyHttp/blob/master/HelpDoc.md#%E6%88%91%E4%B8%8D%E6%83%B3%E4%B8%80%E4%B8%AA%E6%8E%A5%E5%8F%A3%E5%86%99%E4%B8%80%E4%B8%AA%E7%B1%BB%E6%80%8E%E4%B9%88%E5%8A%9E

2. 怎么和协程一起使用，这个是你的个人使用问题，需要你自行研究一下，我目前不处理和框架无关的问题。

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。
