### ISSUE TITLE
接口超时，要怎么去监听超时的回调呢

### ISSUE THREAD

**Issue by lianghuiyong** [getActivity/EasyHttp#88]
## 问题描述

* 框架版本：10.8

* 问题描述：接口超时，要怎么去监听超时的回调呢？

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/147215407-8dda4001-bf47-4255-917f-c0492b92e4de.png)

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/147215529-706a0657-632d-4010-8e5a-d1cc3dcee63f.png)

**Comment by lianghuiyong** [comment]
嗯嗯，看到了，谢谢大佬！
