### ISSUE TITLE
Kotlin实现该框架抽象方法的建议

### ISSUE THREAD

**Issue by GitHubCHF** [getActivity/EasyHttp#90]
## 建议收集

* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）
 Kotlin使用框架所有接口实现都会附加?导致做一些没必要的判空处理
* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）
*  可否在必定不为空的参数下新增@NotNull注解来优化该问题

**Comment by getActivity** [comment]
小伙子，你指的是哪些接口的参数需要加 `@NotNull` 注解？

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。
