### ISSUE TITLE
帮助文档过时了，具体用法需要更新

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [getActivity/EasyHttp#91]
## 建议收集

* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）
![image](https://user-images.githubusercontent.com/54784104/147807982-445811cc-d38d-4899-b7e2-66f20b66f910.png)
![image](https://user-images.githubusercontent.com/54784104/147808007-40ab730e-b542-4a61-b045-302192230cdd.png)

* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）
现在应该怎么配置服务器设置？

**Comment by getActivity** [comment]
小伙子，这个不是文档过时了，而是你的框架版本过时了，在 EasyHttp 最新版本上面 IRequestServer 是没有 getPath 这个方法的。

**Comment by SaltedFish-Extreme** [comment]
> 小伙子，这个不是文档过时了，而是你的框架版本过时了，在 EasyHttp 最新版本上面 IRequestServer 是没有 getPath 这个方法的。

不是啊，我用的最新的10.8版本，连IRequestServer这个类都没有，在10.2里面就有
![image](https://user-images.githubusercontent.com/54784104/147819928-70446a0b-963c-4f41-98a4-f97f5147820e.png)

**Comment by getActivity** [comment]
有的，小伙子，你回去看看 [IRequestServer.java](https://github.com/getActivity/EasyHttp/blob/master/library/src/main/java/com/hjq/http/config/IRequestServer.java) 这个类

**Comment by SaltedFish-Extreme** [comment]
> 小伙子，这个不是文档过时了，而是你的框架版本过时了，在 EasyHttp 最新版本上面 IRequestServer 是没有 getPath 这个方法的。

![image](https://user-images.githubusercontent.com/54784104/147820123-abacec26-2bf0-45c9-aa84-25da8247aa57.png)

**Comment by SaltedFish-Extreme** [comment]
> 有的，小伙子，你回去看看 [IRequestServer.java](https://github.com/getActivity/EasyHttp/blob/master/library/src/main/java/com/hjq/http/config/IRequestServer.java) 这个类

我用10.2就自动导了这个类，10.8就这样

**Comment by getActivity** [comment]
@SaltedFish-Extreme Demo 有这个问题？

**Comment by getActivity** [comment]
我这里明明是好好的。

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/147820209-3b724747-96f7-4eb0-b00c-f670b944b977.png)

**Comment by SaltedFish-Extreme** [comment]
> 我这里明明是好好的。

demo没问题，但是你随便开个项目导入easyhttp依赖和okhttp依赖就这样

**Comment by SaltedFish-Extreme** [comment]
@getActivity 
![image](https://user-images.githubusercontent.com/54784104/147820304-e35dd235-55cc-480f-bbe6-ecc7ff9e3835.png)

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/147821900-b965e5a1-3949-4382-b43d-70e449dd7cde.png)

**Comment by getActivity** [comment]
小伙子，你上这里找找看这个类存不存在

**Comment by SaltedFish-Extreme** [comment]
> 小伙子，你上这里找找看这个类存不存在

啊，好了，没问题了
