### ISSUE TITLE
在Application中设置拦截器添加Header 不执行

### ISSUE THREAD

**Issue by 979881765** [getActivity/EasyHttp#92]
## 问题描述

* 框架版本：10.8
拦截器添加请求头并没有执行，如果使用.addHeader("token","7123456") 可以正常添加

        EasyConfig.with(okHttpClient)
                // 是否打印日志
                .setLogEnabled(true)
                // 设置服务器配置
                .setServer(new RequestServer())
                // 设置请求处理策略
                .setHandler(new RequestHandler(application))
                // 设置请求重试次数
                .setRetryCount(1)
                // 设置请求参数拦截器
                .setInterceptor(new IRequestInterceptor() {
                    @Override
                    public void interceptArguments(HttpRequest<?> httpRequest, HttpParams params, HttpHeaders headers) {
                        // 添加全局请求头
                        headers.put("token", "123456");
                    }
                })
                .addHeader("token","795e9a84-e10a-46ef-84f7-3e292b668996")
                .into();

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/147823078-732b489d-7449-4a52-8dc7-cffafbe39c60.png)

**Comment by getActivity** [comment]
小伙子，我试过了是没有问题的，你试试看 demo 有没有这个问题？

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。
