### ISSUE TITLE
下载文件列表

### ISSUE THREAD

**Issue by Reginer** [getActivity/EasyHttp#93]
## 建议收集

* 下载功能目前只看到能支持下载一个文件

* 可否增加支持下载文件列表功能，设置的是保存路经文件夹，下载完成后，回调的是下载完的文件列表

**Comment by getActivity** [comment]
小伙子，批量下载功能这个后期会考虑加上的，多谢小伙子的提醒，我建议你先用别的框架来实现。

**Comment by Reginer** [comment]
好，接受建议

**Comment by xihan123** [comment]
着急的话 只要要下载的文件不是很多 定义一个类 里面设定有保存路径、下载地址、md5 之类的  用for循环下载不就完了，虽然麻烦了一点，但是可以解决燃眉之急

**Comment by getActivity** [comment]
小伙子，我后面再思考了一下，最终决定还是不加批量下载的功能，因为 EasyHttp 的定位是网络请求框架，不是下载框架，这两者有相似之处，但却属于两个不同类别的，如果你需要使用批量下载，建议使用其他第三方框架实现。

**Comment by Reginer** [comment]
我认为你说的有道理，这应该是下载库做的事情 。

**Comment by Reginer** [comment]
我发现个问题，不知道大佬有没有打算搞个下载库。像这种http网络库竞争压力很大呀。下载库基本都没什么人维护。
