### ISSUE TITLE
我不想一个接口写一个类

### ISSUE THREAD

**Issue by CPC-Coder** [getActivity/EasyHttp#95]
## 建议收集

* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）
* 缺少通用型操作

* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）
* Net.api("/app/chargeEquip/sendCharge")
                        .addParam("ckLabelId",equip.getCkLabelId())
                        .addParam("electricity",equip.getElectricity())
                        .addParam("ip",equip.getCabinetIp())
                        .addParam("place",msg.getPosition()+"")
                        .addParam("time", TimeUtils.getNowString())
                        .addParam("type",msg.getType()+"")
                        .callback(new Callback_base() {
                            @Override
                            public void onSuccess(Response response, String origin, Object o) {
                                

                            }
                        });

**Comment by CPC-Coder** [comment]
因为有时候并不想写api,可以直接这么操作
这是我封装的网络请求框架 只是自己用下
但是这种代码比较集中  感觉挺好

**Comment by CPC-Coder** [comment]
以map的形式传入 参数  , 然后根据实际情况  做get post方式请求

**Comment by CPC-Coder** [comment]
封装掉一个框架,可以不用过于依赖这个框架,隔离框架

**Comment by CPC-Coder** [comment]
目前我自己封装了okhttp,以这种形式 写,希望可以封装easyhttp,以防框架停止维护等异常情况,隔离框架

**Comment by getActivity** [comment]
小伙子，你如果不喜欢 EasyHttp 的设计理念，可以考虑不用 EasyHttp，你完全可以依照自己的习惯来写代码，又或者直接用 OkGo，这些都是可以的。

**Comment by CPC-Coder** [comment]
接口参数的 Key 值是动态变化的该怎么办
get 没办法 用动态的方式么

**Comment by getActivity** [comment]
文档上面不是有写了？

**Comment by CPC-Coder** [comment]
谢谢轮子哥 写的很赞
