### ISSUE TITLE
感觉不大适合配合rx

### ISSUE THREAD

**Issue by CPC-Coder** [getActivity/EasyHttp#96]
## 建议收集

* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）
* rx以流的形式走,有点强行配合rx

* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）

**Comment by CPC-Coder** [comment]
希望能真正适配下 rx(没办法 莫名遇到公司里同事一定要走rx 只能跟大众走 哎~)

**Comment by getActivity** [comment]
小伙子，网络请求框架为什么一定要和 RxJava 耦合在一起才行呢？

**Comment by getActivity** [comment]
如果你们的公司人员有这个需求，可以自行下载框架的源码进行修改，或者直接将网络请求框架更换成 Retrofit。
