### ISSUE TITLE
Post请求中文乱码问题

### ISSUE THREAD

**Issue by lzy0016** [getActivity/EasyHttp#97]
## 问题描述

* 框架版本：10.8

* 问题描述：post请求时  参数传中文后台接收是乱码  我用Profiler看的确是   但是log打印又是正常的  提交方式是表单提交   用get请求是正常的

* 复现步骤：正常提交

* 是否必现：是

* 手机信息：小米 8

## 请回答

* 是部分机型还是所有机型都会出现：华为的也会

* 框架最新的版本是否存在这个问题：是

* 是否已经查阅框架文档还未能解决的：框架文档没有找到设置编码方式

* issue 是否有人曾提过类似的问题：是  有一条  但是没有反馈就关闭了

* 是否可以通过 Demo 来复现该问题：是

* 使用原生的 OkHttp 来实现是否也会出现该问题：是/否（排查一下是不是 EasyHttp 的代码存在问题导致的）

![image](https://user-images.githubusercontent.com/9514526/150087052-f8979d16-7ede-4755-85a6-47f8dcf62a47.png)
![image](https://user-images.githubusercontent.com/9514526/150087210-9aaf8da2-1769-4e2d-af8f-a08c8176a99b.png)

**Comment by getActivity** [comment]
使用原生的 OkHttp 来实现是否也会出现该问题：是/否

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。
