### ISSUE TITLE
同一时间请求2个接口，会出现服务器响应异常，请稍后再试, responseCode: 500, message: Internal Server Error

### ISSUE THREAD

**Issue by lidaming940614** [getActivity/EasyHttp#98]
## 问题描述

* 框架版本：10.8

* 问题描述：同一时间请求2个接口，会出现服务器响应异常，请稍后再试, responseCode: 500, message: Internal Server ### `Error，如果其中加入1个延迟请求，就不会出现此错误`

* 复现步骤：XXX

* 是否必现：经常

* 手机信息：Android 10

## 请回答

* 是部分机型还是所有机型都会出现：全部

* 框架最新的版本是否存在这个问题：是

* 是否已经查阅框架文档还未能解决的：是

* issue 是否有人曾提过类似的问题：否

* 是否可以通过 Demo 来复现该问题：是

* 使用原生的 OkHttp 来实现是否也会出现该问题：否

## 其他

* 提供报错堆栈（如果有报错的话必填）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
<img width="554" alt="image" src="https://user-images.githubusercontent.com/28616817/154213465-9b98bad3-5309-491f-999a-ea54fcf02b3d.png">

**Comment by getActivity** [comment]
小伙子，500 是服务器解析出现问题，这个跟框架又有什么关系呢？

**Comment by getActivity** [comment]
超过三天没有响应，自动关闭此 issue。
